### ISSUE TITLE
[FEATURE]Suggestion

### ISSUE THREAD

**Issue by zasnaz** [booksaw/BetterTeams#1]
Hello i don't know if this feature is available or not but i want to appear the name of teams over the players heads if this available i hope you explain how to do it . if not i hope you add this in the next update and thank you .

**Comment by booksaw** [comment]
I will see what I can do. If this works as you hope it will be included in the next update.

**Comment by zasnaz** [comment]
Thank you so much.

**Comment by booksaw** [comment]
This feature is included within the 3.0.5 update

**Comment by booksaw** [comment]
The two agreed features have been implemented and will be released in version 3.0.7. 
1. Make it configurable if the team name is displayed as a prefix or a suffix.
2. Add a permission node for the team name display, so you can choose to disable it for specific players (ie donors)

**Comment by zasnaz** [comment]
Hey I just updated the plugin and I don't know how to make the team name appears as suffix 
could you please explain?

**Comment by booksaw** [comment]
Change the value 'displayTeamName: true' to 'displayTeamName: suffix'

**Comment by zasnaz** [comment]
Sorry but it didn't work, I changed the value 'displayTeamName: prefix' to 'displayTeamName: suffix'
on the config file
