### ISSUE TITLE
[FEATURE] Team Home Suggestion

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#10]
**Is your feature request related to a problem? Please describe.**
1. Add config option to enable cooldown for using '/team home'
2. Add config option to modify cooldown time usage.
3. Add config option to enable cost per '/team home' command usage.
4. Add config option to set cost to create team home using '/team sethome'.
5. Add a new command to delete team home.
6. Separate permission for '/team home' & '/team sethome' to **betterteams.home** & **betterteams.sethomes**
7. Add a new command for server admins to teleport to any team homes.

**Describe the solution you'd like**
1. New permission to bypass '/team home' cooldown.     - **betterteams.home.bypass**
2. New command to delete team sethome using '/team removehome' or '/team delhome'  - **betterteams.removehome**
3. New command for server admins to teleport to team homes using '/team home (team)'     - **betterteams.admin.home**  

**Describe alternatives you've considered**
I wanted to use cmi's built in cooldown/warnup command feature but I'm afraid it might not work.

**Additional context**
None

**Comment by booksaw** [comment]
All ideas here will be added in version 3.0.9

**Comment by booksaw** [comment]
Cost and cooldown of plugins will be available to modify for all /team commands in the file betterteams/team.yml. This file is created when the plugin first launches on version 3.0.9.

Added /team delhome
Added /teama home <team> 

/team sethome, /team unban and /team demote have all been separated from their partner commands.

**Comment by booksaw** [comment]
The system of command cooldowns and pricing has been improved for the next update. In the next update, only when a command is successful will it trigger the cooldown and price.
