### ISSUE TITLE
AllyLimit error

### ISSUE THREAD

**Issue by giantfurkii** [booksaw/BetterTeams#100]
even though I make the ally limit 1, it's unlimited.
![1](https://user-images.githubusercontent.com/78488589/114282318-c8fa3e80-9a4b-11eb-9031-3ce188c6f0c2.png)
![2](https://user-images.githubusercontent.com/78488589/114282319-c992d500-9a4b-11eb-9172-1790a6da346f.png)

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update.
