### ISSUE TITLE
/team top error

### ISSUE THREAD

**Issue by giantfurkii** [booksaw/BetterTeams#103]
/ team top command sometimes works, sometimes not.
![image](https://user-images.githubusercontent.com/78488589/114764581-cca00500-9d6c-11eb-902f-4d03aa142472.png)
![image](https://user-images.githubusercontent.com/78488589/114764613-d6296d00-9d6c-11eb-84b5-3c76ba3db82d.png)

**Comment by booksaw** [comment]
I cannot reproduce this error, is this a recurring error or has it only happened a single time?

**Comment by giantfurkii** [comment]
a constant error, sometimes the command works, sometimes it does not work.

**Comment by booksaw** [comment]
This bug should have been fixed and will be included in the next update.
