### ISSUE TITLE
[FEATURE] chunk loading

### ISSUE THREAD

**Issue by Jaredy00** [booksaw/BetterTeams#104]
Could you add support for teams to keep x amount of chunks loaded while players are offline would be useful for auto farms
and add configuration to set the limit for the number of chunk each team is allowed per team level

**Comment by booksaw** [comment]
What would the commands to force load chunks be. etc.
You need to be more specific than this

**Comment by Jaredy00** [comment]
/team keeploaded (x z of the chunk)
example /team keeploaded 592 196

**Comment by booksaw** [comment]
Ive had a look into this and sadly I do not think it fits the style of betterteams in its current state. In the near future, an integration with a claims plugin is going to be introduced into betterteams. Until that feature has been released for a while so I can measure the response.
You can request this feature again in a few months as the way betterteams is evolving may mean that it fits within the style of betterteams.
