### ISSUE TITLE
TeamLimit error

### ISSUE THREAD

**Issue by giantfurkii** [booksaw/BetterTeams#108]
teamLimit: although it is 8, sometimes a maximum of 5 people are taken.

![1619032091976](https://user-images.githubusercontent.com/78488589/115828484-6e32f080-a416-11eb-9984-c821623195ea.jpg)

**Comment by booksaw** [comment]
Could you send a screenshot of the levels section of your config.yml please

**Comment by booksaw** [comment]
This issue is being closed due to inactivity. 
If you wish to continue this discussion please create a new issue linking to this one answering any questions.
