### ISSUE TITLE
[BUG] EssentialsX /back incompatibility

### ISSUE THREAD

**Issue by MaximilianGaedig** [booksaw/BetterTeams#109]
**Describe the bug**
EssentialsX /back incompatibility

**To Reproduce**
Steps to reproduce the behaviour:
1. Run /team home
2. Run /back

**Expected behaviour**
On typing /back i should go back to the location you teleported to when using /team home

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): git-Paper-608
- BetterTeams version (found by running /version BetterTeams):  3.1.24
- EssentialsX version:  2.18.2.0

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update.
