### ISSUE TITLE
[FEATURE] New Commands

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#11]
**Is your feature request related to a problem? Please describe.**
1. Add a new command to view all default commands using '/team help'.
2. Add a new command to view plugin version '/team version'.
3. Add a new command to view top teams instead from holograms using '/team top' and '/team top (teams)'.

**Describe the solution you'd like**
1. New permission for  '/team help'          - **betterteams.help**
2. New permission for '/team version'       - **betterteams.version**
3. New permission for '/team top'             - **betterteams.top**

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by booksaw** [comment]
/team help and the admin alternative /teama help are both already within the program, if you are having problems with them, please make a bug report showing what the issue is. 
/teama version will be added in 3.0.9 (using /teama instead of /team as it is an admin command) 
/team top will be added in version 3.0.9

**Comment by BboyZeroOne** [comment]
Sorry, /team help is default for players, which only show all default/basic commands for players.

**Comment by booksaw** [comment]
Sorry, I'm not quite understanding. 
At the moment (unless you have custom help messages enabled), when running /team help, players should only be shown the commands that they have permissions to run. 
What exactly are you proposing should be changed about this?

**Comment by BboyZeroOne** [comment]
Based on the commands and permissions list, I don't seem to see the '/team help' command nor permission.
https://github.com/booksaw/BetterTeams/wiki/Permissions

If the command/permission has already exist, then you can ignore the suggestion! Sorry about that haha

**Comment by booksaw** [comment]
Ah, I understand. It does not appear on the permission list. Currently, if you have access to the permission `betterTeams.standard` which allows the user to do /team, it is assumed that the player should be able to /team help to view the commands that are available for them to run.

Knowing this, do you want me to add a specific permission node for betterteams.help?

**Comment by BboyZeroOne** [comment]
I think it would be redundant to add a specific permission node since it already exist for betterTeams.standard.

I guess we can go ahead with the other two suggestions, sorry for the trouble!

**Comment by booksaw** [comment]
Not a problem 😄.

All other suggested features (/teama version and /team top) have been added to version 3.0.9 along with an additional command /team rank [team].
