### ISSUE TITLE
CRASH ERROR

### ISSUE THREAD

**Issue by giantfurkii** [booksaw/BetterTeams#111]
https://mclo.gs/hj5m7Fp
My Survival server froze for 10 seconds. and I think I've encountered these errors in the panel about your plugin.

**Comment by booksaw** [comment]
I have encountered the same problem as the last issue you created. 
Please use a website which does not delete errors after 7 days, as it is often over 7 days before I have time available to fix it.
You have 20 days to reply to this issue with the correct error message, or this issue will be closed.

**Comment by booksaw** [comment]
This issue has been inactive for over a month and will be closed, if you wish to respond to the question please open a new issue referencing this one
