### ISSUE TITLE
[BUG] Console error

### ISSUE THREAD

**Issue by youdontmeanmuch** [booksaw/BetterTeams#112]
**Describe the bug**
Giant console error when  teams with spaces in name/tag are created or changed.

**To Reproduce**
Steps to reproduce the behaviour:
1.  /team create  TEAM NAME WITH SPACES
2. /team tag TAG WITH SPACES
3. /team title TITLE WITH SPACES

**Expected behaviour**
I expected the team name/title to support spaces but not the team tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/82125796/116169216-10720300-a6b9-11eb-8728-c1f511ae1f98.png)

**Details**
This server is running Purpur version git-Purpur-1056 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
BetterTeams Version 3.1.24

**Additional context**
n/a

**Comment by booksaw** [comment]
I will not add an option to add spaces to team names, as many servers have not implemented the team tag feature but instead use the team name in its place. The team description can be used for more details about the team.

I will fix the bug in the next update.
