### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by youdontmeanmuch** [booksaw/BetterTeams#113]
**Is your feature request related to a problem? Please describe.**
I would love to be able  to further customt help message.

**Describe the solution you'd like**
I would like the [BetterTeams]  prefix to not be on every line of the custom help option. Here is a screenshot as an example. 
The repeat of [HardcoreEssence] is ugly  and I can't  find a way to remove it without not using custom help.
**Describe alternatives you've considered**
n/a
**Additional context**
![image](https://user-images.githubusercontent.com/82125796/116169294-431bfb80-a6b9-11eb-9fb7-c130c689cfaa.png)

**Comment by booksaw** [comment]
As already described you can use fullyCustomHelpMessages.
I do not intend to remove the prefix as it helps differentiate the help messages from the rest of the chat. The longer prefix is a decision you have made. 
Additionally, if I added a config option for it it would just cause a more cluttered config.
