### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by youdontmeanmuch** [booksaw/BetterTeams#114]
**Is your feature request related to a problem? Please describe.**
My feature request is NOT related to a problem. I would love if there was an option added to the configuration to enforce tags in front of members names. I know there is a tag prefix however whenever  a team doesn't have a tag it reverts to the team name. I  would love to have 30+ Character Team names but force players  to display a 4 letter tag infront of their name instead of a 30 character long name.

**Describe the solution you'd like**
^

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by booksaw** [comment]
How would the plugin handle teams which have not yet set their tag?

**Comment by youdontmeanmuch** [comment]
(Inserting message from Discord as requested) How would the plug-in handle teams which have not set their tag? Well if the new command is /team create <Name> <Tag> then teams will always have a tag to display. Of course this could be a toggle able feature in the config for users to decide whether or not they want members of their server to be forced to create a tag along side the name. If it didn’t work like that, then teams without a tag simply couldn’t be created unless they provide a tag, or pre generate a tag with the first 4 words of the name they chose. Ex: they choose the name Hollow but didn’t provide a tag name so it automatically defaulted to HOLL. It doesn’t have to be the fist 4 either, it can also be the number provided in the config for the max tag count.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the sugggestion.
