### ISSUE TITLE
[FEATURE] Compatibility with zKoth Plugin

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#12]
**Is your feature request related to a problem? Please describe.**
A feature. Make BetterTeams be compatible with KOTHs plugins namely zKOTH.
https://www.spigotmc.org/resources/zkoth-king-of-the-hill.76749/

This would allow more possibilities for servers with pvp/raiding/koth/events/mini-games aspect be able to use BetterTeams plugin.

**Describe the solution you'd like**
Example Usage:
1. When a team captures a KOTH, it will show in the team's '/team info' which KOTH locations were captured by the team/team members.
It will also influence the rankings of teams in team top hologram.
2. Servers could organize team-based events using zKOTH. The higher the amount of KOTHs captured by a team, the higher the team ranking.

**Describe alternatives you've considered**
None

**Additional context**
This is a small suggestion, hopefully it will be implemented. Thanks!

**Comment by booksaw** [comment]
I like the idea of integrating better teams into more plugins. The problem with zKoth is though there is good documentation for developers, the plugin is a premium plugin which I do not have access to. 
For me to add support I would need access to the plugin so I could actually test it.

**Comment by BboyZeroOne** [comment]
I could send you a copy personally with the permission from the devs. Is that okay for you? My discord ID: BboyZeroOne#6251

**Comment by booksaw** [comment]
I have sent you a request on discord.

**Comment by booksaw** [comment]
I have added integration with zkoth. 
When you win a Koth, a configurable amount of points will be awarded to your team (found in the config) 
Displaying in /team info would not make sense, as the best it could do is display all the koths, that the last time they ran, that team won. But as there is no way of detecting when a Koth arena is deleted, those Koth strings will remain indefinitely.
