### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by TrPythonx** [booksaw/BetterTeams#124]
Hi can u add config;
Events 
Kill / break / place / enchant / fishing etc.

**Comment by booksaw** [comment]
I have looked into implementing this feature but I have more questions: 
by break do you mean they get score for every block a player places. This applies to place as well 

With enchant do you mean a player gets score for enchanting, or are you thinking of it relating to the level of the enchantment or the the specific enchantment.

With fishing the same questions, how would you attain score from fishing.

If you are suggesting more complicted triggers for score, how would you format the possibilities in the config in a way that other users would be able to understand.

**Comment by booksaw** [comment]
This issue is being closed due to inactivity. If you want to respond to the questions, make a new issue linking this one.
