### ISSUE TITLE
[FEATURE] Compatibility with DefensiveTurrets Plugin

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#13]
**Is your feature request related to a problem? Please describe.**
A feature. Make BetterTeams be compatible with DefensiveTurret Plugin.

https://www.spigotmc.org/resources/defensiveturrets-defend-yourself-using-turrets-1-8-1-15.67188/

This would allow more possibilities for servers with pvp/raiding/koth/events/mini-games aspect be able to use BetterTeams plugin.

**Describe the solution you'd like**
Example Usage:
The turret placed by a team member will not attack any team or ally members. It will only attack neutral players.

**Describe alternatives you've considered**
None

**Additional context**
I'm not sure if the compatibility feature should be done here or their side. I hope it could be implemented, thanks! <3

**Comment by BboyZeroOne** [comment]
I have also suggested this to the plugin developer. He said BetterTeams does not have a developer API.

**Comment by booksaw** [comment]
I will work on creating documentation for other developers once version 3.0.9 is released as most backend functions are simple to use, I will just need to add the needed documentation to walk users through the process.

**Comment by booksaw** [comment]
Looking at the defensive turret API, there are no events available when a turret targets a player, only when the turret kills a player this means I think it would be easier if the Defensive Turrets developer adds the code into their plugin. (if they add more developer support I would happily add it on my end).
I have created a way to access my plugins documentation and a brief explanation of how the plugin works [within the wiki](DefensiveTurrets ). Hopefully, this will help with integration. 

I am going to leave this feature request open for now, please use this to keep me updated on how the integration of Defensiveturrets is going.

**Comment by BboyZeroOne** [comment]
Alright, I have informed the dev regarding the API wiki and also the 'no events available'. Will keep you updated.

**Comment by booksaw** [comment]
The Defensive Turrets developer is adding the integration on their end.
