### ISSUE TITLE
[BUG] Major server lag/crashes with a large amount of teams

### ISSUE THREAD

**Issue by DeathByAutoscroll** [booksaw/BetterTeams#134]
Written on behalf of YAP on discord.

My server regurally gets between 100-140 players, because of this my server's teams.yml  has a lot of teams, and everytime that file is accessed it lags the server. 

Causes of lag include: Getting information about a team, removing a player from a team, updating a teams score (from player death).

This gets worse and worse with more data added to the teams.yml file.

Original discord message:
hello!
i find  big bug..

my server user online 100 ~140 player

this bug is induce server thread thumping or stoping.

my server
teams.yml file data value is 80kb
in file so many created teams

how to thumping lag?
just two cmmands quickly input
/team info name
/team kick player

its commands quickly typings 
again again

A lag is triggered when loading data.

In addition, the score system loads data when an event occurs in which the player dies, causing a lag

**Comment by booksaw** [comment]
It is important to ensure new saving systems can be implemented in the future. For example MySQL.

TODO: 
- [ ] Code to update old configs to the new saving system 
- [ ] Save manager to make transfer easier to new systems
- [ ] Transfer old system to save manager
- [ ] Ensure loading and saving is all moved to new class

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
