### ISSUE TITLE
War Feature

### ISSUE THREAD

**Issue by Evo-000** [booksaw/BetterTeams#137]
Would be nice to see a cmd that plublicly displays wars, like "/team war <teamname>" which would declare war and "/team war list" which would list wars.
This would add a whole new adventure to your plugin

**Comment by booksaw** [comment]
Copy from the discord server where this was initally mentioned: 
this has been suggested in the past but thus far everyone who has suggested this has failed to answer this question:
what benefits / differences would their be between neutral teams and enemy teams? as currently you can pvp neutral teams. 
If there is no difference there is no point adding a command to declare war / enemy another team as there will be no benifits of doing it
but if there is no encouragement to actually enemy a war people will not feel motivation to enemy it
Also if there are like 100 teams on a server, how would you manage the number of enemies that would exist in the /team war list

**Comment by booksaw** [comment]
This issue is being closed due to lack of response. If you wish to respond to the concerns, please make a new issue and reference this one along with answering all unanswered questions.
