### ISSUE TITLE
[FEATURE] Large chest

### ISSUE THREAD

**Issue by Centralgz** [booksaw/BetterTeams#138]
I started using this plugin awhile, is there a way to make the clan echest larger?

**Comment by megargayu** [comment]
How do you propose you get this "larger" echest? Using points? Or should it be a config specific option? (Or both?)

**Comment by booksaw** [comment]
This issue is being closed due to lack of response, if you see this notification and wish to mention this issue again, please make a new issue referencing this one and answering all the questions,
