### ISSUE TITLE
[Config option to turn off "Team home"]

### ISSUE THREAD

**Issue by Offline-User** [booksaw/BetterTeams#14]
**Is your feature request related to a problem? Please describe.**
I've been looking for a teams plugin that doesn't feature any teleportation commands.

**Describe the solution you'd like**
Addition of a config option to turn off teleportation via the team home command, or a permissions node for it

**Comment by booksaw** [comment]
/team home and /team sethome can already be disabled. 
To do so, all you need to do is remove the permission node from the default group. (they have the permission node by default)
If you are using luckperms, add the permission node and set it to false (i'm not too familiar with other permission plugins, so I don't think I can be of much help. 
To save typing out the permission nodes again check the [wiki permissions page](https://github.com/booksaw/BetterTeams/wiki/Permissions) to find the permission nodes you are looking for.
