### ISSUE TITLE
[FEATURE] Tag, colors, rank and permissions.

### ISSUE THREAD

**Issue by louismesmo** [booksaw/BetterTeams#141]
Would be nice if we could have multiple differences between teams ranks, not just warps and chests. Higher ranks teams could have options like colored tags, or even being able to edit tags. In other words, let us decide which commands the teams can use depending on their ranks. Also, give an option to ban chars from /team tag and /team description.

**Comment by megargayu** [comment]
Please put a seperate feature request for an option to ban chars from /team tag and /team description :)

**Comment by booksaw** [comment]
Team description would require a seperate banned character list, at this point, it is not intended to add this. 

TODO: 
- [ ] Update config.yml to reflect that team tag has banned chars

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
