### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sodagame** [booksaw/BetterTeams#148]
**Describe the bug**
Teams can spam ally teams multiple times so when u do /team ally their team comes up like 7 times or more which can be annoying to find the right team to ally with so it would be nice if every team can only ally one time to the person every 1 min and after 1 min the ally request goes away and a cooldown of doing /team ally but that would be the 1 min thing per team to ally with.

**Expected behaviour**
When u do /team ally it shouldnt come like 7 ally requests from the same team

**Screenshots**
https://imgur.com/a/EF5LjRh

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): purpur latest version
- BetterTeams version (found by running /version BetterTeams):  New version 3.1.26

**Additional context**

**Comment by booksaw** [comment]
This has been fixed and will be included in the next update.
