### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eretna123** [booksaw/BetterTeams#149]
**Describe the bug**
There are a few more problems. The Team Rank command sends an error tree. In the same way, the chest Claim and Chest Remove commands send an error tree. We had to disable them. We ask you to solve them. With our dignity.
this is a team rank error
**To Reproduce**
Steps to reproduce the behaviour:
1. Run command...
2. 

**Expected behaviour**

**Screenshots**
 
[message.txt](https://github.com/booksaw/BetterTeams/files/6566098/message.txt)

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):airplane latest
- BetterTeams version (found by running /version BetterTeams): latest

**Additional context**

**Comment by booksaw** [comment]
/team rank has been fixed for the next update

Could you send the error message for chest claim and chest remove please so I can look into those errors.

**Comment by booksaw** [comment]
This issue is being closed due to inactivity, if you want to respond to the comments and continue this issue, make a new issue referencing this one answering any questions / concerns.
