### ISSUE TITLE
[FEATURE] Automatic permission management for members of higher rank team

### ISSUE THREAD

**Issue by GuazP** [booksaw/BetterTeams#155]
**Is your feature request related to a problem? Please describe.**
I would like to introduce team rewards to motivate players for grouping and collecting money to advance level of their team. 

**Describe the solution you'd like**
Such thing like managable permission for members/owners/admins of teams would allow to create approperiate rewards. 

**Describe alternatives you've considered**
It could be built-in mechanism which allow to collect reward only by specific rank user or once (configurable, maybe twice or so on) by owner (for example) per some period of time, who could give it to member who paid the most or whatever are rules in team.

**Additional context**
Not applies

**Comment by booksaw** [comment]
By permissions you mean permission nodes so those ranks can interact with other plugins right? 
instead of varying what commands a player can run within the team? (ie /team kick)

**Comment by GuazP** [comment]
Yes. I mean allowing interact with other plugins, for example any reward plugin I saw, needs permission for player to grab reward. In this case, when player is in team of level 3 for example, he should have permission batterteams.team.rank.3 (or 1, 2, 3 despite of configuration). This will make it fully compatybile with any reward plugin :)

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
