### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Lucky0888** [booksaw/BetterTeams#157]
**Is your feature request related to a problem? Please describe.**
No it's not, It just to make the plugin better, That's all.

**Describe the solution you'd like**
Can there be a placeholder for the top 10 teams in a list or something like that? For example like if I wanted to put the top 10 teams on a hologram

**Describe alternatives you've considered**
None. I cant find one.

**Additional context**
Nothing.

**Comment by booksaw** [comment]
This can already be done. There is two methods:
1. Use the holgraphic API dependency and use /teama holo create
2. Use the placeholders: https://github.com/booksaw/BetterTeams/wiki/PlaceholderAPI `%betterTeams_teamscore_{rank}%`

**Comment by booksaw** [comment]
Due to lack of further questions, I am closing this issue. If you have any more questions do not hesitate to make a new issue.
