### ISSUE TITLE
[FEATURE] Add /team list Command.

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#16]
**Is your feature request related to a problem? Please describe.**
Feature Request. Add a new command '/team list'

**Describe the solution you'd like**
Team list command will list out all the team in a list of 10. If the player wants to view the next list of team, they could do '/team list 2'. The arrangement of the team is based on the number of members in the team. 

**Describe alternatives you've considered**
None

**Additional context**
Permission: betterteams.list

This should be a default command under 'betterteams.standard'

**Comment by booksaw** [comment]
This feature has been completed.
