### ISSUE TITLE
[FEATURE] toggle claim chests config to decrease consuming resource

### ISSUE THREAD

**Issue by ALiangLiang** [booksaw/BetterTeams#162]
**Is your feature request related to a problem? Please describe.**

If my players builds many machines with many hoppers, the `onHopper` listener will consume resources. But i don't allow my players claim chests.

**Describe the solution you'd like**

Add a config `enableClaimChests: false` to enable/disable claiming chests. If disabled, don't [register ChestManagement](https://github.com/booksaw/BetterTeams/blob/c040bd7fd1298caac5e8a49d1e575cde05c1e887/src/com/booksaw/betterTeams/Main.java#L702) and disable related commands.

**Describe alternatives you've considered**

**Additional context**

**Comment by booksaw** [comment]
You can disable chest claim commands by setting enabled to false under the relevant commands in teampermissions.yml and chestpermissions.yml
are you noticing any performance impact from the onHopper method?

**Comment by ALiangLiang** [comment]
@booksaw not too heavy. Although only a few hoppers will cause apparently resource consumption. Maybe someone can testing for many hoppers.

It's a report from lag monitor. Sampling time is 25.797 seconds.
![image](https://user-images.githubusercontent.com/6974496/122040471-671ed200-ce0a-11eb-8808-83dbdf278d5b.png)

**Comment by booksaw** [comment]
Yeah thats higher than is acceptable, ill make some improvements

**Comment by booksaw** [comment]
Instead of adding a config option, the chest checks will be disabled automatically when the chest command is disabled.

This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
