### ISSUE TITLE
[BUG] Placeholder API teamscore not working

### ISSUE THREAD

**Issue by gellowg** [booksaw/BetterTeams#165]
**Describe the bug**
When using holographic display to display %betterTeams_teamscoreno_{1}% or %betterTeams_teamscore_{1}% it doesn't display the team or score but jus the text of what goes in.

**To Reproduce**
Steps to reproduce the behaviour:
1. Using holographic display, protocollib, betterteams with 2 different teams, and Placeholder API
2. running command /hd addline leaderboard %betterTeams_teamscoreno_{rank}%
3. All other placeholders work, like %betterTeams_name%

**Expected behaviour**
The score or team name from that rank should appear not the actual text

**Screenshots**
![image](https://user-images.githubusercontent.com/47644702/122649360-64332280-d125-11eb-8acb-9e3cc074c369.png)

**Details**
Please provide the following details about your server set-up:
- Spigot version 1.17:
- BetterTeams version 3.1.26:

**Comment by booksaw** [comment]
for placeholder bugs, please demonstrate by using `/papi parse me <placeholder>` showing both the command and result, as that command is provided by placeholderAPI and shows that no other plugins are conflicting
For your problem, remove the { and } but keep the numbers, for example:
`%betterteams_teamscoreno_1%`

**Comment by gellowg** [comment]
Yes, it turned out I just needed to get rid of the curly brace's, thanks
