### ISSUE TITLE
[BUG] invisibility bug

### ISSUE THREAD

**Issue by STEVE1010101** [booksaw/BetterTeams#166]
sometime you can see other player invisibility nametag (different team)
here is how it happen
if invisibility player have team sometime show nametag (also it appear when you join random team)
if invisibility player don't have any team it will stop show nametag (also it disappear when you no longer in any team)

**Comment by booksaw** [comment]
From my understanding of what you are saying: This is how minecraft scoreboard teams operate. 

There would be ways to bypass the issue, but for the time being this is a low priority bug (hence it being marked as "wontfix")

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
