### ISSUE TITLE
[FEATURE] Use variables in messages.yml instead of `%s`

### ISSUE THREAD

**Issue by megargayu** [booksaw/BetterTeams#169]
Right now, we use `%s` to indicate variables in our `messages.yml`. For example:
```yaml
rank.infos: '&6Team rank: &b%s &7(%s score needed for next rankup)'
```
This is extremely annoying to edit, because the `%s` signs have to be in the exact order, and it's hard to see which means which. Instead, I think we should add a variable-like system. For example:
```yaml
rank.infos: '&6Team rank: &b%rank% &7(%score_needed% score needed for next rankup)'
```
This makes it much easier to read and understand. This also has the benefit of adding some more variables, such as `%team%` which gives the team name so you can do something like:
```yaml
rank.infos: '&6%team%'s rank: &b%rank% &7(%score_needed% score needed for next rankup)'
```
We could also have some global variables like `%player_ran%` which returns the username of the player who ran the command.

Updating would be hard, but not impossible. We would have to update users `%s` to variables (such as `%team%`) using some automated code that might run on startup.

**Comment by booksaw** [comment]
Though I like this idea, it would both require a messages.yml reset as updating the 100 or so messages including `%s` in is not reasonable as each message update would have to be custom coded, along with the problems of if them message has been edited.

This also poses some problems with languages, as all the tags will still be in english some people will translate the tag %score_needed% into their language (I know it sounds silly, but similar things have happened in the apst) which would increase the amount of support that I would need to give. 

I just dont see a way this could be a feasible change, however good in the long term it would be

**Comment by megargayu** [comment]
@booksaw Well, for your first point, I thought we could just make a little script that converts all the `%s` into the variable names. However, I see your point about the languages. You could maybe put comments in `messages.yml` telling them about the variable names?

**Comment by booksaw** [comment]
The script would have to figure out what to replace each %s with, there may be a way by loading the internal config.yml and comparing each %s in order within each message to the internal config.
My main concern is having to track down and update every occurrence of all the messages that contain a %s to the new system.

**Comment by EarthCow** [comment]
It might not be exactly what was wanted but to solve this we could use a system similar to GriefPrevention's system. Where instead of all the variables being %s they are {0}, {1}, {2} or $0, $1, $2... This way it would allow for the reordering and removal of the variables. Plus, migrating to this would be much easier than migrating to a textual variable based system.

Ex: `prefixSyntax: '&7[%s&7] &r%s'` -> `prefixSyntax: '&7[{0}&7] &r{1}'`

**Comment by booksaw** [comment]
Yeah I agree this is a good idea, my only issue would be figuring out a script to either support both of automatically migrate existing language files to the new system. As if users have customised their messages.yml file I don't really want to publish a breaking change meaning they have to reconfigure them again.
