### ISSUE TITLE
[FEATURE] Execution Delay on Teleportation Commands

### ISSUE THREAD

**Issue by iavengetheweak** [booksaw/BetterTeams#17]
**Is your feature request related to a problem? Please describe.**
A feature which places a delay of execution on teleportation commands such as /team home.
Ability to set the amount of delay before execution in seconds through the config file
Ability to choose whether to enable an execution delay at all through the config file

**Describe the solution you'd like**
Sequence of events:
Player enters: /team home
Message in chat appears similar to: 'Team home teleportation will commence in 10 seconds.  Don't move."
Server executes the teleportation command for player after 10 seconds.

If player moves before teleportation commences a message in chat appears similar to: 'Pending teleportation request cancelled.'

**Describe alternatives you've considered**
Alternative to a new command add the choice of enabling an execution delay on teleportation through a new command
such as: /teama teledelay {true/false}.
Same concept as above for the delay in seconds before execution of a teleportation command.
Personally, whichever is easier for you to implement is my preference!

**Additional context**
None

**Comment by booksaw** [comment]
I like this idea. As a matter of fact, I have already programmed this into the program and it is waiting for the next release to come out (someone else had already requested it) 
The update will add 2 new config options, 1 to determine how long of a tp delay there is, and a second to determine if the player is allowed to move during the wait time.
