### ISSUE TITLE
[FEATURE] Add team war

### ISSUE THREAD

**Issue by kedavlar** [booksaw/BetterTeams#171]
Hi, it it possible to add a feature where team can have a real battle in specified arena. ex.. /team war ''team name'' and if the other team accept , they can go to 1 of the specied arena for the fight and win  a prize?

**Comment by kedavlar** [comment]
.

**Comment by booksaw** [comment]
Dont worry about bumping it so it is not inactive, I don't close issues that don't have unanswered questions
