### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SarahPMC** [booksaw/BetterTeams#179]
**Describe the bug**
Sometimes, a player can be shown on TAB even he is offline and as a prefix he has the team name instead of his rank. It should never be the team name.

**To Reproduce**
There are no steps, it just happens.

**Expected behaviour**
I hope you could help me to fix it

**Screenshots**
https://imgur.com/a/orQWY2V

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): git-Purpur-1087 (MC: 1.16.5)
- BetterTeams version (found by running /version BetterTeams): 3.1.26

**Additional context**
Forgot to say: the bugged players are always the last on tab even if they should be the first ones
And i didn't update the plugin recently because I didn't see a solution for it in the Update Log

**Comment by booksaw** [comment]
As mentioned in the discord, try setting `useTeams` to false if you are not using their prefxes. Let me know if you are still having problems after you have made that change

**Comment by booksaw** [comment]
Due to the lack of activity, I am assuming this issue has been resolved.
