### ISSUE TITLE
[FEATURE] Compatibility with EpicLevels Plugin

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#18]
**Is your feature request related to a problem? Please describe.**
A feature. Allow BetterTeams to be compatible with EpicLevels.

https://songoda.com/marketplace/product/epiclevels-gain-levels-by-fighting.44

**Describe the solution you'd like**
The level of the Team member would contribute to the score of the team. The higher the pvp level the team member is, the higher the team score in team top.

**Describe alternatives you've considered**
None.

**Additional context**
Documentations
https://wiki.songoda.com/Epic_Levels
https://docs.songoda.com/epic-series/epiclevels

**Comment by booksaw** [comment]
After further research, I have found out that though 'epic levels' is open source, they have not released the full code as the internal dependency 'songoda core' is not included within the source code (I would guess it is to ensure people do not use the plugin without paying).
I will try to reach out to the developers of this plugin to get the full source code.

**Comment by booksaw** [comment]
While looking into how to add this feature. I noticed (assuming I am understanding correctly) that the easiest way to add this feature is to add into the LevelUpRewards.yml file a new command to increase the score of the team. For example 
/teama score add <player/team> <amount>
As then in the config file, you could put under the '-1' category and any categories which have the heading 'OVERRIDE'. something like CMD /teama score add %player% 1 or something. 
If this command was added I would also add
/teama score set <player/team> <amount> 

Would this method of completion work as you are more familiar with the plugin?

**Comment by BboyZeroOne** [comment]
> While looking into how to add this feature. I noticed (assuming I am understanding correctly) that the easiest way to add this feature is to add into the LevelUpRewards.yml file a new command to increase the score of the team. For example
> /teama score add <player/team>
> As then in the config file, you could put under the '-1' category and any categories which have the heading 'OVERRIDE'. something like CMD /teama score add %player% 1.
> If this command was added I would also add
> /teama score set <player/team>
> 
> Would this method of completion work as you are more familiar with the plugin?

Yes! Adding '/teama score <add/remove> <player/team> <amount>' would be a great addition!

**Comment by booksaw** [comment]
TODO list 
- [ ] /teama score set <player/team> <score>
- [ ] /teama score add <player/team> <score>
- [ ] /teama score remove <player/team> <score>

**Comment by booksaw** [comment]
All planned commands have been added and are working as expected
