### ISSUE TITLE
[BUG] team echest

### ISSUE THREAD

**Issue by STEVE1010101** [booksaw/BetterTeams#181]
version 1.16.5
https://www.youtube.com/watch?time_continue=19&v=X4ZMg0HyFQE&feature=emb_title
when you relog team echest will be reset

**Comment by megargayu** [comment]
It seems like this might be a lag issue. Are there any errors/warnings in console? Maybe try closing the echest before relogging?

**Comment by STEVE1010101** [comment]
there is no error no lag
here is my guess
when your own team all offline enderchest won't save it will rollback

**Comment by booksaw** [comment]
It may be a problem with storage in the new update, there seems to be a few problems relating to it

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
