### ISSUE TITLE
[FEATURE] Disable TP option

### ISSUE THREAD

**Issue by pentrait** [booksaw/BetterTeams#183]
**Describe the solution you'd like**
Would it be possible to add a disable team teleport in the config?  Running a hardcore-ish SMP and don't want them to be able to teleport.  We could use permissions, but at the time, our server does not need a permission setup as there is only one admin and no OP's.

**Comment by megargayu** [comment]
Please see the wiki on `teampermissions.yml`: https://github.com/booksaw/BetterTeams/wiki/Team-Permissions

(This is not with any permission manager, it's a simple config file used to disable/enable certain commands).

**Comment by pentrait** [comment]
Oh Ok, Thank you!
