### ISSUE TITLE
[BUG] - An available team cannot be found

### ISSUE THREAD

**Issue by PenguinSlippers** [booksaw/BetterTeams#187]
**Describe the bug**
 An avaliable team cannot be found, be prepared for a lot of errors. (this should never happen, and should always be reported to booksaw)
14.07 16:19:59 [Server] WARN This catch is merely here to stop the server crashing
14.07 16:19:59 [Server] ERROR Could not pass event PlayerJoinEvent to BetterTeams v4.0.1

**Details**
Please provide the following details about your server set-up:
- git-Purpur-1171 
- BetterTeams version 4.1

**Comment by megargayu** [comment]
Some more information, please! You can post your full stack trace on https://mclo.gs/ or https://pastebin.com/, or any other site you wish to use.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
