### ISSUE TITLE
[FEATURE] New Team Warp Command.

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#19]
**Is your feature request related to a problem? Please describe.**
Feature Request. I would like to suggest a new Warp command feature.

**Describe the solution you'd like**
/team warp <warp name> <password>       -    **betterteams.warp**                - Warp to team warp location.
/team setwarp <warp name> <password>   -   **betterteams.setwarp**            - Set team warp location.
/team delwarp <warp name>                        -   **betterteams.delwarp**            - Delete team warp.
/team warp list                                                -  **betterteams.warp.list**            - List all team warps.
                                                                        -  **betterteams.warp.bypass**      - Bypass warp warmup and cost.
/teama warp <team> <warp name>              -  **betterteams.admin.warp**       - Teleport to any team warp location.
/teama delwarp <team> <warp name>         -  **betterteams.admin.warp**        - Delete any team warp.
/teama warp list <team>                                 -  **betterteams.admin.warp**        - List all team warps.

**Description:** To allow Team leader/admin to set an additional team warp for members to teleport to, with an option to set warp password. The _amount/limit of warp a team could create_ and also _warp warmup_ is configurable in the config file. The _cost per warp usage_ is also configurable via the config file.

**Example:** Team leader could set a warp to a farm for team members to teleport to with a warmup of 5 seconds before teleporting to the set warp location.

Config should include:
1. Option to set team warp limit.
2. Option to set team warp creation cost.
3. Option to set team warp teleportation cost.
4. Option to set team warp warmup value.
5. Option to disable warp creation in certain worlds.

**Describe alternatives you've considered**
Player Warps. But its built for players not team based warps.
https://www.spigotmc.org/resources/%E2%AD%90-player-warps-%E2%AD%90-%E2%9E%A2-let-your-players-set-warps-1-8-1-16-1.66692/

**Additional context**
None

**Comment by booksaw** [comment]
I like the ideas, this will be added in then next version.
Teleport warmup will be automatically done by the plugin under the already existing config option along with the relevant bypass. 
Command cost/cooldown works with any /team command automatically (Just so you know for future)

TODO list - for reference during development: 

- [ ] /team warp <name> [password]
- [ ] /team setwarp <name> [password]
- [ ] Limit maxumim warps per team
- [ ] /team delwarp <name> [password] - if the user is the team owner, the password is not required, but for admins it will be
- [ ] config option to enable / disable the use of passwords (as it could just be used for owners to get more /sethomes) 
- [ ] /team warps - view the warp list (this should also appear when running the command /team warp
- [ ] /teama warp <team> <name> (leave name blank to view all avalaible warps
- [ ] /teama setwarp <team> <name> [password] 
- [ ] /teama delwarp <team> <name>

**Comment by booksaw** [comment]
This feature will be released in the next update
