### ISSUE TITLE
[BUG]The lines to set the price of the command "house" do not appear

### ISSUE THREAD

**Issue by zlvicho** [booksaw/BetterTeams#192]
![Captura](https://user-images.githubusercontent.com/87586890/126051112-27cd4e39-0f86-47c6-951b-a7a92b612742.PNG)
When trying to give a price to the command "home" or to any other command of the plugin, it becomes impossible since the lines which fulfill this function in the file "team.yml" do not appear and when trying to replace them and start the server again delete again and the file remains as shown in the photo

**Comment by booksaw** [comment]
What version of betterteams are you using? 
Try stopping the server, deleting the file then restarting the server.

**Comment by booksaw** [comment]
Due to the lack of response, I am assuming this issue has been resolved. If you need further support feel free to make a new issue.
