### ISSUE TITLE
[BUG] cant disable team pvp

### ISSUE THREAD

**Issue by kedavlar** [booksaw/BetterTeams#194]
VERSION: 4.0.2

BUG: sometimes some team cant disable team pvp with the command, it only happend after 4+ version of the plugin, i dont know how to replicate, its random for what a know

**Comment by booksaw** [comment]
This may be unintentionally fixed in the next update, let me know if its not. 
I cant currently reproduce it so im not sure what the error is and until I can there is not much I can do.

**Comment by kedavlar** [comment]
i think the problem is the new storage system with old team crated, i have a lot of error fo this, like this with /team top https://pastebin.com/FLJ35sjd

**Comment by booksaw** [comment]
Alright, let me know if you are still getting the errors in the next update as I think they may have been fixed.

**Comment by kedavlar** [comment]
when is release the next update?

**Comment by kedavlar** [comment]
teh team top is fixed but the teama reload is bugged and it dosent work
