### ISSUE TITLE
[BUG]Team leave doesn't work

### ISSUE THREAD

**Issue by Rerace** [booksaw/BetterTeams#199]
**Describe the bug**
A few people in my server try to leave there team but they can't.
When they try to leave there team they get the following message: an internal error has appeared.
They don't are server operators. 
My server console log also get a big error message.

**To Reproduce**
Steps to reproduce the behaviour:
/team leave

**Expected behaviour**
Leaving the team where they are in.

**Screenshots**
![image](https://user-images.githubusercontent.com/68928098/126677017-4fe97d7d-1100-4740-a5c7-39e4f26635f0.png)
![image](https://user-images.githubusercontent.com/68928098/126677069-6ad270c9-e4ec-4ff0-b2d7-d8c3bf51ed6d.png)

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): 1.17
- BetterTeams version (found by running /version BetterTeams):  4.0.2

**Additional context**
The server log error message https://mclo.gs/M7K73fb

Plugins used: 
![image](https://user-images.githubusercontent.com/68928098/126677276-7012b336-b8b7-4897-a9fa-902c17093df3.png)

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
