### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by zasnaz** [booksaw/BetterTeams#2]
Hey it's a small issue which is I have a plugin called healthbar it displays the mobs or players health above their head and not as a prefix or suffix just a single box over their head. The plugin was okay but after updating betterteams plugin to 3.0.5 version, the healthbar plugin no longer working i don't know why .

**Comment by booksaw** [comment]
This problem has been fixed for version 3.0.7. As shown here:
![example](https://user-images.githubusercontent.com/13976636/84571267-0dfd0800-ad8a-11ea-984e-aa30b715e239.PNG)

This will fix a problem if the health is being displayed below the player name (as shown above). There will still be conflicts if it is changing the nametag prefix or suffix (to my knowledge there is no way to avoid this)
