### ISSUE TITLE
[BUG] reload problem

### ISSUE THREAD

**Issue by dogi-dogi** [booksaw/BetterTeams#202]
I'll tell you the bug I found. v 4.0.3
The cause of those bugs is from the use of the reload or /teama command.
This is for sure.
The message file could not be properly loaded when it was modified and reloaded.
There must be something wrong with reloading.
That doesn't mean there's an error in the bucket.
It's a strange bug.

1. Problems arise from reloading.
2. reloading -> Functions malfunction.
3. In conclusion, there is a bug that all functions of the config are not working properly.

check.
not work list
1. team invite 
2. team kick
3. disableCombat: true 
   not work
   The function should be blocked, but it can attack team members. 
4. team message reloading

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
