### ISSUE TITLE
How about add a not pvp in the config.yml?

### ISSUE THREAD

**Issue by LSSwwwwwww** [booksaw/BetterTeams#203]
I very love your plugin but my server is a minigames server.And when player join the team it cannot PVP in their team,everytime they must use /team pvp to open it.I wonder if you can add a function to add the "Is it PVP in their team：True" to add the config.yml

**Comment by GuazP** [comment]
> I very love your plugin but my server is a minigames server.And when player join the team it cannot PVP in their team,everytime they must use /team pvp to open it.I wonder if you can add a function to add the "Is it PVP in their team：True" to add the config.yml

Hi, I have minigames as well on my serwer along this plugin. Maybe it'll help you as temporary fix until option being added: Add Team-PVP flag in your worldguard (if you use it) to all minigames worlds/regions :)

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
