### ISSUE TITLE
[BUG] Error with team name change and enderchest

### ISSUE THREAD

**Issue by jahua50** [booksaw/BetterTeams#204]
When players change their team name, the teamNameLookup list is not updated (but the yml file in teaminfo folder is updated). This will cause many bugs such as unable to invite people, unable to rank up, etc...

Another bug is item duplication in teams' ender chest.  When team member logs out and logs in again, they seem to be able to retrieve the items twice (or even more times). I did not test this out myself, but I have heard several reports about this bug from the players in my server.

**Comment by booksaw** [comment]
The first bug will be patched for the next update.
Could you give me more details on how to reproduce the /team echest bug please.

**Comment by jahua50** [comment]
I upgraded from the old storage system (before 4.0 version), im using the latest version betterteams and 1.17.1 paper. The process of item replication is:
Take item out of the echest -> disconnect from the server -> log in again immediately ->  the original item is still in the echest (and you can take it out again).
![image](https://user-images.githubusercontent.com/35772634/127028000-bfcd2739-b319-4e48-9d60-3267b608026d.png)
These are items that my player successfully replicated.

**Comment by booksaw** [comment]
I have tried to replicate this about 40 times, including making a macro to disconnect from the server as fast as possible, I am assuming I have unintentionally fixed the bug while working on the update.
Let me know if this issue persists after you update to the version which will release later today

**Comment by booksaw** [comment]
Also have you checked the resulting items are not ghost items?

**Comment by TDMidkwhatisxd** [comment]
yes

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
