### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kennethako** [booksaw/BetterTeams#206]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command...
2. 

**Expected behaviour**

**Screenshots**

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
- BetterTeams version (found by running /version BetterTeams): 

**Additional context**

**Comment by booksaw** [comment]
by the missing body / title I am assuming this issue was not intended to be opened
