### ISSUE TITLE
[FEATURE] when team kick

### ISSUE THREAD

**Issue by dogi-dogi** [booksaw/BetterTeams#210]
Request improvements

When the owner takes a team kick

I would like to have a function that tells the kicker that he was deported for about 20 seconds by title message.

Team betrayal or This is to minimize damage to the user after being deported by the team.

under the guise of alliance
I want to minimize damage to our killing behavior through team deportation.

Users who betray and steal team members' items are often reported.

If I have an idea for a better improvement function, I will ask.
thanks

**Comment by DeathByAutoscroll** [comment]
You can already change the plugin messages in the `messages.yml`, as well as toggle PVP within teams via `config.yml` (disableCombat).

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
