### ISSUE TITLE
[FEATURE] permission-based team limit

### ISSUE THREAD

**Issue by GunacP40** [booksaw/BetterTeams#211]
**Is your feature request related to a problem? Please describe.**
it's not. i'd just like permission-based team limit for vip players

**Describe the solution you'd like**
basically what i said before

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by booksaw** [comment]
Hey, I've started working on this, but I have encountered a couple of problems.
My initial plan was to check the owner's permissions and get the team limit based on the permissions of the owner of the team. but if the owner of the team is offline when someone joins the team, I cannot access the permission nodes for the owner, meaning that my initial strategy would not work.

How do you propose this permission-based team limit works?

**Comment by GunacP40** [comment]
hello, sorry for the late reply i didnt have the time to do it. yes that was exactly what i was thinking about, only allowing the team leader to invite more players therefore they should have the permission. if you cannot access permission nodes for the owner, why don't you just allow the owner to invite players? so players can only be invited when the owner is online and then there is no need to access permission nodes

i'm not sure if thats what you meant..

**Comment by booksaw** [comment]
This feature has been implemented, the plugin will require Vault to be on the server for it to be able to work else it will ignore the config setting to enable this.
