### ISSUE TITLE
[BUG] The prefix team still show , I removed the plugin

### ISSUE THREAD

**Issue by HRNGUYEN111** [booksaw/BetterTeams#213]
I removed the plugin , but the prefix team still show?
![image](https://user-images.githubusercontent.com/88438745/128181068-e4dd9945-d765-4697-a5af-f8655d81892d.png)

**Comment by booksaw** [comment]
What version of the plugin were you using?

**Comment by HRNGUYEN111** [comment]
Sorry, the plugin has no error, I fixed it already. Thank you :3
