### ISSUE TITLE
What version of BetterTeams for Minecraft 1.12.2?

### ISSUE THREAD

**Issue by HRNGUYEN111** [booksaw/BetterTeams#214]
What version of BetterTeams for Minecraft 1.12.2?

**Comment by booksaw** [comment]
latest

**Comment by HRNGUYEN111** [comment]
> latest

What's this error? What can I do now?
![image](https://user-images.githubusercontent.com/88438745/128354838-25d1c49e-f949-4881-a5fe-791cd2492071.png)

**Comment by HRNGUYEN111** [comment]
I'm using 3.1.20, it has no error. how I deny players use the command "/team sethome" in a world? Because my server has warp VIP, if the owner of a team is VIP rank and /sethome at there, members in the team can teleport there.

**Comment by booksaw** [comment]
for how to fix the error check: #173 
To disable commands: 
Option 1 disable the command: View the wiki page explaning how to disable a command: https://github.com/booksaw/BetterTeams/wiki/Team-Permissions
Option 2 with permissions: for example /team name, go to this link: https://github.com/booksaw/BetterTeams/wiki/Permissions find the relevant permission node and set that to false for the permissions group in question. An example of this is shown below

**Comment by HRNGUYEN111** [comment]
> for how to fix the error check: #173
> To disable commands:
> Option 1 disable the command: View the wiki page explaning how to disable a command: https://github.com/booksaw/BetterTeams/wiki/Team-Permissions
> Option 2 with permissions: for example /team name, go to this link: https://github.com/booksaw/BetterTeams/wiki/Permissions find the relevant permission node and set that to false for the permissions group in question. An example of this is shown below

Thank you! Let me try

**Comment by booksaw** [comment]
Due to the inactivity, I am assuming this has been sorted, I am closing this issue, if you need more support feel free to open a new issue.
