### ISSUE TITLE
[BUG] Team ally bug

### ISSUE THREAD

**Issue by thepro113** [booksaw/BetterTeams#216]
**Describe the bug**
/team ally bug
**To Reproduce**
Run command: /team ally

**Expected behavior**
The /team ally help menu

**Screenshots**
An internal error occurred while attempting to perform this command.
https://hastebin.com/rolabuduja.apache

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): PaperMC 1.17.1
- BetterTeams version (found by running /version BetterTeams): 4.0.4 

**Additional context**

**Comment by booksaw** [comment]
I cannot reproduce the bug, (when I run `/team ally` the expected messages show up), and the provided error message is not loading.
With most code storage websites, I believe hastebin deletes pastes after a duration of time, to save this problem could you paste the error message in a comment using code tags (``` on either side of the error message)
