### ISSUE TITLE
A placeholder for allied teams

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [booksaw/BetterTeams#218]
It would be nice to be able to add a placeholder to see what who is allied with what teams, to display :)

**Comment by booksaw** [comment]
How would this be formatted if you had more than one ally?

**Comment by ItLucifer-MRPG** [comment]
I imagine it as either a list going down, or listed with a comma in between the names

**Comment by booksaw** [comment]
so like this? 
`team1, team2, team3, team4`?
