### ISSUE TITLE
STILL RAGGING LOADING DATA

### ISSUE THREAD

**Issue by dogi-dogi** [booksaw/BetterTeams#220]
1.12.2
team v4.0.5

i was told you

command
/team info name

When I searched for a team name with about 20 members,
The server tps is lowered.
I changed the data storage format, but it still lags when I load the data.

**Comment by booksaw** [comment]
Hey, could you send a youtube link showing the lag.

I have tested using the new storage system on a test server with 98 teams and 397 players which are in teams, and there is no lag.

**Comment by booksaw** [comment]
due to lack of response I am closing this issue.
