### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by JManuelHeredia** [booksaw/BetterTeams#222]
**Language the issue is about**
es_mx

**Details about request**
New language support. Rename to .yml | Warn: file type not sopported by GitHub at upload time.

**Discord name** 

**File**
[es_mx.txt](https://github.com/booksaw/BetterTeams/files/7071125/es_mx.txt)

**Comment by booksaw** [comment]
Hi, thanks for the translation it will be included in the next update.
If you are interested in getting the translator role in the discord server (https://discord.gg/JF9DNs3) just message booksaw on discord saying you helped with translations.
