### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pentrait** [booksaw/BetterTeams#226]
**Describe the bug**
Splash harming potions do not effect players until disablePotions:false

**To Reproduce**
Steps to reproduce the behaviour:
1. Thrown splash harming potions do not effect players
2. 

**Expected behaviour**
Splash harming potions should effect enemy players and not friendly players.

**Screenshots**

**Details**
Please provide the following details about your server set-up:
- Paper 1.17.1
- BetterTeams version (found by running /version BetterTeams): 4.1.0 

**Additional context**

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
