### ISSUE TITLE
[FEATURE] More Placeholders 

### ISSUE THREAD

**Issue by ParrotRacer** [booksaw/BetterTeams#227]
**Is your feature request related to a problem? Please describe.**
I would like to have more placeholders added so then you can decorate your leader boards easier and with more colour

**Describe the solution you'd like**
Currently, the placeholders of **%betterTeams_teamscore_{rank}%** and **%betterTeams_teamscoreno_{rank}%** I would suggest this as the full list of placeholders:

**For your team they would be:**

%betterTeams_myID% - Your Team's ID
%betterTeams_mytag% - Your Team's Tag
%betterTeams_mydisplayname% - Your Team's Displayname
%betterTeams_mydescription% - Your Team's Description
%betterTeams_myopen% - Whether or not your team is open or invite-only
%betterTeams_myscore% - Your Team's Score
%betterTeams_mybalance% - Your Team's Balance
%betterTeams_myrank% - Your Rank In Your Team
%betterTeams_mycolour% - Your Team's Colour

**For a leaderboard/positioning they would be:**

%betterTeams_position_ID_{rank}% - The ID of the team in the position listed in {rank}
%betterTeams_position_score_{rank}% - The score of the team in the position listed in {rank}
%betterTeams_position_tag_{rank}% - The tag of the team in the position listed in {rank}
%betterTeams_position_displayname_{rank}% - The displayname of the team in the position listed in {rank}
%betterTeams_position_description_{rank}% - The description of the team in the position listed in {rank}
%betterTeams_position_open_{rank}% - Whether or not the team in that rank is open or not
%betterTeams_position_balance_{rank}% - The balance of the team in the position listed in {rank}
%betterTeams_position_colour_{rank}% - The colour of the team in the position listed in {rank}

**Describe alternatives you've considered**
It may also be worth considering placeholders for variables for individual teams such as
%betterTeams_score_{ID}% which would display the score of the team with that ID.

**Comment by booksaw** [comment]
> %betterTeams_myID% - Your Team's ID
> %betterTeams_mytag% - Your Team's Tag
> %betterTeams_mydisplayname% - Your Team's Displayname
> %betterTeams_mydescription% - Your Team's Description
> %betterTeams_myopen% - Whether or not your team is open or invite-only
> %betterTeams_myscore% - Your Team's Score
> %betterTeams_mybalance% - Your Team's Balance
> %betterTeams_myrank% - Your Rank In Your Team
> %betterTeams_mycolour% - Your Team's Colour

The existing placeholders will not be reformatted to this as this would cause problems for other servers, forcing them to update their placeholders

> **For a leaderboard/positioning they would be:**
> 
> %betterTeams_position_ID_{rank}% - The ID of the team in the position listed in {rank}
> %betterTeams_position_score_{rank}% - The score of the team in the position listed in {rank}

Same as above, placeholders to do this already exist. Though adding these would make sense (and hiding the pre existing placeholders though not removing them) would be a good idea to maintain formatting.

> %betterTeams_position_tag_{rank}% - The tag of the team in the position listed in {rank}
> %betterTeams_position_displayname_{rank}% - The displayname of the team in the position listed in {rank}
> %betterTeams_position_description_{rank}% - The description of the team in the position listed in {rank}
> %betterTeams_position_open_{rank}% - Whether or not the team in that rank is open or not
> %betterTeams_position_balance_{rank}% - The balance of the team in the position listed in {rank}
> %betterTeams_position_colour_{rank}% - The colour of the team in the position listed in {rank}

these are good ideas

> **Describe alternatives you've considered**
> It may also be worth considering placeholders for variables for individual teams such as
> %betterTeams_score_{ID}% which would display the score of the team with that ID.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
