### ISSUE TITLE
Players Can Join Teams After Leaving/Being Kicked Without New Invite [BUG]

### ISSUE THREAD

**Issue by iavengetheweak** [booksaw/BetterTeams#23]
**Describe the bug**
A player receives an invite to join a team and joins that team.  The player then leaves the team or is kicked from the team.  The player can still join the team after leaving without needing to receive a new invite.

**To Reproduce**
Steps to reproduce the behaviour: 
1. Player 1 invites Player 2 /team invite *player*
2. Player 2 joins team /team join *team*
3. Player 2 leaves the team /team leave *team*  OR      Player 1 kicks Player 2 from team /team kick *player*
4. Player 2 rejoins team /team join *team*  -- Did not receive a new invite, but still was able to join the team

**Expected behaviour**
When a player leaves or is kicked from a team they should not be able to rejoin that same team without receiving a new invite to that team.

**Screenshots**
![Better-Teams-Team-Join-Bug-01](https://user-images.githubusercontent.com/46011905/88753982-29965500-d123-11ea-91f6-f2e676fcbc5d.png)
![Better-Teams-Team-Join-Bug-02](https://user-images.githubusercontent.com/46011905/88753939-1edbc000-d123-11ea-8742-111e0fb8e857.png)

**Details**
Please provide the following details about your server set-up:
- Paper 1.16.1 #123
- BetterTeams 3.1.2

**Additional context**
No new context

**Comment by booksaw** [comment]
This will be fixed for the next update.

**Comment by booksaw** [comment]
This bug has been fixed for the next update
