### ISSUE TITLE
[FEATURE] Add Password to join team or Only let team owner add members to the team

### ISSUE THREAD

**Issue by davigamer987** [booksaw/BetterTeams#232]
**Is your feature request related to a problem? Please describe.**
Anyone can join any team and spy :(

**Describe the solution you'd like**
Only Team owners will be able to invite players to the team (Toggle option in config.yml) Or add a password to join the team

**Describe alternatives you've considered**
Idk

**Additional context**
?

**Comment by booksaw** [comment]
You can toggle if a team is invite-only or open to everyone using the command /team open. 
You can change the permissions of what rank a player must be to invite other players in teampermissions.yml
![image](https://user-images.githubusercontent.com/13976636/133894464-bd6daa4c-dc2d-4103-914a-969da353cd5f.png)
check the section shown above.

If you have any other questions, let me know

**Comment by davigamer987** [comment]
Thanks
