### ISSUE TITLE
[Feature] Add default /team pvp state to config

### ISSUE THREAD

**Issue by Aadi-mone** [booksaw/BetterTeams#235]
/team pvp 
got vanished, I asked how to make the PVP allowed as default, if /team pvp is removed then why disable combat in the config?

**Comment by DeathByAutoscroll** [comment]
It may help if you joined the official help discord server rather than creating tons of issues (https://discord.gg/JF9DNs3).

Check the plugin permissions, as well as `enabledCommands.yml`

**Comment by Aadi-mone** [comment]
ok let me check

**Comment by Aadi-mone** [comment]
there is no file named enabledCommands.yml 
in the current stable version

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
