### ISSUE TITLE
[BUG] team prefix tag disable 

### ISSUE THREAD

**Issue by dogi-dogi** [booksaw/BetterTeams#237]
can't see the prefix tag of my team member.

Other team members can see it well.

The team I belong to team tag Disappeared.

**Comment by dogi-dogi** [comment]
> 서버를 다시 시작하고 문제가 해결되는지 확인하십시오.
> 
> 팀에 없는 플레이어가 팀원의 태그를 볼 수 있나요?

Unlike the previous version, it is not updated immediately.
The tag on the head should be updated immediately, but it's not.

config set
prefix: true

**Comment by booksaw** [comment]
What version of betterteams are you using? 
What is the plugin you use for your scoreboard? 
Do you have a tab plugin?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
