### ISSUE TITLE
DisablePerWorld

### ISSUE THREAD

**Issue by Cer66** [booksaw/BetterTeams#238]
Hello, I have a feature request...
I made an event, in an event world. Players in the event world are in creative. I disabled every command to Transfer items between worlds like /gift, /ec, /backpack, /shop, /ah etc..... using Worldguard. I also disabled the whole team commands for that world. However players were able to use /team echest and took items over the event to the Survivalworld. I had to completely remove the team echest permission until the event ends, wich is not an optimal solution.

I'd suggest a DisabledInWorlds setting for all team commands in the config.yml.

Thank you! :)

**Comment by booksaw** [comment]
I'm not totally sure how this would work in the code base but I'll look into it when I have time. 

Were other /team commands disabled, or did worldgaurd not work as expected.

**Comment by Cer66** [comment]
I disabled just the command /team, but every betterTeams command worked just fine, even the /team command (that shows the help page). Also typing in worldguard
/rg flag __global__ -w event_world block-cmds team,team echest
Didn't work (should disbale both the /team and /team echest commands) but players were still able to use it.

Thank you for trying it!

**Comment by booksaw** [comment]
thats really bizarre, the code to reach the echest command is the exact same as the code to reach any other command

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
