### ISSUE TITLE
[BUG] Team still "exists" after disband

### ISSUE THREAD

**Issue by FelixDaemonWox** [booksaw/BetterTeams#241]
whenever a team has been disbanded, the team kind of still exist within the pluggin.
doing /team disband, does not eliminate the team completetly.

after a disband, if you try to create a new team with the name of the disbanded team, it will show the error: "that team already exists", however if then you try to do /team join with the disbanded team that "already exists" then it will sow the error "that team does not exist try /team create <name>", essentialy softlocking that name as you cant create a team with that name anymore, and theres no way to delete the bugged team.

the disbanded team does not appear on the teams list nor in the TeamInfo folder but it appears in the teams.yml file

Steps to reproduce:
1. create a new clan
2. disband the clan 
3. try to create a new clan with the same name of the disbanded one

**Comment by FelixDaemonWox** [comment]
> What version of betterteams are you using (/version betterteams)

my version is 4.1.3

also same thing with the teams.yml reloading, athough I think that works as intended as the file explicitly tells you to not touch it

**Comment by booksaw** [comment]
I am not able to reproduce this bug on the development version of betterteams, teams are disbanded correctly for me.
Try setting `rebuildLookups` to true in config.yml and restarting the server, this will recreate the entire teams.yml file from scratch to ensure there are no problems with it.

| Also, trying to delete any info from the teams.yml does not work
yeah, you cant modify teams.yml manually, running rebuildLookups as described above will 

I am going to leave this issue open until it becomes inactive, if either of you are still having difficulties after updating to the version which will be released soon, let me know here and ill fix it as quickly as possible.

**Comment by FetFingers** [comment]
[image: image.png]
So, same happened and didn't work.
Changed the value to True and I was able to create the team with the same
name.
Disbanded it and try to create again and had the same issue

[image: image.png]

James McNair ***@***.***> escreveu no dia sábado, 9/10/2021
à(s) 17:55:

**Comment by FelixDaemonWox** [comment]
version 4.1.4
setting rebuildLookups  to true did fix it temporarily.

but the "bug" persisted after, it still says that a disbanded team still exist.

but after testing in another new vanilla server w/o pluggins. found out it does work.
so most likely its not a bug but a conflict with other pluggin, although because of the huge number of pluggins in my mai server, i can't say wich one is conflicting.

maybe a command ingame that reloads the lookups or reloading the lookups with the /team disband?

anyway, thanks a lot for the help :D

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
