### ISSUE TITLE
[FEATURE] Teleporting Teams Support / Feature

### ISSUE THREAD

**Issue by ParrotRacer** [booksaw/BetterTeams#242]
**My feature request:**
I suggest adding a command such as /teama teleport [Name] X Y Z [YAW] [PITCH] which would enable admins to teleport an entire team to a direction and direction facing.

**Alternatives**
Adding support with the vanilla way which is /tp @a[team=Red] X Y Z [YAW] [PITCH]

**Additional context**
I was creating a hunger games game on my server for a mini tournament and was trying to create starting pods however I found it wasn't possible with the vanilla way as the plugin over rides it therefore I had to use player usernames to certain coordinates instead

**Comment by booksaw** [comment]
You should be able to use the team classifiers to some degree, it may be a bit buggy but if it is let me know.

If you have `useTeams` set to true in the config.yml each betterTeams team will have a scoreboard team. It will be called something a little strange like in the example of 'Red' it will be Red01 or something, 
use `/minecraft:team list' or something like that to view a list of all scoreboard teams, you can go from there. 

the teleport idea seems like a good idea though.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
