### ISSUE TITLE
[FEATURE] Setting to allow user to own multiple teams

### ISSUE THREAD

**Issue by srnyx** [booksaw/BetterTeams#251]
**Is your feature request related to a problem? Please describe.**
I can only create 1 team when I need to create 2

**Describe the solution you'd like**
A way to create multiple teams

**Describe alternatives you've considered**
* Not using Better Teams (would have to get a custom plugin made)
* Using an alt (alt is used by someone else and would have to use the alt whenever I wanted to edit the team)
* Editing the files (might break)

**Comment by booksaw** [comment]
This is already possible, do /teama create <name> 
you then have to use admin commands to manage the team ie /teama invite <team> <player> 
you can view all commands on the wiki: https://github.com/booksaw/BetterTeams/wiki/Commands
