### ISSUE TITLE
MySQL System

### ISSUE THREAD

**Issue by srrawr11** [booksaw/BetterTeams#255]
I would like to request that if it possible to put the mysql system and for example if I created a TEAM in the gamemode SURVIVAL called [GG] so I can have the same TEAM in the gamemode SKYBLOCK, I do not know how to explain, like put it GLOBAL.

**Comment by booksaw** [comment]
It is intended for SQL support to be added in the future.

Allowing players to be in a different team in every world has been requested before. I am not going to implement it as an idea as the plugin is not designed for that to be possible, so the entire backend would have to be remade, along with this the idea poses several design flaws.
