### ISSUE TITLE
Per world teams

### ISSUE THREAD

**Issue by MadEngineerGH** [booksaw/BetterTeams#259]
Hello! I am looking for per world teams? A feature that you can customize by selecting which worlds better teams is disabled in or which teams has the same combined world. im not sure if this is too complex but it would be a pretty cool feature.
Ex: In an anarchy world a team would be "RedRaiders"
But in the survival world you can join say "The_country_of_france"

**Comment by booksaw** [comment]
This change has been requested in the past. 
I am going to reject this feature request for a couple of reasons, firstly the codebase is not designed to allow changes like this to happen. Along with this it is very possible for a system like this to lead to confusion of users and all together a bad user experience.
