### ISSUE TITLE
[FEATURE] Disable update check

### ISSUE THREAD

**Issue by Strahilchu** [booksaw/BetterTeams#260]
No way to disable update check

Would like config option

**Comment by booksaw** [comment]
May I ask your reason for intentionally not updating?

**Comment by Strahilchu** [comment]
> May I ask your reason for intentionally not updating?

I do update it I just like to do it on my own terms and do not like for plugins to automatically run update checks

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
