### ISSUE TITLE
[BUG] Name of the existing team

### ISSUE THREAD

**Issue by PJGamerr** [booksaw/BetterTeams#262]
When I create a team and disband it, it doesn't make me recreate a team with the same name..

**Comment by booksaw** [comment]
Hey, I've tried to reproduce this without success. Could you set rebuildLookups to true in config.yml and restart your server and test it again and let me know of the result.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
