### ISSUE TITLE
MY TEAM MEMBERS CAN KILL EACH OTHER EVEN AFTER DEV SUPPORT

### ISSUE THREAD

**Issue by WindupYT** [booksaw/BetterTeams#267]
**Describe the bug**
i can kill everyone
even my team members
i want pvp disabled when trying to hit other team members. the dev helped me do everything, yet nothing is working, so he told me to make a bug report.

**To Reproduce**
Steps to reproduce the behaviour:
idk what this means

**Expected behaviour**
I expected my team not to hit each other, only other teams, but its broken.

**Screenshots**
no screenshots needed

**Details**
Please provide the following details about your server set-up:
- This server is running Airplane version git-Airplane-103 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 86fee6b on HEAD)
You are on the latest version!
- BetterTeams version (found by running /version BetterTeams): 4.2.0

**Additional context**
no

**Comment by Aadi-mone** [comment]
**Hey, I think you can disable PVP in the config.**
```yml
disableCombat: true
```

**or you can say the team leaders to do:**
```yml
/team pvp
```
**to toggle PVP off or on.**

**Comment by booksaw** [comment]
that does not work, already been through that on the discord server

**Comment by WindupYT** [comment]
Please help?

**Comment by booksaw** [comment]
I've just tested on my test server: 
![image](https://user-images.githubusercontent.com/13976636/141640481-2c4c02b5-7ad6-4a27-a8bd-e4960647d28b.png)
With disableCombat set to true I cannot hit teammates but I can damage and kill members of other teams which are not allied.
![image](https://user-images.githubusercontent.com/13976636/141640955-a50482ca-5565-414a-a4f9-9f94279cc449.png)
Could you share your config.yml please

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
