### ISSUE TITLE
[FEATURE] Allow a team to be teleported to another player

### ISSUE THREAD

**Issue by srnyx** [booksaw/BetterTeams#269]
Allow teams to be teleported to another player.
*Don't really **need** this, so you can make this your lowest priority.*

**Comment by Aadi-mone** [comment]
how about adding a command like:
```yml 
/team list and 
```
```yml
/team visit (team name)
```
which will redirect to their team home?
but that will be not that private for other teams? 
so we can add another command like:
```yml
/team acceptvist (player name)
```
I think that is a nice one? Do you like it? 

and thank you for your response

**Greetings,
~ Adarsh A**

**Comment by Aadi-mone** [comment]
how about adding a command like:
```yml
/team visit (team name)
```
which will redirect to their team home?
but that will be not that private for other teams? 
so we can add another command like:
```yml
/team acceptvist (player name)
```
I think that is a nice one? Do you like it? 

and thank you for your response

**Greetings,
~ Adarsh A**

**Comment by Aadi-mone** [comment]
how about adding a command like:
```yml
/team visit (team name)
```
which will redirect to their team home?
but that will be not that private for other teams? 
so we can add another command like:
```yml
/team acceptvist (player name)
```
I think that is a nice one? Do you like it? 


**Greetings,
~ Adarsh A**

**Comment by srnyx** [comment]
> how about adding a command like:
> 
> ```yaml
> /team visit (team name)
> ```
> 
> which will redirect to their team home? but that will be not that private for other teams? so we can add another command like:
> 
> ```yaml
> /team acceptvist (player name)
> ```
> 
> I think that is a nice one? Do you like it?
> 
> **Greetings, ~ Adarsh A**

I'd rather have something admins can use like `/teama teleport <teambeingteleported> <teambeingteleportedto>` and `/teama teleport <teambeingteleported> <playerbeingteleported>`

**Comment by srnyx** [comment]
Wait, just realized the team > team thing makes no sense. So only player one.
