### ISSUE TITLE
Enovys feature request

### ISSUE THREAD

**Issue by JackCrispy** [booksaw/BetterTeams#27]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The enovys plugin: https://www.spigotmc.org/resources/crazy-envoy.32870/ to be linked into BetterTeams so teams can gain score by opening envoys, and maybe more score for better envoy boxes.

**Describe alternatives you've considered**
N/A

**Additional context**
Plugin Link: [Here](https://www.spigotmc.org/resources/crazy-envoy.32870/)

**Comment by booksaw** [comment]
I've had a quick check of the plugin and if the code works as it claims to this should be possible and will be attempted for the next update.

**Comment by booksaw** [comment]
I've done a bit more research into this plugin, it appears you can specify commands to run when envoys are opened (in the ways of prizes), you can use `/teama score add %Player% <amount> ` as an envoy prize command (I would suggest testing that command individually to make sure you have the syntax correct before including it with the plugin. 

If my understanding of the plugin is incorrect, reply and explain why this is not a possibility.
