### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sarahhubmc** [booksaw/BetterTeams#272]
**Describe the bug**
When  have team chat enabled and I want to write on public chat I put "!" in front of the message, but when I do it the message has the exclamation sign visible and a few months ago it wasn't there.

**To Reproduce**
Steps to reproduce the behaviour:
1. /team chat
2. !message
3. The message has "!" in front of it

**Expected behaviour**
To be a normal message, without !, like it used to be

**Screenshots**
https://prnt.sc/1zkuby8

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): git-Purpur-1159 (MC: 1.16.5)
- BetterTeams version (found by running /version BetterTeams): 4.2.1

**Additional context**
ASAP please

**Comment by Aadi-mone** [comment]
if you have a chat manager or any other chat plugin, try removing it and see :)

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
