### ISSUE TITLE
THERE ARE NO FLAGS FOR ENABLING BETTERTEAMS WHEN THERE SHOULD BE IN WORLDGUARD

### ISSUE THREAD

**Issue by WindupYT** [booksaw/BetterTeams#273]
**Describe the bug**
THERE ARE NO FLAGS FOR ENABLING BETTERTEAMS WHEN THERE SHOULD BE IN WORLDGUARD, I want to enable betterteams in a certain region.

**To Reproduce**
dunno what this means

**Expected behaviour**
I expected the worldguard teamPvp for better teams to work, i want it disabled in rtpspawn, i used the command /rg flag -w "world" rtpspawn teamPvp deny to set it, but nothing happened.

**Screenshots**
not needed as nothing happened

**Details**
[20:11:56 INFO]: This server is running Airplane version git-Airplane-103 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 86fee6b on HEAD)
[20:12:06 INFO]: BetterTeams version 4.2.0

**Additional context**
not needed i dont think

**Comment by booksaw** [comment]
What version of worldgaurd are you using?

**Comment by srnyx** [comment]
> What version of worldgaurd are you using?

Better Teams doesn't like WorldGuard 7.0.6+1cff55f (I think it's just labeled v7.0.6 on Bukkit):
`[01:18:20 WARN]: [BetterTeams] Your version of worldgaurd is not yet supported, the betterteams flags will not be usable`
Thought it was normal and just had to wait for it to be supported

**Comment by booksaw** [comment]
Version 7 of worldguard should be supported. I've checked in the code and there is a bug causing the version to not be supported. Currently, version 7 of worldgaurd is the only supported version.
The bug will be fixed and included in the next update
