### ISSUE TITLE
[BUG] Teams are still there after uninstalling plugin

### ISSUE THREAD

**Issue by PappoYT** [booksaw/BetterTeams#274]
**Describe the bug**
The teams are still there but I've uninstalled the plugin.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install plugin
2. Setup teams
3. Uninstall pluing
4. Restart server

**Expected behaviour**
Teams shoul have been cleared.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/74958346/142065089-f6c82ba7-2a0e-4749-9caf-58b707628b16.png)

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
This server is running Paper version git-Paper-381 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: db0bff9)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-788 (MC: 1.16.5)
- BetterTeams version (found by running /version BetterTeams): 
BetterTeams-4.1.4

**Additional context**
If I use command /team list I get no output.

**Comment by Aadi-mone** [comment]
how do you confirm that better teams are still there?

**Comment by PappoYT** [comment]
If you look at the attached picture you can see the red word "Bot" near the third player.
That is a team made wit BetterTeam when the plugin was installed.

**Comment by Aadi-mone** [comment]
well, we can't say by looking that.
there might be 2 reasons:
1 You didn't remove BetterTeams properly
2 or another plugin might be interfering it!

check once more, or make a back-up and try removing the plugins one by one to see which one causing the issue!

**Comment by dogi-dogi** [comment]
I went through the same thing.
Occurs when the team is deleted and re-created with the same name.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
