### ISSUE TITLE
[BUG] /team command doesnt work on default permission account

### ISSUE THREAD

**Issue by SebastianSoftware** [booksaw/BetterTeams#277]
**Describe the bug**
If I run the /team command (or any team command) in a default user (with default permissions), it says that the command doesnt exist

**To Reproduce**
Steps to reproduce the behaviour:
1. Login with a default permission account
2. Run command /team

**Expected behaviour**
Shows the team commands

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): Purpur 1.16.5
- BetterTeams version (found by running /version BetterTeams): latest (4.2.1)

**Comment by booksaw** [comment]
try giving your default users 'betterteams.standard'

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
