### ISSUE TITLE
[FEATURE] Chest and Plot Claiming

### ISSUE THREAD

**Issue by jackgraddon** [booksaw/BetterTeams#28]
**My Idea**
A feature for claiming chests and plots in Better Teams would be great. That way it can easily integrate with the teams you have already created, and you wouldn't need an extra plugin or two running down your RAM.

**Team Chests**
It could simply be `/team chest claim` while standing on the top of a chest, a double chest, possibly even furnaces, smokers, etc.
Now, one might say, "That could cause many issues because teams could claim other team's chests if they haven't claimed them yet, or don't know how to!" This is a valid claim, because I too worry about that when looking at other plugins, and trust me I have looked through many a plugin. Luckily, this has a simple answer in the config file. Something like `max-claimed-chest: '5'` can create a limit to how many chests each team can claim. Of course, they can still claim only one chest in their base, and four in others, but that is on the server to deal with, as it won't be as frequent of an issue compared to unlimited chest claims.

**Team plots**
The command could look like `/team plot claim x1 z1 x2 z2`, or `/team plot claim` and have the plugin respond with `Select your starting position` where you would stand on your coordinate, type `/team plot start`, and then the plugin would ask you to move to your ending position where you can type `/team plot end`. Again, "Can't you just create a plot that covers the whole map, or over other team's bases?" Why of course you *could*, but you could also limit this by adding yet one more line in the config that would look something like `max-plot-size: '50 50'` where the '50 50' is length x width, or you can use area if that is more convenient by saying `max-plot-area: '2500'`. You can also if you need more than one claim have a `max-plot-count: '3'`, for example. 

**Other Details**
- If you have Vault, you can create a cost for claiming chests or land. `plot-cost: '100'`, `plot-cost-per-block: '5'`, 'chest-cost: '5'`.
- If you have World Guard, you could let teams integrate with World Guard protections, such as `interact` and `use` to limit the things other teams can do inside of the claimed area.

*If anyone reading has anything they would like to add on, comment it!*

**Comment by booksaw** [comment]
**Team chests** look good - Reminders to self: 

- Will have to work with world guard in some capacity to stop players claiming chests in certain regions
- Need admin commands to remove and check claims 
- Need a way to remove self claims 
- Admins+ can only claim chests
- Non processor-intensive way of checking chests to do not go missing

**Team plots**
- Probably simpler and less buggy to find another plugin and integrate with betterTeams, will look for one at some other point

**Comment by booksaw** [comment]
World guard with anti chests 

Notes to self:
TODO:
**Team Chests**
- [ ] Chest claim command
- [ ] Chest remove command
- [ ] Command to unclaim all
- [ ] Admin chest claim command
- [ ] Admin chest remove command
- [ ] Admin unclaim command
- [ ] Chests cannot be opened by opposing team members
- [ ] Hoppers cannot be placed under chets claimed by other teams
- [ ] Config option so allys' can open chests or not

**Team plots**
@jackgraddon Do you know of any appropriate land claim plugins? as adding support would be much simpler than creating it from scratch

**Comment by booksaw** [comment]
**Team Chests**
Completed and included within the update being released in version 3.1.7

**Comment by booksaw** [comment]
Issue is being closed until further information is provided.
