### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Sarahhubmc** [booksaw/BetterTeams#280]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Team top different requirements

**Describe alternatives you've considered**
I would like the /team top to be based on more aspects, like baltop, kills and mobs killed. It would be nice if this top made a statistic with these 3 things.

**Additional context**
none

**Comment by Aadi-mone** [comment]
well, the `/team top` represents the team PVP status, and the `/team baltop` represents topp-est team in the economy!
and well take a look on the commands wiki:
https://github.com/booksaw/BetterTeams/wiki/Commands

Greetings,
~ Adarsh

**Comment by booksaw** [comment]
As mentioned a command exists for baltop
How would you propose the rankings of this new leaderboard are calculated?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
