### ISSUE TITLE
[BUG] tag

### ISSUE THREAD

**Issue by dogi-dogi** [booksaw/BetterTeams#281]
ver 4.2.1

Bug that occurs to the person who joined the team.

no overhead team name tag when player sign up.
The overhead tag is not working.
reconnect to the server to get a tag 
or
the reload command to get the overhead tag.

**Comment by booksaw** [comment]
This is caused by conflicts with other plugins, not just betterteams by itself. What is your scoreboard manager plugin?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
