### ISSUE TITLE
[BUG] /setowner does not work

### ISSUE THREAD

**Issue by Galaxysearcher10** [booksaw/BetterTeams#282]
**Describe the bug**
/setowner and /enablesingleowner do not work or even show up when I use the commands.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command... /teama set
2. /teama setowner does not show up, only setrank/setwarp

**Expected behaviour**
The setowner permission to allow me to assign different players to their respective team leader's post.

**Screenshots**
n/a

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): paper/spiggot on aternos
- BetterTeams version (found by running /version BetterTeams): 4.2.1

**Additional context**
N/a

**Comment by booksaw** [comment]
`/teama setowner` and `/team setowner` are only enabled commands when the setting `singleOwner` is true in config.yml. Is this the case on your server? If so this is a bug.
If singleOwner is not set to true, you can use `/teama promote` and `/teama demote` to change who is owner of a team.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
