### ISSUE TITLE
[FEATURE] still lag

### ISSUE THREAD

**Issue by dogi-dogi** [booksaw/BetterTeams#284]
ver 4.2.1

- [ ] [](url)
![431sa](https://user-images.githubusercontent.com/86357529/143234551-79a57893-acfd-47a6-9991-c164c143d66e.PNG)

**Comment by dogi-dogi** [comment]
thank you. I'm waiting.

**Comment by booksaw** [comment]
If this is not fixed by the SQL changes that are going to be released in the next couple of days, please make a new bug report with your current timings.
