### ISSUE TITLE
[BUG] OFFLINE PLAYER NOT KICK TEAM

### ISSUE THREAD

**Issue by giantfurkii** [booksaw/BetterTeams#288]
**Describe the bug**
Although the player is in the team, he is not thrown out.
**To Reproduce**
Steps to reproduce the behaviour:
1. Run command...
2. 

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/78488589/144430965-f6eca836-2fb3-409d-b351-10c1de7769a0.png)

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
- BetterTeams version (found by running /version BetterTeams): 

**Additional context**

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
