### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Davidlazy** [booksaw/BetterTeams#29]
Once per week / once per day (depends on config setting) players from team A would be able to open teams B chests.
this feature can be set for X ammount of minutes/hours (again depends on config setting)

This could incerase player activity on some pvp servers at specified hour.

Last example - 8PM - (server runs a command) (Pluggin trigger the "feature"). Every team member defending their stuff or attacking other teams to get stuff

9PM - (server command possibility) (Plugin untrigger the "feature") and the chests get claim protection again.

If you dont understand my poor english ask me again on discord LazyAlpha#7878

**Comment by booksaw** [comment]
After some research, their area already command scheduling plugins around, so I will develop the commands required and you can configure a command scheduling.

Personal TODO list: 
- [ ] Command to enable / disable chest claims
- [ ] Notify all users when the command is run 
- [ ] Notify users when they log in if the command is active.

**Comment by booksaw** [comment]
The feature has been implemented as shown below. 

/teama chest enableclaims - Used to reenable claimed chests
/teama chest disableclaims - Used to disable all claimed chests for a period of time
Chest claim will auto be enabled if the server restarts.
