### ISSUE TITLE
Placeholder that will return true/false if player is in team (or he is owner for both things)

### ISSUE THREAD

**Issue by Gladnii** [booksaw/BetterTeams#290]
**Is your feature request related to a problem? Please describe.**
No, not really

**Describe the solution you'd like**
Placeholder that will return if you are in team (return true/false or yes/no, anything)
(( Usefull for scoreboards ))

**Describe alternatives you've considered**
I tried to take team name but i can't work with blank

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
