### ISSUE TITLE
"Kicked" out of time when using /teama create 

### ISSUE THREAD

**Issue by Mato1111** [booksaw/BetterTeams#292]
**Describe the bug**
When creating a new team as an admin by using /teama create, it will remove you from the team you were already in. When running /team leave, it says you aren't in a team. After rejoining your original team, there will appear to be 2 of you (/team info and in the teaminfo file) in the same team and will continue to increase the more you use /teama create and rejoin. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Be in a team already
2. /teama create teamname
3. It will then (kinda) remove you from the team you were in and leave your name in the list of members

**Expected behaviour**
A team to be created without removing the admin from the original team and not duplicating the player in /team info

**Screenshots**
![image](https://user-images.githubusercontent.com/96366252/146805719-e7b92274-6d48-4364-bb5e-820aa1c6c19e.png)

**Details**
Please provide the following details about your server set-up: 

Server set up through DedicatedMC but the issue still occurs on a brand new server on my friend's home computer.
- Spigot version (found by running /version): Paper-82     Implemting API: 1.181.-R0.1-SNAPSHOT) (Git:8c5be16)
- BetterTeams version (found by running /version BetterTeams): 4.2.1

**Additional context**
Occurs on a fully set up server as well as an entirely fresh server with no other plugins.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
