### ISSUE TITLE
I have created a team, then I disbanded it. I tried to create a team with the same name as I have just disbanded, it keeps telling that a team with that name already exists, yet when I look at the list of teams, it doesn't show up there. /team disband x2. /team create GrooveStreet. That team already exists.  [BUG]

### ISSUE THREAD

**Issue by GreenGang121** [booksaw/BetterTeams#298]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command...
2. 

**Expected behaviour**

**Screenshots**

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
- BetterTeams version (found by running /version BetterTeams): 

**Additional context**

**Comment by booksaw** [comment]
What version of betterteams are you using?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
