### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iavengetheweak** [booksaw/BetterTeams#3]
**Describe the bug**
Newest version of the plugin has combined the commands /team promote and /team demote.  Where /team promote executes the command /team demote and even in /team help the description for /team promote is for demoting a player.  /team demote no longer exists as a command.

**To Reproduce**
Steps to reproduce the behaviour:
1. /team help -> to view the fact only /team promote exists and the wrong desc.
2. /team promote "player" -> will demote the player instead of promoting
3. /team demote "player" -> brings up the list of team commands because demote does not exist

**Expected behaviour**
/team promote and /team demote both exist and work as promoting and demoting players of a team

**Screenshots**
![image](https://user-images.githubusercontent.com/46011905/84562074-1ff19300-ad17-11ea-834c-db03719f5fa3.png)

No idea if that worked...

**Details**
Please provide the following details about your server set-up:
- Spigot version: 1.15.2
- BetterTeams version: 3.0.6

**Additional context**

**Comment by booksaw** [comment]
Thank you for the report, this problem will be fixed in version 3.0.7.

**Comment by booksaw** [comment]
The problem has been fixed and will be included within the 3.0.7 update. 
There is a chance you will also need to change the messages.yml value for the promote message (help.promote in older versions will say demote)
