### ISSUE TITLE
[BUG] BetterTeams with VentureChat

### ISSUE THREAD

**Issue by GoaTTheGoat** [booksaw/BetterTeams#30]
**Describe the bug**
At first I am using Chatmanager Plugin and it works very well. The prefix of my teams name is look like this "[Immortal]" without putting the placeholder into my chatmanager plugin. But when I switched to VentureChat, now it looks like this "Immortal" without putting the placeholder. 

**To Reproduce**
Steps to reproduce the behaviour:
1. When I place the %betterTeams_name% placeholder into the venturechat it looks like this "Immortal".
2. Try to chat ingame.
3. It must be "[Immortal]" not "Immortal"

**Expected behaviour**
It must be automatically will place the team name in the prefix like this "[Immortal]" without placing the placeholder of %betterTeams_name%

**Screenshots**
![image](https://user-images.githubusercontent.com/29046846/100497007-a732a600-3193-11eb-88a3-adcd900d43cf.png)

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
![image](https://user-images.githubusercontent.com/29046846/100497040-ccbfaf80-3193-11eb-951b-0863087e17e9.png)

- BetterTeams version (found by running /version BetterTeams): 
![image](https://user-images.githubusercontent.com/29046846/100497048-d9dc9e80-3193-11eb-8a0a-f1d7e43da4ec.png)

**Additional context**
None

**Comment by booksaw** [comment]
That is because you will be using the placeholder from placeholderAPI instead of the prefix chat of my plugin.

Just go to messages.yml and where it says placeholder.name and add square brackets around the %s
