### ISSUE TITLE
[FEATURE] Supporting ClaimChunks

### ISSUE THREAD

**Issue by ESP-Edgar** [booksaw/BetterTeams#301]
### What is the feature request for?

I would like to see this plugin be compatible with ClaimChunks this plugin is really amazing because it works like the way you want but you can't make a soffisticated team system, and BetterTeams is a nice plugin that has all of it. Some of the functions with ClaimChunk would be:

-Showing with a PlaceHolder who the owner is of the team
-Ranking
-Buying chunks with the balance of the team
-Selling Resources to gain balance
-And maybe compatible with the essentials economy so it would go through that

The main thing is that players can't claim for their own if they are in a team, at this moment with ClaimChunks only it isn't possible.

PS: I don't like Ultimate Claims it is too much and they ask a lot of money for their plugins.

### Relevant links

https://www.spigotmc.org/resources/claimchunk.44458/

**Comment by booksaw** [comment]
Duplicate Issue
