### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MrKrisy1234** [booksaw/BetterTeams#306]
### What is the bug?

When you kick, promote, and demote a player from a team the entire server lags for a second or two

### Expected Behaviour

For the command to not cause any lag at all

### How to Reproduce

Create a team

Try to kick a player. Works even if you do just "/team kick a"

Server will then lag, also works with doing promote and demote too

### Error message

There is no error message in console and nothing in timings reports

According to Spark the server tps never changes but the server does in fact freeze up

### Output of /teama version

[Teams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[Teams] Minecraft Version: git-Airplane-110 (MC: 1.17.1)
[Teams] Current plugin version: 4.3.2

### Additional Information

If you need anything else let me know

Also tried setting up a SQL to see if that would fix but I was spammed with error messages then but I believe it was conflicting with another plugin called TAB but that is a separate issue

**Comment by booksaw** [comment]
YAML is known to be slow on larger servers, use SQL. the latest update (likely released later today) should fix the issue with SQL, if it does not make bug reports for the SQL issues, there should not be any plugin conflicts with the SQL component of the plugin.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
