### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zikehalil3535** [booksaw/BetterTeams#308]
### What is the bug?

If I use team tittle giving error

### Expected Behaviour

-

### How to Reproduce

1. Run command /team title

### Error message

![image](https://user-images.githubusercontent.com/88826436/150107442-b10a8738-bc13-4525-b233-f260ad7c2d0f.png)

### Output of /teama version

Latest

**Comment by zikehalil3535** [comment]
Hey bookshaw hello, when time you fixing this?

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
