### ISSUE TITLE
[FEATURE] Have a typo free Messages.yml

### ISSUE THREAD

**Issue by DeathByAutoscroll** [booksaw/BetterTeams#31]
These are typos contained within the messages.yml currently hosted on github

'You are no longer allied wih [sic] that team' - **Line 190** - Should be "with"
'your [sic] team no longer...' - **Line 223**- No capitalisation on "Your"
'that players...' - **Line 255** - No capitalisation on "That"
'...do /teama setowner <player> &6To [sic] set the...' - **Line 268** - "To" should be lowercase.
'&6That warp has been set ' - **Line 274** - Extra space (not rly an issue but worth pointing out)
Delete your teams [sic] home - **Line 334** - Missing comma, should be "team's"

Ingame example
![2020-07-14-19-57-02](https://user-images.githubusercontent.com/39137649/102278932-818ef600-3f22-11eb-930e-b53efe36cc67.png)

**Comment by booksaw** [comment]
All typos have been fixed for the next update. 
Any older configs will automatically update to the correct messages version.
