### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ResopexTerror** [booksaw/BetterTeams#312]
### What is the bug?

Sends Ally notifications to players when they join the server even tho the teams are already allied.
![image](https://user-images.githubusercontent.com/98848378/152045966-916d8beb-02a8-468a-a7be-38a7ed7d0ea4.png)

### Expected Behaviour

Send this notification only when Ally requests are pending.

### How to Reproduce

Requires a player with closed /accepted allied requests to join the server.

### Output of /teama version

![image_2022-02-02_020233](https://user-images.githubusercontent.com/98848378/152046446-7848037f-582e-4b1e-9ed7-d4a720ccd0fc.png)

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
