### ISSUE TITLE
[BUG] Team Chest open as Admin/Op

### ISSUE THREAD

**Issue by MaxRubbel** [booksaw/BetterTeams#313]
### What is the bug?

Hello you can not look into the team chests as admin/op. I have not found a permission for this. Thanks for the help and the great plugin!

### Expected Behaviour

Add a permission for admins to look into the chests.

### How to Reproduce

Claim a Chest for a team and then try to look into the Chest.

### Output of /teama version

[BetterTeams]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[BetterTeams]: Minecraft Version: git-Paper-187 (MC: 1.18.1)
[BetterTeams]: Aktuelle Plugin-Version: 4.3.3

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
