### ISSUE TITLE
[FEATURE] A way to chat in team chat by just adding a '!' in ur message (from the general chat)

### ISSUE THREAD

**Issue by Woutie29** [booksaw/BetterTeams#314]
### What is the feature request for?

 A way to chat in team chat by just adding a '!' in ur message. This only works atm in team chat to general chat, but unfortunality tho not vice versa, I hope this get implemented in one of the future updates!

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
