### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by AstonicPI** [booksaw/BetterTeams#315]
### What is the feature request for?

A placeholder that will display the name of the Team Leader. The placeholder could be something like %betterTeams_leader%.

**Comment by booksaw** [comment]
Do you mean that this placeholder would only work if `singleOwner` is active?
or how would the placeholder react if multiple owners for the team exist?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
