### ISSUE TITLE
[FEATURE] Use usernames instead of display names for players in team/ally chat formats

### ISSUE THREAD

**Issue by tooop4u** [booksaw/BetterTeams#319]
### What is the feature request for?

Would make the chat a bit more compact, as there isn't really a need to see your member's displayname in team or ally chats.

**Comment by booksaw** [comment]
This seems to have been implemented under another change at some point. And so I an closing this feature request.
https://github.com/booksaw/BetterTeams/blob/8a5cc0c3eab0cc7f474211d158e206399089365d/src/main/java/com/booksaw/betterTeams/Team.java#L979
