### ISSUE TITLE
[BUG] Double "You are no longer allies with [team]" message

### ISSUE THREAD

**Issue by DeathByAutoscroll** [booksaw/BetterTeams#32]
**Describe the bug**
When unallying a team, you will be given both the Team unallying message, and the personal unallying message when you should only really get one of these messages

**To Reproduce**
Steps to reproduce the behaviour:
1. Ally a team
2. /team neutral a team as the only member (more members not tested)

**Expected behaviour**
Only one of the messages should show up to reduce redundency

**Screenshots**
![2020-07-14-19-57-02](https://user-images.githubusercontent.com/39137649/102279477-5f49a800-3f23-11eb-9df6-3a98afb2dad6.png)

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): fucking old af
- BetterTeams version (found by running /version BetterTeams): Recent as of 14th July 2020 (however dms were used to verify it was not fixed)

**Additional context**
Booksaw is fat

**Comment by booksaw** [comment]
This will be fixed in the next update.
