### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Styks13** [booksaw/BetterTeams#320]
Please add a way to prevent players teleporting out of combat using /team home and /team warp

**Comment by booksaw** [comment]
You can already do this by adding a delay to the teleport. in config.yml look for `tpDelay`.

If you need any more assistance please reply, else this issue will be closed in 40 days.

**Comment by Styks13** [comment]
how do i edit config files?

**Comment by booksaw** [comment]
that depends on how your server is hosted. You find the file in the folder /plugins/betterTeams/config.yml

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
