### ISSUE TITLE
[BUG] /team kick SERVER CRASH

### ISSUE THREAD

**Issue by sebastiaannnn** [booksaw/BetterTeams#321]
### What is the bug?

Hey, we talked about this in the discord server if someone performs /team kick
the entire server either crashes, gets frozen or huge tps drop (from 20 to 10) 
![image](https://user-images.githubusercontent.com/68129758/155846228-6d09f5db-5b37-4597-aefc-a6fd45ab5ecd.png)
![image](https://user-images.githubusercontent.com/68129758/155846230-74c15bfc-ad7b-4370-8ba3-2f2c82d54761.png)
![image](https://user-images.githubusercontent.com/68129758/155846234-838151f8-3751-49f3-a2df-af61780e154a.png)
[message (5).txt](https://github.com/booksaw/BetterTeams/files/8146758/message.5.txt)

Server specs:
amd ryzen 5 5600
19 gb ram

Playercount
Doesnt matter, happened with 90 players but also with only me online.

### Expected Behaviour

Fix the bug, I temporary disabled it for now bby not giving my players permissions

### How to Reproduce

Wasn't able to reproduce it on my test server tbh

### Output of /teama version

Latest version.
4.3.3

### Additional Information

High priority, serious matter.

**Comment by sebastiaannnn** [comment]
Additional info:
/team ban
also creates lagg, but less then /team kick
[tps 20 to 17]

**Comment by sebastiaannnn** [comment]
Update: the same happens with /team promote

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
