### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TheB2D** [booksaw/BetterTeams#324]
### What is the bug?

API documentation in the wiki page of the plugin features broken links that give a 404 error when accessing.

### Expected Behaviour

Should give a readable page of the documentation.

### How to Reproduce

1. Click [wiki tab](https://github.com/booksaw/BetterTeams/wiki) of the BetterTeams Github repo.
2. Click the ["API"](https://github.com/booksaw/BetterTeams/wiki/API) section.
3. Clicking on Hyperlink texts: TeamPlayers, BelowNameChangeEvent, PrePurgeEvent gives a 404 page.

### Error message

404 - This is not the web page you are looking for

404: Not Found

### Output of /teama version

Latest GitHub repository

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
