### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AmethystShards** [booksaw/BetterTeams#325]
### What is the bug?

When trying to /team set warp 
This message occurs 'An Internal error occurred while attempting to perform this command'  
And the warp does not get saved 

### Expected Behaviour

To fix the bug?

### How to Reproduce

1.Do /team setwarp example
2. This Message Occurs: An Internal error occurred while attempting to perform this command
3. And The warp does Not get saved 

### Error message

An Internal error occurred while attempting to perform this command
![image](https://user-images.githubusercontent.com/100928051/156748490-c1c20c09-2105-4896-b7f6-838a36baf63b.png)

### Output of /teama version

 
![image](https://user-images.githubusercontent.com/100928051/156748358-a3a041ac-fce3-4871-a8af-1ec493a4da1c.png)

### Additional Information

The warp get saved when the player who set the warp is online and when he logs off the server warp gets removed

**Comment by booksaw** [comment]
What is the error message in the console?

when I try and recreate the bug I get the following: 
![image](https://user-images.githubusercontent.com/13976636/159314882-615a18a1-eee1-4f83-83a5-d8881370c548.png)
If I cannot recreate the issue or view the error message I cannot fix the bug.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
