### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ZedarOfficial** [booksaw/BetterTeams#330]
### What is the bug?

When you create a clan and disband it right after it will say that the clan with that name already exists.

### Expected Behaviour

To be able to create a clan with that name afterwards.

### How to Reproduce

1. Create a clan
2. Disband the clan
3. Attempt to create the clan again with the same name

### Error message

N/A

### Output of /teama version

![image](https://user-images.githubusercontent.com/74577732/161386615-6a646de5-ec1e-46b9-aefa-ea27a24628ab.png)

**Comment by booksaw** [comment]
Hi, this bug has been reported repeatedly in the past. If you can figure out how to reproduce the bug from a clean install I will be able to fix it, else I will not be able to fix it. 

I have tried searching the code for anything that could possibly cause the bug, but I cannot find anything. I need a consistent way of reproducing this bug for me to be able to find the root.

Screenshot of me testing: 
![image](https://user-images.githubusercontent.com/13976636/161580862-3711ebed-8200-498a-a74c-67dc2280256b.png)

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
