### ISSUE TITLE
PVP wont be on with teamates [BUG] 

### ISSUE THREAD

**Issue by VeryTimmy** [booksaw/BetterTeams#334]
### What is the bug?

i was just wondering why i still cant damage my teamate (also restarted server)
theres also no error
![unknown](https://user-images.githubusercontent.com/103639509/163374125-9f368ead-90c4-4f39-9651-0bfc611a3cc6.png)

### Expected Behaviour

help me fix this please

### How to Reproduce

1. Install the plugin
2. Get in config
3. Change disableCombat to false
4. Restarted server
- I still cannot damage my teamates.

### Output of /teama version

![image](https://user-images.githubusercontent.com/103639509/163376309-70f86deb-657b-4900-96b1-88ca01ebe081.png)

**Comment by booksaw** [comment]
Hi, I think this may be due to another plugin interacting as I have just tested and disableCombat works as expected for me.
