### ISSUE TITLE
[BUG] /team promote command not finding the player

### ISSUE THREAD

**Issue by AstonicPI** [booksaw/BetterTeams#336]
### What is the bug?

Basically when a team leader tries to promote a player (the player is in the team and the player name is correct), but BetterTeams outputs the issue that the player is not found.
![Uploading unknown.png…]()

### Expected Behaviour

It should promote the player

### How to Reproduce

1. Run command /team promote (player)

### Error message

Specified player not found

### Output of /teama version

![image_2022-04-16_144117418](https://user-images.githubusercontent.com/84206179/163675352-50a023bc-8043-41dd-8865-7b7c104a05ee.png)

**Comment by booksaw** [comment]
Hi, I have attempted to recreate the bug, but when I perform /team promote the player is promoted as expected. Please can you provide information on how to reproduce from a clean install

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
