### ISSUE TITLE
[FEATURE] Restoration of features from the vanilla /teams command.

### ISSUE THREAD

**Issue by DeathByAutoscroll** [booksaw/BetterTeams#34]
**Is your feature request related to a problem? Please describe.**
There are vanilla "/team" features missing/not supported in the latest version of BetterTeams. These include: The ability to hide player nametags, disable collisions, see invisible players (within the team) as a ghost, specific team deathmessage visibility, and have multiple colours within the team name (Although in vanilla survival this is very jank in the way it is done, essentially declaring each unique text string as a different colour then connecting it into one thing)

**Describe the solution you'd like**

A BetterTeams equivilent commands/server settings for:

`/team modify <teamName> collisionRule [always, never, pushOtherTeams, pushOwnTeam]`
`/team modify <teamName> deathMessageVisibility [always, never, hideForOtherTeams, hideForOwnTeam]`
`/team modify <teamName> nametagVisibility [always, never, hideForOtherTeams, hideForOwnTeam]`
`/team modify <teamName> seeFriendlyInvisibles [true, false]`
`/team modify <teamName> prefix  [{"text":"team ","color":"gray"),{"text":"team","color":"red"}]` <-- Ew gross single line JSON

e.g:
`/team collision [on, off]` - Toggles collision **within** a team, server settings can determine if teams should push other things
`/team deathMessages [on, off]` - Toggles death messages showing within a team, server settings for if deathmessages should be shown to any other team
`/team nametag [show, hide]` - Toggles nametags/playernames showing to other team members, server settings for if it should display to anything else
`/team seeInvis [show, hide]` - Shows invisible teamsmates within the team as a ghost for other teammembers
`/team colour &7team &4name` - Modification of the existing /team colour to use colour codes rather than a dropdown of colours

**Describe alternatives you've considered**
Playing vanilla, going outside

**Additional context**
Sidenote: If you gave all villagers on the server a team and then disabled collisions within that team (but not to anything else) you could make reletively lag friendly entity launchers which would be really cool

**Comment by booksaw** [comment]
/team modify <teamName> prefix [{"text":"team ","color":"gray"),{"text":"team","color":"red"}] <-- Ew gross single line JSON
this is how the team name / color is displayed so this command cannot be used.

For the rest of the commands, they may need to turn into config options as I am unsure how efficiently I can create custom commands for them as the Minecraft team integration with this plugin is quite complex.

**Comment by booksaw** [comment]
TODO: 

- [ ] collisionRule 
- [ ] deathMessageVisibility 
- [ ] nametagVisibility 
- [ ] seeFriendlyInvisibles

**Comment by booksaw** [comment]
This has been implemented and will be included within the next update.
