### ISSUE TITLE
[BUG] tag in invitation message on chat

### ISSUE THREAD

**Issue by SpizganyTomek** [booksaw/BetterTeams#341]
### What is the bug?

When someone invites other player, he don't get tag placeholder on chat. Instead of that he gets %s. 
PL language

### Output of /teama version

4.3.7

**Comment by SpizganyTomek** [comment]
pl language

**Comment by SpizganyTomek** [comment]
![bug](https://user-images.githubusercontent.com/69018833/164533360-0c8d1fcd-31bd-4996-b1e7-86dad69d04f8.jpg)
`# All translations in this file are community made, this means there may be errors / missed translations, if you are able to improve upon any translation it would be greatly appreciated

# Able to help with translations? Either improving a already existing language, or adding a whole new one. Join the discord server: https://discord.gg/JF9DNs3 
# or message me on spigot: https://www.spigotmc.org/members/booksaw123.120955/

# Any placeholders from placeholder API will work in this file
# general errors
invalidArg: '&4Taka komenda nie istnieje'
inTeam: '&4Musisz być w teamie żeby to zrobić'
notInTeam: '&4Musisz opuścić team żeby to zrobić'
needOwner: '&4Musisz być założycielem teamu żeby to zrobić'
needAdmin: '&4Musisz być założycielem lub zastępcą teamu żeby to zrobić'
needPlayer: '&4Musisz być graczem żeby to zrobić'
noPlayer: '&4Nie znaleziono tego gracz'
notTeam: '&6&4Ten team nie istnieje &b/team create <nazwa>'
needSameTeam: '&6Nie jesteście w tym samym teamie'
noPerm: '&4Nie masz permisji aby to zrobić'
prefixSyntax: '&b[%s] &r%s'
bannedChar: '&4Ta nazwa jest zakazana"'
noTeam: '&4Ten team nie istnieje'
version: 16
cooldown:
  wait: '&4Musisz poczekać %s sekund zanim tego użyjesz!'
cost:
  tooPoor: '&4Nie stać cię na tą komendę'
  run: '&4&l-%s'
placeholder:
  noTeam: ''
  noDescription: ''
  owner: Założyciel
  admin: Szef
  default: Członek
  name: '%s'
  money: '%s '
  tag: '%s'
  displayname: '%s'
prefix:
  owner: ' **'
  admin: ' *'
  default: ' '
create:
  exists: '&6Taki team już istnieje'
  success: '&6Stworzyłeś team'
  banned: '&4Ta nazwa jest zablokowana'
  maxLength: '&4Ta nazwa jest za długa'
leave:
  success: '&6Opuściłeś team'
  lastOwner: '&6Jesteś jedynym założycielem teamu, awansuj kogoś innego lub opuść
    team &b/team disband'
rank:
  noTeam: '&4Nie ma takiego teamu'
  info: '&6Team position:'
  syntax: '&b%s: &6%s &7(%s)'
  infos: '&6Punktacja drużyny: &b%s &7(%s punkty potrzebne do awansu)'
  infom: '&6Punktacja drużyny: &b%s &7($%s potrzebne do awansu)'
delhome:
  success: '&6Usunąłeś sethome teamowy'
  noHome: '&4Twój team nie ma sethome'
disband:
  success: '&6Opuściłeś team'
  confirm: '&6Wpisz ponownie &b/team disband &6aby potwierdzić'
description:
  success: '&6Zmieniłeś opis teamu'
  view: '&6Opis teamu: %s'
  noDesc: '&6Opis teamu - nieustawiony'
  noPerm: '&4Nie posiadasz uprawnień aby edytować opis'
name:
  success: '&6Zmieniłeś nazwę teamu'
  view: '&6Nazwa: %s'
  exists: '&4Taki team już istnieje'
  noPerm: '&4Nie posiadasz uprawnień aby edytować tytuł drużyny'
invite:
  success: '&6Gracz został zaproszony'
  invite: '&6Zostałeś zaproszony do teamu: &f%s %betterTeams_name% &6wpisz &b/team dolacz %s &6 aby dołączyć
    do tego teamu'
  inTeam: '&6Ten gracz już jest w teamie'
  banned: '&6Ten gracz jest zbanowany w twoim teamie'
  full: '&6Twój team jest pełny, wyrzuć kogoś aby dodać nową osobę'
  expired: '&4Zaproszenie od &b%s wygasło'
join:
  success: '&6Dołączyłeś do teamu'
  notify: '&6Witaj &b%s &6w teamie!'
  notInvited: '&6&4Nie zostałeś zaproszony do tego teamu'
  banned: '&6&4Jesteś zbanowany przez założyciela tego teamu'
  full: '&4Ten team jest pełny'
open:
  successopen: '&6Teraz każdy może dołączyć do twojego teamu'
  successclose: '&6Gracz musi być zaproszony żeby dołączyć do twojego teamu'
title:
  change: '&6Twój tytył został zmieniony na &b%s'
  success: '&6Zmieniono twój tytuł'
  tooLong: '&4Ten tytuł jest za długi'
  noFormat: '&4Nie masz uprawnień aby edytować tytuły'
  noColor: '&4Nie masz uprawnień aby edytować kolor tytułu'
  reset: '&6Zrestowano twój tytuł'
info:
  needTeam: '&6Nie ma takiego teamu lub gracza'
  name: '&6Nazwa: &b%s'
  description: '&6Opis: &b%s'
  open: ''
  owner: '&6Założyciel: &b%s'
  admin: '&6Zastępcy: &b%s'
  default: '&6Członkowie: &b%s'
  fail: '&6Nie ma takiego teamu lub gracza'
  score: '&6Punkty: &b%s'
  money: '&6Bank: &b%s'
  ally: '&6Sojusznik: &b%s'
  level: '&6Poziom: &b%s'
  tag: '&6Tag: &b%s'
kick:
  success: '&6Ten gracz został wyrzucony'
  notify: '&6Zostałeś wyrzucony z teamu %s'
  noPerm: '&6Nie masz permisji aby wyrzucić tą osobę'
ban:
  success: '&6Ten gracz został zbanowany'
  notify: '&6Zostałeś zbanowany z teamu %s'
  noPerm: '&6Nie masz uprawnień aby zbanować tę osobę'
  already: '&6Ten gracz już jest zbanowany'
unban:
  success: '&6Gracz został odbanowany'
  notify: '&6Zostałeś odbanowany w teamie %s'
  noPerm: '&6Nie masz uprawnień aby odbanować tę osobę'
  not: '&6Ten gracz nie jest zbanowany'
promote:
  success: '&6Gracz został awansowany'
  noPerm: '&6Nie masz uprawnień aby awansować osoby'
  max: '&6Ta osoba ma najwyższą rangę!'
  notify: '&6Otrzymałeś awans!'
demote:
  success: '&6Ten gracz został zdegradowany'
  noPerm: '&6Nie masz uprawnień aby degradować osoby'
  min: '&6Ta osoba ma już najniższą rangę'
  notify: '&6Zostałeś zdegradowany na niższą rangę'
  lastOwner: '&6Nie możesz zdegradować założyciela'
home:
  success: '&6Zostałeś teleportowany'
  noHome: '&6Twój team nie ma homea'
  world: '&4Lokalizacja domu drużyny nie może zostać odnaleziona'
sethome:
  success: '&6Ustawiono home w twoim teamie'
  noPerm: '&6Nie masz wystarczającej rangi aby ustawić home'
chat:
  enabled: '&6Chat teamowy włączony'
  disabled: '&6Chat teamowy wyłączony'
  syntax: '&6&b[Team]&f%s: %s'
color:
  success: '&6Kolor teamu zmieniony'
  fail: '&6Nie ma takiego koloru'
  banned: '&4Kolor musi być nazwą po angielsku'
deposit:
  tooLittle: '&4Nie możesz wpłacić negatywnej wartości'
  fail: '&4Przelew nie powiódł się'
  success: '&6Wpłacono kasę do banku teamowego'
withdraw:
  tooLittle: '&4Nie możesz wypłacić takiej wartości'
  fail: '&4Wypłata nie powiodła się'
  success: '&6Wypłacono kasę'
  notEnough: '&6Nie macie tyle kasy w banku teamowym'
ally:
  already: '&4Już jesteście sojusznikami'
  success: '&6Wasze teamy są teraz sojusznikami'
  ally: '&6Zostaliście sojusznikami z &b%s'
  requested: '&6Wysłano prośbe o zostanie sojusznikami'
  request: '&b%s &6wysłali wam prośbę sojuszu, wpisz &b/team ally <nazwa> &6aby akceptować'
  self: '&4Nie możesz tego zrobić'
  from: '&6Masz prośbę sojusz z: %s'
  noRequests: '&4Nie masz zaproszenia do sojuszu'
  onJoin: '&6Masz nową prośbę sojuszu, wpisz &b/team ally &6aby ją zobaczyć'
  limit: '&4Limit sojuszników został osiągnięty'
allychat:
  disabled: '&6Wyłączono chat z sojusznikami'
  enabled: '&6Włączono czat z sojusznikami'
  syntax: '&d[%s]&f%s: %s'
neutral:
  self: '&6Nie możesz tego zrobić'
  requestremove: '&6Już nie jesteście sojusznikami'
  reject: '&4Prośba o sojusz z &b%s &4została odrzucona'
  notAlly: '&4Nie jesteście sojusznikami'
  success: '&4Już nie jesteście sojusznikami'
  remove: '&4Już nie jesteście sojusznikami z &b%s'
list:
  noPage: '&6Nie znalezniono strony'
  header: '&7--- &bLista teamów %s &7---'
  body: '&6%s: &b%s'
  footer: '&7--- &6wpisz &b/team list [strona] &6aby zobaczyć więcej &7---'
setowner:
  use: '&6Nie możesz awansować tego gracz, wpisz &b/team setowner <gracz> &6aby awansować
    gracza na założyciela'
  success: '&6Ten gracz nie jest założycielem'
  notify: '&6Nie jesteś założycielem'
  max: '&4Ten gracz jest już założycielem'
setwarp:
  exist: '&4Ten warp już istnieje'
  max: '&4Nie możecie ustawić więcej warpów'
  success: '&6Stworzono warpa'
  char: '&4Wybrana nazwa warpa zawiera niedozwolone znaki'
warp:
  nowarp: '&4Ten warp nie istnieje'
  invalidPassword: '&4Nieprawidłowe hasło'
  success: '&6Zostałeś teleportowany'
  world: '&4Lokalizacja warpu nie może zostać odnaleziona'
warps:
  syntax: '&6Warpy: &b%s'
  none: '&4Nie macie warpów w teamie'
delwarp:
  success: '&4Usunięto warpa'
teleport:
  fail: '&4Telportacja anulowana'
  wait: '&6Poczkaj &b%s &6sekund'
chest:
  claim:
    noChest: '&4Nie stoisz na skrzyni'
    limit: '&4Już macie maksymalną ilośc skrzyń'
    claimed: '&4Ta skrzynka jest już zabezpieczona'
    success: '&6Zabezpieczyłeś tę skrzynię'
  remove:
    noChest: '&4Nie stoisz na skrzyni'
    notClaimed: '&4Ta skrzynia nie jest zabezpieczona przez twój team'
    success: '&4Usunięto zabezpieczenie skrzyni'
  all:
    success: '&6Odbezpieczono wszystkie skrznie'
  claimed: '&4Skrznia jest zabezpieczona przez &a%s'
admin:
  config:
    reload: '&6Reloadzik... Czasami wymagany jest restart serwera.'
  holo:
    create:
      success: '&6Hologram stworzono'
    remove:
      noHolo: '&4Brak hologramów'
      success: '&6Hologram usunięto'
  title:
    success: '&6zmienino tytuł gracza'
    reset: '&6Zrestowano tytuł gracza'
  version: '&6Wersja pluginu: %s'
  noTeam: '&4To nie jest team'
  home:
    success: '&6Przeteleportowano cię do home teamowego'
    noHome: '&4Ten team nie ma homea'
  name:
    success: '&6Zmieniono nazwę teamu'
  description:
    success: '&6Ten team zmienił swoją nazwę'
  open:
    successopen: '&6Każdy może dołączyć do tego teamu bez zaproszenia'
    successclose: '&6Musisz otrzymać zaproszenie aby dołączyć do tego teamu'
  invite:
    success: '&6Ten gracz został zaproszony do teamu'
  create:
    success: '&6Team został stworzony'
  join:
    banned: '&4Ten gracz został zbanowany z tego teamu'
    success: '&6Ten gracz dołączył do teamu'
    notify: '&6Dołączyłeś do teamu &b%s'
    full: '&4Ten team jest pełny'
  notInTeam: '&6Ten gracz nie może być w teamie'
  inTeam: '&4Ten gracz nie jest w teamie'
  leave:
    success: '&6Ten gracz opuścił team'
    notify: '&6Opuściłeś ten team'
  demote:
    notify: '&6Zostałeś zdegradowany'
    success: '&6Gracz został zdegradowany'
    min: '&4Ten gracz ma już najniższą rangę'
  promote:
    max: '&6Ten gracz ma już najwyższą rangę'
    notify: '&6Otrzymałeś awans'
    success: '&6Gracz otrzymał awans'
    owner: '&6W teamie może być tylko jeden założyciel, &b/teama setowner <gracz>
      &6aby ustawić założyciela'
  setowner:
    already: '&4Ten gracz już jest założycielem'
    nonotify: '&6Już nie jesteś założycielem'
    success: '&6Ten gracz jest teraz nowym założycielem'
    notify: '&6Jesteś teraz założycielem teamu'
  warps:
    none: '&4Ten team nie ma żadynch warpów'
  setwarp:
    success: '&6Ustawiono warpa'
    max: '&6Ten team osiągnał już limit warpów'
  purge:
    confirm: '&6Wpisz tą komendę ponownie w ciągu 10 sek, &4TA AKCJA NIE MOŻE ZOSTAĆ
      COFNIĘTA!'
    success: '&6Teamy zostały wyczyszczone!'
  score:
    tooSmall: '&4Punkty muszą być większe niż 0'
    success: '&6Zmieniono ilość punktów dla tego teamu'
  update: '&4Wyszła nowa wersja BetterTeams: https://www.spigotmc.org/resources/better-teams.17129/updates'
  disband:
    success: '&6Team rozwiązano pomyślnie'
  color:
    success: '&6Kolor teamu został zmieniony'
  chest:
    claim:
      success: '&6Zabezpieczyłeś skrzynkę dla całego teamu'
    remove:
      success: '&6Usunąłeś zabezpieczenie skrzynki'
      notClaimed: '&4Żaden team nie zabezpieczył tej skrzynki'
    all:
      success: '&6Wszystkie zabezpieczone skrzynki zostały usunięte'
    disable:
      already: '&4Zabezpieczone skrzynki są już wyłączone'
      success: '&6Wyłączono zabezpieczanie skrzynek'
    disabled:
      bc: '&6&lWszystkie zabezpieczone skrzynki można teraz otwierać'
    enable:
      already: '&4Zabezpieczanie skrzynek jest już włączone'
      success: '&6Zabezpieczanie skrzynek zostało włączone'
    enabled:
      bc: '&6&lWszystkie zabezpieczone skrzynki są zablokowane'
  setrank:
    success: '&6Ranga drużyny została ustawiona'
    'no': '&4Wybrana ranga nie istnieje lub nie jest ustawiona prawidłowo'
  tag:
    success: '&6Tag wybranej drużyny został pomyślnie zmieniony'
  cancel: '&4Komenda została anulowana przez inny plugin'
nametag:
  syntax: '&6&l%s&r '
holo:
  leaderboard: '&6Tabela'
  syntax: '&6%s: &b%s'
  msyntax: '&6%s: &b$%s'
top:
  leaderboard: '&6Tabela'
  syntax: '&b%s: &6%s &7(%s)'
  divide: '&f...'
spy:
  stop: '&6Wyłączono podgląd chatu teamowego'
  start: '&6Włączono podgląd chatu teamowego'
  team: '&7[&b%s&7]&f%s&f: %s'
  ally: '&7[&d%s&7]&f%s&f: %s'
help:
  description: Pokazuje i zmienia opis teamu
  ban: Banuje osobę z teamu
  home: Teleportuje do home teamu
  help: Pokazuję tę stronę
  promote: Awansuje gracza na wyższą rangę
  demote: Degraduje gracza na niższą rangę
  unban: Unbanuje gracza z teamu
  kick: Wyrzuca członka z teamu
  leave: Opuszczasz team, w którym jesteś
  chat: Wysyła wiadomośc do osób z teamu
  name: Pokazuje i zmienia nazwę teamu
  sethome: Ustawia home teamowy
  create: Tworzy team o podanej nazwie
  invite: Zaprasza osobę do teamu
  disband: Usuwa team
  open: Włącz aby każdy mógł dołączyć bez zaproszenia
  info: Pokazuje info o graczu / teamie
  color: Zmienia kolor teamu
  deposit: Wpłaca kasę do banku teamowego
  bal: Pokazuje kasę w banku teamowym
  withdraw: Wypłaca kasę z banku teamowego
  title: Zmienia tytuł gracza w teamie
  top: Pokazuje topke teamów
  rank: Pokazuje ranking twojego teamu
  join: Dołącz do teamu
  delhome: Usuwa home teamowy
  ally: Utwórz sojusz między teamami
  neutral: Zerwij sojusz
  allychat: Chat z sojusznikami
  setwarp: Ustawia warp dla teamu
  warps: Pokazuje listę warpów w teamie
  delwarp: Usuwa warpa teamowego
  chest: ''
  list: Pokazuje listę wszystkich teamów
  warp: Teleportuje do warpa teamowego
  removeall: Usuwa wszystkie zabezpieczone skrzynki
  claim: Zabezpiecza skrzynkę na której stoisz
  remove: Odbezpiecza skrzynkę na której stoisz
  chatspy: Szpieguj wiadomości teamowe
  purge: Resetuj punkty wszystkich teamów
  version: Wersja pluginu
  score: ''
  reload: Reloadzik configu
  holo: ''
  setowner: Ustawia nowego założyciela teamu
  echest: View your teams ender chest
  rankup: Rank your team up to get more perks
  tag: Set your teams tag
  pvp: Toggle if pvp is enabled for your team
  baltop: View the richest teams
command:
  create: stworz
  leave: opusc
  disband: rozwiaz
  description: opis
  invite: zapros
  join: dolacz
  name: nazwa
  open: open
  info: info
  kick: wyrzuc
  promote: awanasuj
  demote: degraduj
  home: home
  sethome: sethome
  ban: ban
  unban: unban
  chat: chat
  color: color
  title: title
  top: top
  rank: rank
  delhome: delhome
  ally: sojusz
  neutral: wrog
  allychat: sojchat
  list: list
  warp: warp
  setwarp: setwarp
  delwarp: delwarp
  warps: warps
  claim: claim
  remove: remove
  removeall: removeall
  chest: chest
  reload: reload
  chatspy: chatspy
  version: version
  purge: purge
  add: add
  set: set
  score: score
  enableclaims: enableclaims
  disableclaims: disableclaims
  holo: holo
  deposit: wplac
  bal: bank
  withdraw: wyplac
  setowner: zalozyciel
  echest: ec
  pvp: pvp
echest:
  echest: '&bTeamowy &9Enderchest'
pvp:
  enabled: '&6PvP w Teamie zostało &awłączone'
  disabled: '&&6PvP w Teamie zostało &cwyłączone'
baltop:
  leaderboard: '&6Tablica wyników'
  syntax: '&b%s: &6%s &7(%s)'
  divide: '&f...'
rankup:
  max: '&4Posiadasz już najwyższą rangę'
  score: '&4Potrzebujesz %s punktów by podnieść rangę'
  money: '&4Potrzebujesz %s waluty w drużynowym balansie by podnieść rangę'
  success: '&6Twoja drużyna awansowała na wyższy poziom'
tag:
  banned: '&4Wybrany tag jest zakazany'
  success: '&6Twój tag został pomyślnie zmieniony'
  maxLength: '&4Wybrany tag jest zbyt długi'
  noPerm: '&4Nie posiadasz uprawnień aby edytować tag drużynowy'
uclaim:
  member: '&4Nie możesz zdjąć działki drużyny'
  kick: '&4Nie możesz wyrzucić członków drużyny ze swojego terenu'
  ban: '&4Nie możesz zablokować członków drużyny na swoim terenie'
  dissolve: '&4Twoja drużyna została rozwiązana, przez to twój teren również.'
  team: '&4Musisz znajdować się w drużynie by stworzyć teren'
`

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
