### ISSUE TITLE
[TRANSLATION] Add Indonesian (id)

### ISSUE THREAD

**Issue by 72stom** [booksaw/BetterTeams#342]
**Language the issue is about**

**Details about request**
I want to add a new language
[messages.yml](https://www.toptal.com/developers/hastebin/gobitotuxu.less)

**Translations**
in the form of Indonesian

**Discord name** 
72_TUI#0805

**Comment by booksaw** [comment]
Hi, the url is not working. it woud be appreciated if you could paste the result into a comment instead of sharing as a pastebin as they expire

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
