### ISSUE TITLE
[FEATURE] Add placeholder support to get information of a player by name

### ISSUE THREAD

**Issue by alimix3** [booksaw/BetterTeams#343]
### What is the feature request for?

Placeholders like `%betterTeams_name%` are great to get relevant information about the team you are part of. In addition to this, I think it would be great to have the chance to get that information for any player, in order to be able to build some custom UI's like a tooltip when you mouseover another player in the chat.

For instance, adding the player as a possible parameter for the placeholders `%betterTeams_name_<player>%` could work well for this type of scenarios.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
