### ISSUE TITLE
[FEATURE] List of all players online and offline for each team.

### ISSUE THREAD

**Issue by ParrotRacer** [booksaw/BetterTeams#346]
### What is the feature request for?

New placeholders that display a list of team members (their display name). So if Bob, Jeff and Tom are in the #1 ranked team and online and the placeholder "%betterTeams_position_onlinelist_%" is used it would display "&fBob Jeff Tom".   

%betterTeams_position_onlinelist_{rank}% - Displays the list of online players for that ranked team.
%betterTeams_position_offlinelist_{rank}% - Displays the list of offline players for that ranked team.
%betterTeams_members_onlinelist_<team>% - Displays the list of online players for that team.
%betterTeams_members_offlinelist_<team>% - Displays the list of offline players for that team.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.

The last two placeholders have a different placeholder than suggested, but have the same function:
%betterTeams_members_onlinelist_% -> %betterTeams_onlinelist%
%betterTeams_members_offlinelist_% -> %betterTeams_offlinelist%
