### ISSUE TITLE
[BUG] /team home delay not working

### ISSUE THREAD

**Issue by cao-eric** [booksaw/BetterTeams#347]
### What is the bug?

The delay for the _/team home_ and _/team warp <warp>_ commands is not working. Teleporting is instantaneous. By delay I do **not** mean the cooldowns between spamming _/team home_, but rather the amount of time before the teleport executes. Thus when fighting enemy teams, the opponents can sprint away and type _/team home_ and immediately teleport to safety. There is supposed to be a delay in which they cannot move for a certain amount of seconds.

### Expected Behaviour

I expect there to be a message alerting the player that the "/team home" command has been used and the player must remain still for X amount of seconds without moving. If the player were to move in this time frame, then the player would not teleport to their team home or warp and must retype the command.

### How to Reproduce

1. Go into the config.yml file located in the plugins/BetterTeams folder.
2. Edit the following lines: 
![image](https://user-images.githubusercontent.com/73639302/169137317-dda48c66-2bd1-4f07-bbee-d53b8ba285d6.png)
3. Save the file and run the server.
4. With permissions available, create a team home or warp: _/team sethome_
5. Then use the command: _/team home_

### Output of /teama version

Console log:
![image](https://user-images.githubusercontent.com/73639302/169137949-d9c7ad1a-b22c-4d33-9d00-cc6a0d8c0b02.png)

Ingame:
![image](https://user-images.githubusercontent.com/73639302/169137880-cbbcd05d-4c7c-4d5a-88c3-5601e89fa6e6.png)

### Additional Information

Currently using version 1.18.2 on a completely brand new server.
No other plugins are currently installed.

**Comment by booksaw** [comment]
ive had a test and its all working for me, there is a permission node betterteams.warmup.bypass to bypass the teleport delay, ensure you are not opped and do not have that permission node and try again

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
