### ISSUE TITLE
[BUG] TAG should be a must have to set but it is not 

### ISSUE THREAD

**Issue by homerek111** [booksaw/BetterTeams#348]
### What is the bug?

In config there are set: 

prefix: tag
enforceTag: true

But when player create team with setting name only it is still possible to do so and he has team's name as a prefix...
So he can force TAG characters limit because on name there is bigger limit than on TAG

### Expected Behaviour

make player must set tag as well while creating team

### How to Reproduce

config:
prefix: tag
enforceTag: true
maxTeamLength: 11
maxTagLength: 4

1. run command: /team create <name>

### Error message

no error

### Output of /teama version

Storage Method: http://com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager
Minecraft Version: git-Paper-339 (MC: 1.18.2)
Plugins Version 4.4.0

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
