### ISSUE TITLE
Can you add a feature where you can disable team names so owners cant change it only admins can?

### ISSUE THREAD

**Issue by sfgdfgfdgdfgdfgfdgdf** [booksaw/BetterTeams#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by booksaw** [comment]
This is already possible through permission nodes:
As shown (on the permissions wiki)[https://github.com/booksaw/BetterTeams/wiki/Permissions] the permission node for a team name is 'betterteams.name' if you give that to your default user but set it to false (it is by default given to all users) they will no longer be able to change their team name. The admin command to change team names will remain uneffected. 

In future could you fill out the body of the feature request, as that makes it easier for me.
