### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by iDastz** [booksaw/BetterTeams#350]
### What is the bug?

`enforceTag: true` It's not working. When activated, it only modifies the help menu but does not ask users to create a team with a tag.

### Expected Behaviour

Solve it

### How to Reproduce

1. Set `enforceTag:` to true

### Error message

I don't have (The console don't past it)

### Output of /teama version

4.4.0

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
