### ISSUE TITLE
[BUG] Can´t kick players from a clan

### ISSUE THREAD

**Issue by lunarmints** [booksaw/BetterTeams#354]
### What is the bug?

When trying to remove someone who has been offline for some time, /team kick <username> will show an error message in chat: "Specified player not found". Same issue is encountered when an administrator attempts the command /team leave <username>. Both times the username is written perfectly, including numbers and sensitive capitalization. 
Note: This has been tested with both a Bedrock user and a Java one, it only appears to be happening with Bedrock users, who have an underscore in front of their names (Have attempted to write their users both with the underscore and without it, error still happens).

### Expected Behaviour

Players should be able to remove old members from their teams, wether they are online or offline.

### How to Reproduce

1. Run command /team kick <username>
2. See the error message appear

### Error message

Specified player not found

### Output of /teama version

![Captura de pantalla (494)](https://user-images.githubusercontent.com/107825603/174655142-01ebded6-9c61-430a-ac47-20ce0e651cb2.png)

### Additional Information

rebuildLookups has been set to True and server was restarted, still no luck

**Comment by booksaw** [comment]
As discussed on the discord server, this is not an official distribution of betterteams, please report the bug to the developer of this alternative version.
