### ISSUE TITLE
[FEATURE] DecentHolograms Support

### ISSUE THREAD

**Issue by KahpotVanilla** [booksaw/BetterTeams#357]
### What is the feature request for?

Popular hologram plugin alongside HolographicDisplays to display the team leaderboards

### Relevant links

https://www.spigotmc.org/resources/decent-holograms-1-8-1-19-papi-support-no-dependencies.96927/

### Additional Information

I hope it will come fast!

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
