### ISSUE TITLE
[BUG] PAPI errors

### ISSUE THREAD

**Issue by mario638** [booksaw/BetterTeams#359]
### What is the bug?

BetterTeams doesn't pair with PAPI

### Expected Behaviour

to show all the placeholders

### How to Reproduce

/papi parse me %betterteams_name%
and it shows up as %betterteams_name%

### Error message

No errors

### Output of /teama version

[BetterTeams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[BetterTeams] Minecraft Version: git-Purpur-1566 (MC: 1.18.1)
 [BetterTeams] Current plugin version: 4.4.1

**Comment by mario638** [comment]
I have the error since I updated to PlaceholderAPI-2.11.1.jar

**Comment by booksaw** [comment]
I am unable to reproduce your bug. It is likely an integration issue. Let me know if you can provide a more detailed bug report.
![image](https://user-images.githubusercontent.com/13976636/182243688-5497d064-9efb-4bde-b1fc-829793c94697.png)

**Comment by mario638** [comment]
Ok i will

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
