### ISSUE TITLE
[BUG] Console database error

### ISSUE THREAD

**Issue by TaMYzZz** [booksaw/BetterTeams#360]
### What is the bug?

When i start the server and let it run for almost 10 minutes with no players online, then i join the server and it crashes with a database error from BetterTeams

### Expected Behaviour

Not that error

### How to Reproduce

1.  Start the server
2.  Let it run with no players for almost 10 minutes
3.  Join and the server crash 

### Error message

https://pastebin.com/vmAJa27D (Sorry that i used pastebin but the error is too long for github)

### Output of /teama version

[18:21:04 INFO]: Equipos » Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SQLStorageManager
[18:21:04 INFO]: Equipos » Minecraft Version: git-Paper-790 (MC: 1.16.5)
[18:21:04 INFO]: Equipos » Current plugin version: 4.4.1

**Comment by booksaw** [comment]
There is likely an issue with the database connection settings in config.yml. I will look into ensuring this does not cause a server crash in the future.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
