### ISSUE TITLE
[BUG] items from team echest disappearing

### ISSUE THREAD

**Issue by Defaultplayz1** [booksaw/BetterTeams#361]
### What is the bug?

One team on my SMPS items in team chest keep disappearing

### Expected Behaviour

to fix it

### How to Reproduce

1. put item in team echest 
2. wait awhile
3. check the team echest again

### Error message

none

### Output of /teama version

![image](https://user-images.githubusercontent.com/109680924/180047567-c0a28b1f-3d9d-4663-8260-11de995e12d7.png)

**Comment by booksaw** [comment]
I have tried to reproduce the bug with the instructions provided and the file you DMed to me, but everything is working as expected. 
I will need more specific instructions to reproduce for me to fix the bug.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
