### ISSUE TITLE
[BUG] Teams/Allies can Attack on Another

### ISSUE THREAD

**Issue by KingClark316** [booksaw/BetterTeams#362]
### What is the bug?

Currently, the plugin works great in my default worlds overworld, nether, and end. However, in a separate world with multiverse core, I have my KOTH set up. In this world, players of the same team, or allies, can attack one another even if they have PvP disabled. 

### Expected Behaviour

I would like it to sync with the main world, and disable PvP for that team and allyship if they have it disabled, or just make it so that cannot ever hit each other entirely if need be.

### How to Reproduce

No real steps, just happens as you play, not off of a command or anything.

### Output of /teama version

![2022-08-01_15 07 03](https://user-images.githubusercontent.com/110425343/182237778-7c289d76-c984-46ff-9d53-62e38c3b438e.png)

**Comment by booksaw** [comment]
As communicated on discord, this is some implementation issue
