### ISSUE TITLE
/team baltop and other team stats commands are not working [BUG] 

### ISSUE THREAD

**Issue by NotTIG** [booksaw/BetterTeams#363]
### What is the bug?

So my issue is when player/operators run /team baltop (I've also heard other team stats commands don't work, but I can't say for sure) I've tried using the rebuildLookup fix, but it still does not work.

### Expected Behaviour

The commands should work fully without creating errors.

### How to Reproduce

I'm not sure, I have a server with I think over 1.6k teams saved which could be the issue

### Error message

[latest (15).log](https://github.com/booksaw/BetterTeams/files/9243340/latest.15.log)
There is my full log.

### Output of /teama version

teama version
[15:00:32 INFO]: [WARACONS TEAMS] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[15:00:32 INFO]: [WARACONS TEAMS] Minecraft Version: git-Purpur-1747 (MC: 1.19.1)
[15:00:32 INFO]: [WARACONS TEAMS] Current plugin version: 4.4.1

### Additional Information

I think that's all I need to share. Hope it gets fixed soon, love the plugin!

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
