### ISSUE TITLE
[BUG] Hologram Leaderboard

### ISSUE THREAD

**Issue by KingClark316** [booksaw/BetterTeams#364]
### What is the bug?

Setting up Leaderboard Hologram, I would like it to be based off of the teams balance. In the support discord I was told that the first place rank is 0, and when I input that, it show's the full line of code as the hologram rather than the information it should be displaying. It only happens when I rank it at 0. Not only this, the placeholder of %betterTeams_position_name_{rank}% displays the rank in terms of score, or kills. I believe that this may be causing the issue, and that the rank does start at 1 instead of 0.

### Expected Behaviour

I would like the display the top 10 teams in terms of balance, and their balances in a hologram.

### How to Reproduce

1. Create a hologram using Decent Holograms
2. To set it to rank 0, enter the command /dh l set (hologram name) (page) (line) %betterTeams_position_name_0% %betterTeams_position_balance_0%

### Output of /teama version

![2022-08-02_16 12 17](https://user-images.githubusercontent.com/110425343/182464617-f02727c8-c913-4dc6-a68b-b21a83768d46.png)

**Comment by booksaw** [comment]
That placeholder is 1 indexed instead of being 0 indexed.
the first team details is got by doing:  %betterTeams_position_name_1%.
Let me know if you have any other issues.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
