### ISSUE TITLE
[BUG] When player joins a team it doesn't change on tablist unless op

### ISSUE THREAD

**Issue by Khaogamermain01** [booksaw/BetterTeams#367]
### What is the bug?

When a player joins the team it doesn't change it on the tablist and above the player's name until the player rejoins which isn't too good.

### Expected Behaviour

When a player joins the team it should change on the tablist and above the player's name.

### How to Reproduce

Make a player join the team and check the tablist of the players name (without op)

### Output of /teama version

[BetterTeams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[BetterTeams] Minecraft Version: git-Purpur-1735 (MC: 1.19)
[BetterTeams] Current plugin version: 4.4.1

Also "Paste the output of /teama veresion here".

### Additional Information

All you need to remove these lines.
https://github.com/booksaw/BetterTeams/blob/master/src/main/java/com/booksaw/betterTeams/events/MCTeamManagement.java#L54

**Comment by booksaw** [comment]
To display the team name above the player's head and the other features in the Minecraft teams section of the config to work there must be no other plugins on the server which put players within Minecraft teams as this will cause conflicts with better teams.
There are two ways of fixing this: 
1. Remove the offending plugin
        * To figure out what plugin it is, firstly remove any plugin that interacts with the tab menu
        * If that does not work, try removing
2. Get a tab plugin that supports PlaceholderAPI and use the placeholder betterteams_name to display the team name.
        * You must set useTeams to false in betterteams/config.yml
        * An example from a google search of such a plugin is linked below. As a disclaimer I have not tested this plugin nor do I know how it works, so if you need support contact the developer of that specific plugin
        * https://www.mc-market.org/resources/20631/

Let me know if this does not fix the issue

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
