### ISSUE TITLE
[BUG] PermissionLevels not showing up

### ISSUE THREAD

**Issue by bindro1234** [booksaw/BetterTeams#369]
### What is the bug?

The as so stated in the config Permission Levels are not working as intended or I'm not using them correctly. If you go into the Betterteams config and scroll a bit down you will see 'Levels' if you scroll a bit more down you can find the stated line. When I go into the luck perms editor and type "`betterteams.limit" nothing shows up. I already tried: Restarting the server, Relaunching the luck perms editor, Deleting and reinstalling the config, Updating the version and checking console for errors. I can't seem to find the problem. Is this a bug or am I using the plugin incorrectly

### Expected Behaviour

It would be really helpful if there could be a fix to this issue. Or just someone to explain to me how to fix this. 

### How to Reproduce

1. Go into config
2. Scroll down to 'permissionLevels'
3. Put it on true
4. Use a permission plugin and type: betterteams.limit

### Output of /teama version

![image_2022-09-02_104418761](https://user-images.githubusercontent.com/54630550/188100970-c604aa13-ee51-4d4a-b572-3ea40c94d7c1.png)
Minecraft version: git-Paper-387 (MC: 1.18.2)
Plugin version: 4.4.1

**Comment by booksaw** [comment]
If you are referencing Luckperms not recognizing the permission node, nothing can be done about that. 
If you award a player with the permission node `betterteams.limit.10` as an example, even though luckperms will not autocomplete the permission node or give a description, but it should all still work. Let me know if you have any further issues.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
