### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by CatInSuit** [booksaw/BetterTeams#370]
### What is the bug?

![BugImage](https://user-images.githubusercontent.com/112764700/188273252-c4e0d943-38c9-4868-bf2a-6a4e299f63b0.PNG)
If i set the info message (messages.yml) to empty a message will still be sent

### Expected Behaviour

make the message not being sent (maybe if statement if string is empty or something)

### How to Reproduce

1. Set an info message in messages.yml to blank
2. go into minecraft
3. run the command /team info <teamname>

### Output of /teama version

Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
Minecraft Version: git-Paper-411 (MC: 1.17.1)
Current plugin version: 4.4.1

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
