### ISSUE TITLE
[BUG] Some placeholders don't work

### ISSUE THREAD

**Issue by cocoterooo** [booksaw/BetterTeams#371]
### What is the bug?

Placeholders used when the player is not on any team do not work.

I need help please

![image](https://user-images.githubusercontent.com/87582495/188325236-d23aef45-d042-4b99-87bd-c42003c792f2.png)

### Expected Behaviour

.

### How to Reproduce

.

### Error message

.

### Output of /teama version

.

### Additional Information

.

**Comment by booksaw** [comment]
using Spanish translations. File appears to be reset when server restarts. Likely an issue with translation files.

**Comment by booksaw** [comment]
![image](https://user-images.githubusercontent.com/13976636/188687467-ccb1b3af-13c5-46bd-904b-d2de3bcafea6.png)
there is also a case sensitivity issue with this placeholder

**Comment by booksaw** [comment]
I have fixed the issue with placeholder.notInTeam, the fix will be in the next update.  I cannot reproduce the resetting file issues, they are likely an issue with your server configuration. Try modifying and saving the files while the server is stopped then starting the server.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
