### ISSUE TITLE
[FEATURE] Setting something to '' in messages.yml should prevent the message from being sent.

### ISSUE THREAD

**Issue by RealTriassic** [booksaw/BetterTeams#373]
### What is the feature request for?

Instead of still printing the message as an empty line, please just don't print the message.

**Comment by booksaw** [comment]
Which message is this specifically with, as some messages have this already (such as the info messages)? I'm not sure what other mesages you will be wanting to hide.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
