### ISSUE TITLE
[FEATURE] Allow us to configure whether the full command list is returned when sending an invalid command.

### ISSUE THREAD

**Issue by RealTriassic** [booksaw/BetterTeams#374]
### What is the feature request for?

Currently, BetterTeams will print the entire command list if you get a command wrong such as `/team invi` or `/team ba`, please add a configuration option for it to just send an "Invalid Command" message instead, nothing more.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
