### ISSUE TITLE
[BUG] Unable to use a variable multiple times times in a message.yml line

### ISSUE THREAD

**Issue by risunderrated** [booksaw/BetterTeams#378]
### What is the bug?

Title, what happens when I try to do it is it completely fails to rendedr the value and instead just puts %s.

### Expected Behaviour

I expect to be able to put %s twice in a message,  without it malfunctioning.

### How to Reproduce

Set invite.invite in message.yml to || You have been invited to join %s, use [/team join %s]. to join!

Fails to work

### Output of /teama version

Command doesnt work for some reason

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
