### ISSUE TITLE
[BUG] Team balance

### ISSUE THREAD

**Issue by shaqupl** [booksaw/BetterTeams#38]
**Describe the bug**
After deposit money to team balance when I checked /team bal command it shows weird signs and balance is wrong.

**To Reproduce**
Steps to reproduce the behaviour:
1. /team deposit 10100
2. /team balance

**Expected behaviour**
Shows good balance

**Screenshots**
![image](https://user-images.githubusercontent.com/68109218/105176881-27d3aa00-5b26-11eb-9284-8ad0c629fcd3.png)

**Details**
Please provide the following details about your server set-up:
- git-Paper-393 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- BetterTeams version (3.1.13)

**Additional context**
![image](https://user-images.githubusercontent.com/68109218/105177028-58b3df00-5b26-11eb-8d5b-316c5f3a332e.png)

**Comment by shaqupl** [comment]
[messages.zip](https://github.com/booksaw/BetterTeams/files/5843923/messages.zip)
Bug appears even when I did not change anything in config, messages etc. I've read #37 and it's the same. I also have polish złoty currency since first install. Could It be something with geo location?

**Comment by booksaw** [comment]
This error gets stranger and stranger. Ill figure out a way of solving it :)

**Comment by booksaw** [comment]
On another note, I notice that you have a translated version of messages.yml, if you are interested in that version of messages.yml being publically available could you join my discord server here: https://discord.gg/JF9DNs3 and check the #anouncements channel.
I am interested in this as I am aware of many servers that have all had to manually translate their messages.yml file, and if community translations are already available, it will make their life easier.
