### ISSUE TITLE
[BUG] /team create doesn't charge any money

### ISSUE THREAD

**Issue by FreddyAndriu** [booksaw/BetterTeams#381]
### What is the bug?

It doesn't charge players money when doing /team create 

![image](https://user-images.githubusercontent.com/115118007/194169884-20fc90f7-f030-4f78-b81a-40780718db35.png)

![image](https://user-images.githubusercontent.com/115118007/194170034-2e586de1-6799-4ffa-b332-c3b4656d9bfb.png)

### Expected Behaviour

Fix so that /team create interacts with vault to charge money for the command

### How to Reproduce

run /team create 
set in config:
costs:
  - create:50

### Error message

no error message

### Output of /teama version

4.5.0

**Comment by booksaw** [comment]
Hi, you may not be aware that there is a bypass permission node `betterteams.cost.bypass` which means the player bypasses the command cost so it is not taken from that user.

I have tested while not being oped and the expected result occurs for me. Please reopen this issue or make a new issue if you continue having issues.
