### ISSUE TITLE
[BUG] I can't invite people to the team

### ISSUE THREAD

**Issue by alechretien16** [booksaw/BetterTeams#382]
### What is the bug?

Hello!
The problem is that I can't invite people to a team, it's only possible to join if I use /team open, and people join with /team join <name>.

### Expected Behaviour

Replacing McMMO parties with this, BetterTeams seems much better to me, and it is!

### How to Reproduce

1. /team invite.

### Error message

"Equipo lleno, se requiere expulsar a alguien para invitar a otro jugador."

### Output of /teama version

4.5.0

### Additional Information

The way around this is to use /team open, and have users join with /team join.
It also doesn't happen if I do it as an OP.

Server software: git-Purpur-1814 (MC: 1.19.2)*

**Comment by alechretien16** [comment]
[config.zip](https://github.com/booksaw/BetterTeams/files/9719355/config.zip)

**Comment by booksaw** [comment]
in config.yml you have permission levels enabled
![image](https://user-images.githubusercontent.com/13976636/208148652-ab09579f-23db-4b97-a2e6-0dbf64b94b0e.png)
this means that the number of users a team can have is dictated by a permission node awarded to an owner of that team. 

Also I am a little confused as if you open the team with "/team open" and a player tries to join that team, they still get an error saying they cannot join it
