### ISSUE TITLE
[BUG] Disbanding the team will not get rid of the team from teams.yml.

### ISSUE THREAD

**Issue by DaddyRobLIVE** [booksaw/BetterTeams#384]
### What is the bug?

Disbanding the team will not get rid of the team from teams.yml/
I have to manually remove it for others to take that name.

### Expected Behaviour

Disbanding a team should get rid of the team from teams.yml so other players can take the team name.

### How to Reproduce

1. Make a team
2. Disband the team
3. Create another team with the same name
4. Error "That name is already taken"

### Output of /teama version

4.5.0

**Comment by booksaw** [comment]
I am unable to recreate this bug, please see the screenshot below. There used to be a bug to this nature, but it has been patched so please ensure you have updated the plugin to the latest version, then set `rebuildLookups` to true in config.yml and restart your server, this should make everything function as expected.

![image](https://user-images.githubusercontent.com/13976636/208151117-82793100-5689-4ada-97e3-e9803b899d48.png)

If you encounter more issues please reopen this bug report or make a new one.

**Comment by DaddyRobLIVE** [comment]
I'll try this one. Thank you.
