### ISSUE TITLE
[BUG] Can't kick team member that is offline

### ISSUE THREAD

**Issue by DaddyRobLIVE** [booksaw/BetterTeams#387]
### What is the bug?

Can't kick a team member if the player is offline.

### Expected Behaviour

Can kick a team member even if offline.

### How to Reproduce

1. Wait for a team member to go offline
2. Do /team kick <name>

### Output of /teama version

4.5.0

**Comment by booksaw** [comment]
I am unable to reproduce this bug as shown in the screenshot before, this occurs as expected. 
If you are still encountering this bug, please make a new bug report or reopen this one with full info about /teama version (such as spigot version, as some spigot versions are known to have issues processing offline players)

![image](https://user-images.githubusercontent.com/13976636/208155964-d8d225c9-6b13-4c10-a4e9-5f47336d9a71.png)

**Comment by DaddyRobLIVE** [comment]
![image](https://user-images.githubusercontent.com/109517972/210506384-0812b8ab-59b5-49a9-bbe4-e22dc84bd02d.png)
Can't kick offline bedrock users (geysermc)

**Comment by AjMaacc** [comment]
> ![image](https://user-images.githubusercontent.com/109517972/210506384-0812b8ab-59b5-49a9-bbe4-e22dc84bd02d.png) Can't kick offline bedrock users (geysermc)

Having the same issue on my end as well. Java players can be kicked when offline, but not bedrock/geyser players.

**Comment by booksaw** [comment]
@AjMaacc @DaddyRobLIVE geyser is not supported server software, it is very buggy for some things, an example is offline players are not handled the same as Spigot. Any bugs you encounter while using gayser will not be fixed unless you can show they occur when using spigot / paper.
