### ISSUE TITLE
[FEATURE] Members Online Placeholder

### ISSUE THREAD

**Issue by ItzFlibat** [booksaw/BetterTeams#389]
### [FEATURE] New Online Members Placeholder

Make a '%betterTeams_members_online%' Placeholder it does the same thing as '%betterTeams_members_<team>_online%' but it shows the team that the player is currently instead of the placeholder being set on one team.

### Relevant links

https://github.com/booksaw/BetterTeams/wiki/PlaceholderAPI

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
