### ISSUE TITLE
[BUG] Disconnected from server when /team warp

### ISSUE THREAD

**Issue by LeBestVivi** [booksaw/BetterTeams#391]
### What is the bug?

Get disconnected when /team warp
![image](https://user-images.githubusercontent.com/46608329/207724581-c85fb20a-e5ca-4a3f-b51b-30cc0016ec51.png)

### Expected Behaviour

team warp

### How to Reproduce

/team warp base
then the error appears 
![image](https://user-images.githubusercontent.com/46608329/207724740-e9ce4d1d-8cdc-4d7d-a209-277d7778f651.png)

### Error message

Internal Exception: [io.netty.handler.codec.DecoderException:](http://io.netty.handler.codec.decoderexception/)
[java.lang.frr](http://java.lang.frr/) ayIndex0utOfBoundsException: Index 14 out of bounds for length 14

### Output of /teama version

[L&V Teams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[L&V Teams] Minecraft Version: git-Paper-328 (MC: 1.19.3)
[L&V Teams] Current plugin version: 4.5.0

**Comment by booksaw** [comment]
This bug is some issue with the specific team data being stored. please provide the console error message for me to give more support.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
