### ISSUE TITLE
[BUG] spark reported that betterTeams too many threads,It causes the server tps to be too low

### ISSUE THREAD

**Issue by Tanloon** [booksaw/BetterTeams#396]
### What is the bug?

1. spark reported that betterTeams too many threads,It causes the server tps to be too low
report: https://spark.lucko.me/kMt7RgKUgd

2. when i stop the server ,the server log show that: [18:22:53 INFO]: [BetterTeams] Disabling BetterTeams v4.5.0
and it stuck all the time, i have to force total thread shutdown, this will make my server rollback
![image](https://user-images.githubusercontent.com/28031087/212467492-282791f7-17f0-4a43-b62d-aed6201cf2ef.png)

### Expected Behaviour

fix this bug.
In my opinion, it may be caused by database connection

### How to Reproduce

It's hard to say.
This happens when my server runs for a period of time

### Output of /teama version

4.5.0

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
