### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by iavengetheweak** [booksaw/BetterTeams#4]
**Is your feature request related to a problem? Please describe.**
No real problem, more of a desire for more control over the format of messages given to the user upon executing BetterTeams commands

**Describe the solution you'd like**
I would like the option to change the way larger portions of text are shown in a more hierarchy format.  Such as /team info instead of displaying information line by line, possible putting the everything but the name inside a indented area.  I could very well not understand how to use the message.yml file and you have already solved my request.

**Describe alternatives you've considered**
Alternative would be to change the display from the developers end without giving users additional control over message format.

**Additional context**

**Comment by booksaw** [comment]
Thank you for the request. This feature has already been suggested and is being developed for version 3.0.7.
