### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by BlainBurns** [booksaw/BetterTeams#40]
**Is your feature request related to a problem? Please describe.**
I'm running a server with your plugin and the only complaint i get is the fact that people cant turn off the no team pvp

**Describe the solution you'd like**
Is it at all possible to add a command anyone with high authority in a team could use to turn off pvp protection in their group?

**Comment by booksaw** [comment]
This will be added in the next update

**Comment by BlainBurns** [comment]
fantastic

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update.
