### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by Edekoo10** [booksaw/BetterTeams#404]
**Language the issue is about**
- Polish language
**Details about request**
Are you providing translations to a new language, or updating a current one? 
- updating a current
**Translations**
Either provide any relevant translations below or attach the messages.yml file
https://drive.google.com/file/d/1nxg03-yY05rhvqNGvXmyTviS0AHRod4A/view?usp=share_link
**Discord name** 
Provide if you want to get a special rank on the discord server
Edekoo#2918

mistakes are minor like:
![image](https://user-images.githubusercontent.com/110495326/217317039-80e26de8-0b97-4199-8688-8fa8c94a3773.png)
corrected:
![image](https://user-images.githubusercontent.com/110495326/217317258-93788da5-a79f-4552-882c-fd5e5cb505e6.png)

**Comment by Edekoo10** [comment]
Please add command /teamadmin resetrank [nickname]

A very helpful option

**Comment by booksaw** [comment]
Thank you for the provided translation correction. It will be included in the next update


> Please add command /teamadmin resetrank [nickname]
> 
> A very helpful option

Please could you make a separate request for any requested features
