### ISSUE TITLE
[BUG] /team leave

### ISSUE THREAD

**Issue by jadeisalone** [booksaw/BetterTeams#405]
### What is the bug?

it says when im doing /team leave and I am the owner how to fix?
`something went wrong white executing that command please report it to your server owner`

### Expected Behaviour

give me a respond asap

### How to Reproduce

/team leave

### Error message

something went wrong white executing that command please report it to your server owner

### Output of /teama version

latest version

**Comment by booksaw** [comment]
An error message will exist in the console, please could you share that here for me to be able to diagnose the problem.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
