### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SAKDEL** [booksaw/BetterTeams#407]
### What is the bug?

team echest getting reset when a team logs off

### Expected Behaviour

fix it idk

### How to Reproduce

/team echest

### Error message

na

### Output of /teama version

na

### Additional Information

When a team logs off with stuff in its echest the chest gets reset

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
