### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Edekoo10** [booksaw/BetterTeams#408]
### What is the feature request for?

Please add command /teamadmin resetrank [nickname]

A very helpful option

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This can be done using `/teama setrank <team> <rank>`  (this may have been added since this ticket was made, I'm just clearing up old tickets at the moment)
