### ISSUE TITLE
Adding @a and @p to the  "/teama score add" command

### ISSUE THREAD

**Issue by IGDT** [booksaw/BetterTeams#41]
**Is your feature request related to a problem? Please describe.**
I want to use a custom point system for my mob pve event. I can't make that work now apparently.
**Describe the solution you'd like**
Added @p and @a in the command possibilities
**Describe alternatives you've considered**

**Additional context**

**Comment by booksaw** [comment]
This will be added in the next update

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update.
