### ISSUE TITLE
[BUG] Database Timeout

### ISSUE THREAD

**Issue by Edekoo10** [booksaw/BetterTeams#410]
### What is the bug?

i am using mariadb database

### Expected Behaviour

Improved database connection

### How to Reproduce

Connect the server to the database and leave it for a long time after which it starts to happen

### Error message

[logsbug.txt](https://github.com/booksaw/BetterTeams/files/10756899/logsbug.txt)

### Output of /teama version

4.6.2

**Comment by booksaw** [comment]
@Edekoo10 
as shown by below line, autoReconnect is already set to true as mentioned in the line: https://github.com/booksaw/BetterTeams/blob/a582cd71fa3a865ad32ece50a4f31cd350daa718/src/main/java/com/booksaw/betterTeams/database/api/Database.java#L60 

Do you encounter this issue when using a mySQL database as that is the database type I have tested with?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
