### ISSUE TITLE
[FEATURE] i wanna ban some team colors 

### ISSUE THREAD

**Issue by adalmo** [booksaw/BetterTeams#414]
### What is the feature request for?

hmm like when someone tried to set their teamname as dark it's really hard to see it on chat and tablist at night time

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
