### ISSUE TITLE
[BUG ] Extend API

### ISSUE THREAD

**Issue by PincerPrithu** [booksaw/BetterTeams#417]
### What is the feature request for?

Hey, just a quick feature request. I think you know that just a team plugin is not very useful by itself except on vannila style servers. However, if the API could be extended, the plugin could be used as a library and greatly aid in  development of other plugins.

Some things that could be added are:
- Check if player is in team
- Check if team exists
- Get an array of the people in a team
You get the idea!

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by PikaMug** [comment]
This should also include Bukkit Events so [Unite](https://www.spigotmc.org/resources/unite.95217/) can support it.

**Comment by booksaw** [comment]
@PikaMug the plugin provides an Events API, you can read more about it on the API wiki page: https://github.com/booksaw/BetterTeams/wiki/API

@PincerPrithu though the code is not well documented all of what you listed is possible.
To address the mentioned issues in order:
1. *Check if player is in team*
As detailed on the Wiki page, this can simply be done by performing `Team.getTeam(OfflinePlayer player)`. The returned team is the team the player is on, if null is returned then the player is not on a team.

2. *Check if team exists*

This can be done by performing `Team.getTeam(String teamName)`, this will return the team, if it exists, else it will return null.

4. *Get an array of the people in a team*

This can be done after getting the Team object (as detailed on the API wiki page) then performing depending on your specific needs: 
 `team.getMembers().get()` - Get all players on a team
`team.getMembers().getOnlinePlayers()` - Get all online players on a team 
`team.getMembers().getOfflinePlayers()` - Get all offline players on a team

[MemberListComponent](https://github.com/booksaw/BetterTeams/blob/master/src/main/java/com/booksaw/betterTeams/team/MemberListComponent.java) provides all of the functions listed after `team.getMembers()`, I would suggest you check that class and the class it inherits from.

**Comment by PikaMug** [comment]
> @PikaMug the plugin provides an Events API, you can read more about it on the API wiki page: https://github.com/booksaw/BetterTeams/wiki/API

Forgot about this ticket, but I think what I meant to convey was that there doesn't seem to be a CreateTeamEvent.

**Comment by booksaw** [comment]
@PikaMug ok, if you want that added you will have to make a feature request rather than a bug report. I am closing this issue, feel free to open another one if something else comes up.
