### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Ceclon** [booksaw/BetterTeams#42]
Hello, I am here to make a couple of requests.

Ability to change /team to /clan. That would be really useful because most people are used to using the command /clan.

Some sort of team member upgrade. I know you can put in the config the max team size, but it would be a good addition for people to spend in game currency to upgrade the team size.

**Comment by booksaw** [comment]
First suggestion (changing /team aliases) will be added in the next update

Could you create a second feature request for the second suggestion explaining in more detail what you are requesting.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update.
