### ISSUE TITLE
[BUG] Claimed area after Team disband

### ISSUE THREAD

**Issue by Dharuzz** [booksaw/BetterTeams#425]
### What is the bug?

When you disband your team, the claimed area (UltimateClaims) isn't removed.
Have not tested it but please do also check if it changes Claim Owner when transferring Team leadership.

### Expected Behaviour

Claimed area should be dissolved when disbanding the Team.

### How to Reproduce

1. `/team create` Test TST
2. `/c claim`
3. `/team disband` x2
4. ...
5. Claimed area is still there

### Error message

None

### Output of /teama version

![image](https://user-images.githubusercontent.com/100977552/226377462-ebb92bbe-cfed-4592-b5f2-e400f0dfe0d4.png)
![image](https://user-images.githubusercontent.com/100977552/226378268-bd05ccf6-50ba-4545-b4de-c4c241e9b0e7.png)

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
