### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yepikaiye** [booksaw/BetterTeams#427]
### What is the bug?

Essentials /back doesn't warp you to your last location when executing /team home command

### Expected Behaviour

If you were to do /team home, the /back command should return you to your previous correct location, it will only /back you to the essential TP's you've made

### How to Reproduce

TP to a player /tpa [name]
Have him accept the tp request /tpaccept
Then do /team home
Try to do /back
It won't return you to the previous location, it will only return you to previous essential teleport locations you've made

### Error message

No error message

### Output of /teama version

![image](https://user-images.githubusercontent.com/64907360/226971697-88d781f8-847e-4061-a817-841b07ecba01.png)

**Comment by booksaw** [comment]
@yepikaiye 

See the linked line below, you need to set this to true in the EssentialsX configuration file to be able to use `back` command with teleports triggered by other plugins
https://github.com/EssentialsX/Essentials/blob/bf14b88600601019fb51dd6e6a1524e411e9b339/Essentials/src/main/resources/config.yml#LL603C33-L603C33
