### ISSUE TITLE
[FEATURE] Spam kill protection

### ISSUE THREAD

**Issue by shaqupl** [booksaw/BetterTeams#43]
So there is attacker and victim
Attacker should gain 1 score per kill but if he spam killing the same person he shouldn't get any more point.
Victim also should be protected from spam kill and lose only 1 point if attacker is the same person.
You could add option for setting how much time must pass to gain score or lose score when killing or dying due the same player.
eg.
spam-kill-protection: 3600s

**Comment by booksaw** [comment]
This will need further consideration as I know players want other things from score than that (points lost on death to always work not after a cooldown for example) 
This feature will require an entire score system rework with a new config file for the new score system. 

This is a large project, may not be added in the next update, but will be added in the future.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update.

**Comment by shaqupl** [comment]
I'm very glad to hear that
