### ISSUE TITLE
[BUG] Offline players not being kicked 

### ISSUE THREAD

**Issue by Ender0809** [booksaw/BetterTeams#431]
### What is the bug?

Players are unable to kick / ban players from their team

### Expected Behaviour

Kick the player 

### How to Reproduce

/team kick <player> 
This player is not found

### Error message

[21:12:18 INFO]: MEMBER KodaAmi252  » for what is the vote key?
[21:12:21 INFO]: Ender0809 issued server command: /team kick BlackJackj
[21:12:23 INFO]: duo | MANAGER aqua  » what did you say naruto
[21:12:24 INFO]: dogy_lord lost connection: Disconnected

[NO CONSOLE ERRORS]

### Output of /teama version

![Screenshot 2023-03-26 at 22 13 03](https://user-images.githubusercontent.com/122677056/227804916-e10bdaf5-131f-448a-8e0d-cf29028ed940.png)

### Additional Information

n/a

**Comment by booksaw** [comment]
![image](https://github.com/booksaw/BetterTeams/assets/13976636/ba739fd1-d653-4698-854e-8cedd01401ad)
Testing using the same testing conditions you have given does not demonstrate the bug, please could you provide the exact steps to reproduce this bug from a clean server install.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
