### ISSUE TITLE
[BUG] Dupe Glitch

### ISSUE THREAD

**Issue by Frosty9999** [booksaw/BetterTeams#432]
### What is the bug?

Players are able to macro /team deposit and /team withdraw on the same key making them run simultaneously. This causes the server to lag and duplicate the money their using with this macro. 

### Expected Behaviour

Figure out a way to maybe add a wait timer to these commands. So players can't use them but ever "x amount of minutes" 

(Just a thought maybe)

### How to Reproduce

1. Bind /team deposit and /team withdraw to same key and set the amount for both.
2. Spam this key to cause lag and duplicate the money.

### Output of /teama version

4.6.4 

### Additional Information

https://youtube.com/shorts/-k51YQWC1e0?feature=share

This was not found by me, was directed to me before it occurred with my servers.

**Comment by R00tB33rMan** [comment]
Can confirm this issue.
