### ISSUE TITLE
[FEATURE] Two placeholders

### ISSUE THREAD

**Issue by nisammoro** [booksaw/BetterTeams#438]
### What is the feature request for?

Can you add two placeholders; 

1) Placeholder which will fetch the level of team (which is upgraded by /team rankup)

2) Placeholder which will fetch the bank max limit, how much money can be deposited (maximum)

Thank you.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
