### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by SolineKung** [booksaw/BetterTeams#439]
**Language the issue is about**

**Details about request**
Are you providing translations to a new language, or updating a current one? 

**Translations**
Either provide any relevant translations below or attach the messages.yml file

**Discord name** 
Provide if you want to get a special rank on the discord server

**Comment by booksaw** [comment]
I am assuming this issue was opened accidentally. and so I am going to close it. Please open another issue with details if this was not a mistake.
