### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Ceclon** [booksaw/BetterTeams#44]
Feature request:

I made a post earlier about having clan levels or tears so that users can purchase certain tiers for the team so they could have a bigger team size and other types of perks possibly. For example tier 1 would be the starting tier but tier 2 would be 10k or any amount to purchase and would bring players a bigger 
team size.

Also, when you use the placeholder for the team name. It would be nice to implement a "none" when users aren't in a team so the space isn't left blank wherever you use it such as the scoreboard.

Thank you for reading my request, have a good rest of your day.

**Comment by booksaw** [comment]
The first suggestion will be implemented in the next update. how the leveling system will work etc. is still to be determined, I may be able to make it tie in with the updated scoring system which is currently planned. 

With the placeholder concern, check 'placeholder.noTeam' in messages.yml

**Comment by booksaw** [comment]
TODO: 

- [ ] Update /team info
- [ ] /team rankup
- [ ] Change code for chest limit 
- [ ] Change code for team size limit 
- [ ] /teama setrank

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update.
