### ISSUE TITLE
[FEATURE] New placeholder request.

### ISSUE THREAD

**Issue by LavivaNW** [booksaw/BetterTeams#442]
### What is the feature request for?

I love the plugin but it's missing a few placeholders.
%betterTeams_onlineteamuser%
%betterTeams_teamusers%

%betterTeams_maxsteam%
I want to show maxs members and active members count on scoreboard.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
#
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
