### ISSUE TITLE
Mysql Lag

### ISSUE THREAD

**Issue by xF3d33** [booksaw/BetterTeams#447]
### What is the bug?

The plugin, probably because it doesn't use async in database calls, is causing lag
![image](https://github.com/booksaw/BetterTeams/assets/67204462/56d73496-88e1-4c53-b04c-36cf4473d655)

### Expected Behaviour

no lag

### How to Reproduce

enable mysql and let the server run with 30/40 players

### Output of /teama version

![image](https://github.com/booksaw/BetterTeams/assets/67204462/e47384a8-18bc-4122-8f5b-2fd9a03210f6)

**Comment by booksaw** [comment]
duplicate of #429
