### ISSUE TITLE
[FEATURE] Create team event

### ISSUE THREAD

**Issue by PikaMug** [booksaw/BetterTeams#448]
### What is the feature request for?

Add something like a CreateTeamEvent as mentioned in #417

### Relevant links

https://github.com/booksaw/BetterTeams/tree/master/src/main/java/com/booksaw/betterTeams/customEvents

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
