### ISSUE TITLE
Team ranking icons.

### ISSUE THREAD

**Issue by MasterDev16** [booksaw/BetterTeams#45]
**Is your feature request related to a problem? Please describe.**
I don't like it when my team doesn't have a clear ranking system.

**Describe the solution you'd like**
You can add a system where, if you are promoted once, you get one star as a prefix, promoted twice, two stars and so on. Leader would have the most.

**Describe alternatives you've considered**
You can also just have text as prefixes, although this can quickly lead to long long prefixes.

**Additional context**
Leader prefix: [* * *] [Teamtag] [Name]:
2. Promote : [* *] [Teamtag] [Name]:
3. Promote: [*] [Teamtag] [Name]:
4. Default member:  [Teamtag] [Name]:

**Comment by booksaw** [comment]
Im team chat and ally chat these prefixes are showing, Are you asking for there to be an option for those prefixes to show along with your team name in the main server chat?

**Comment by MasterDev16** [comment]
> Im team chat and ally chat these prefixes are showing, Are you asking for there to be an option for those prefixes to show along with your team name in the main server chat?

Yes, in main server chat. But also with more detailed and custom icons, like ✫✫✫. It would be nice to have an option in config where you can set those icons. Like Leader has ♕. 2xpromo got: ♔ and normal rank got: ♢.

**Comment by booksaw** [comment]
> > Im team chat and ally chat these prefixes are showing, Are you asking for there to be an option for those prefixes to show along with your team name in the main server chat?
> 
> Yes, in main server chat. But also with more detailed and custom icons, like ✫✫✫. It would be nice to have an option in config where you can set those icons. Like Leader has ♕. 2xpromo got: ♔ and normal rank got: ♢.

In messages.yml you can change the label for each type of member 

An option to display this in the main server chat will be added in the next update.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. 

To add the team rank to the go to prefixSyntax in messages.yml and add the correct [placeholderAPI placeholder](https://github.com/booksaw/BetterTeams/wiki/Dependencies)
