### ISSUE TITLE
Adding placeholders in chat messages before teams

### ISSUE THREAD

**Issue by ZeeceMC** [booksaw/BetterTeams#452]
### What is the feature request for?

Perhaps making it so you can edit where the team prefix goes in the chat, along with using placeholders.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This can already be done using placeholderAPI. See the wiki page for more information: https://github.com/booksaw/BetterTeams/wiki/PlaceholderAPI
