### ISSUE TITLE
[BUG]  &id001 being inserted into config files

### ISSUE THREAD

**Issue by KYATAPsan** [booksaw/BetterTeams#455]
### What is the bug?

Bug: ranks of placeholders are not displayed

### Expected Behaviour

We would like to utilize better team's placeholder API to display the team's ranking.

### How to Reproduce

Enter the rank placeholder in the plugin called Command Panel.
Open the command panel you created.
Next, an error statement will be triggered and the panel will not open.

### Error message

UNABLE TO READ TEAM DATA FROM plugins/BetterTeams/teamInfo/ac39678d-c1a4-4fb6-8bc9-78e404636b8a.yml.

### Output of /teama version

[18:06:47 INFO]: [BetterTeams] Minecraft Version: git-Paper-545 (MC: 1.19.4)
[18:06:47 INFO]: [BetterTeams] Language Selected: messages
[18:06:47 INFO]: [BetterTeams] Current plugin version: 4.6.4

**Comment by booksaw** [comment]
I have been unable to reproduce this bug, could you please provide steps on how to reproduce this bug from a clean install of BetterTeams.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
