### ISSUE TITLE
Baltop Holo sorts after score not balance.

### ISSUE THREAD

**Issue by MasterDev16** [booksaw/BetterTeams#46]
**Describe the bug**
Baltop Holo sorts after score not balance.

**To Reproduce**
Steps to reproduce the behaviour:
/teama holo create baltop

**Expected behaviour**
Display the team with the most balance at the top

**Screenshots**
![image](https://user-images.githubusercontent.com/57544728/105834405-b767d580-5fca-11eb-8982-4a12a64e395b.png)
https://cdn.discordapp.com/attachments/728527914630643785/803573505563033600/unknown.png

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
- BetterTeams version (found by running /version BetterTeams): 
Paper-405
BetterTeams-3.1.13

**Additional context**

**Comment by booksaw** [comment]
This bug will be fixed for the next update.

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update
