### ISSUE TITLE
[FEATURE] New placeholder %betterTeams_money_limit%

### ISSUE THREAD

**Issue by Izanaagii** [booksaw/BetterTeams#461]
### What is the feature request for?

In addition to %betterTeams_money% returning the balance, why not adding a %betterTeams_money_limit% returning the maximum balance per level ? It would be nice for custom CUI or informations

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
this has been added under `%betterteams_maxmoney%`
