### ISSUE TITLE
[FEATURE] Virtual chest

### ISSUE THREAD

**Issue by Izanaagii** [booksaw/BetterTeams#462]
### What is the feature request for?

A /team chest command opening a chest where everyone in the team can access (like others plugins like AdvancedClans offer)
In addition, why not adding multiple pages to make it more exciting?

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This already exists via the command /team echest.
There are not several pages though.

**Comment by booksaw** [comment]
Duplicate of #316
