### ISSUE TITLE
[FEATURE] New placeholder %betterTeams_level%

### ISSUE THREAD

**Issue by Izanaagii** [booksaw/BetterTeams#463]
### What is the feature request for?

Everything is written in the title, I don't understand how this isn't implemanted yet.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
/
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
