### ISSUE TITLE
[BUG] yaml to sql doesnt work

### ISSUE THREAD

**Issue by sennby** [booksaw/BetterTeams#471]
### What is the bug?

yaml to sql doesnt work

### Expected Behaviour

for it to convert

### How to Reproduce

change to sql

### Output of /teama version

newest

**Comment by sennby** [comment]
https://discord.com/channels/295271438112522241/728527914630643785/1125191727125381260

**Comment by sennby** [comment]
https://gyazo.com/8dc20c082b1c02b9f4e55ec38e4976ae

**Comment by sennby** [comment]
https://mclo.gs/JxrCsSr

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
