### ISSUE TITLE
[BUG] All placeholders need a non-null sender even if it its not used

### ISSUE THREAD

**Issue by Aeliios** [booksaw/BetterTeams#473]
### What is the bug?

Placeholders such as %betterTeams_position_etc% need a online sender, which is not required.

### Expected Behaviour

Return good value, even with a null sender.

### How to Reproduce

/papi parse --null %betterTeams_position_name_1% -> returns "" instead of team's name.

### Output of /teama version

[BetterTeams] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[BetterTeams] Minecraft Version: git-Paper-55 (MC: 1.20.1)
[BetterTeams] Language Selected: messages
[BetterTeams] Current plugin version: 4.6.7

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
