### ISSUE TITLE
[BUG] Could not leave / kick / disband team

### ISSUE THREAD

**Issue by Cr7os** [booksaw/BetterTeams#476]
### What is the bug?

When running the command /team leave, or /team kick or /team disband 
A error command would pop saying to report it to server owner. 

### Expected Behaviour

Player supposed to be able to leave team or disband in by usual.

### How to Reproduce

1. Run command /team leave 
2. - [Wed 02:56:35 ERROR Minecraft] Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose

### Error message

- [Wed 02:56:17 ERROR Minecraft] Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
! [Wed 02:56:17 WARN ] java.lang.IllegalStateException: Unregistered scoreboard component
! [Wed 02:56:17 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:403)
! [Wed 02:56:17 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftTeam.removeEntry(CraftTeam.java:261)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:91)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:63)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:662)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:648)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
! [Wed 02:56:17 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
 
! [Wed 02:56:17 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
! [Wed 02:56:17 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
! [Wed 02:56:17 WARN ]     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
! [Wed 02:56:17 WARN ]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
! [Wed 02:56:17 WARN ]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
! [Wed 02:56:17 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
  [Wed 02:56:22 INFO  Server/PlayerConnection] Hiroisalive issued server command: /msg HackerMgL do /team leave
  [Wed 02:56:27 INFO  Server/PlayerConnection] HackerMgL issued server command: /r not working
  [Wed 02:56:28 INFO  Server] [Not Secure] [Killers] <HackerMgL> ,
  [Wed 02:56:35 INFO  Server/PlayerConnection] HackerMgL issued server command: /team leave Killers
- [Wed 02:56:35 ERROR Minecraft] Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
! [Wed 02:56:35 WARN ] java.lang.IllegalStateException: Unregistered scoreboard component
! [Wed 02:56:35 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:403)
! [Wed 02:56:35 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftTeam.removeEntry(CraftTeam.java:261)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:110)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.events.MCTeamManagement.remove(MCTeamManagement.java:91)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.team.MemberListComponent.remove(MemberListComponent.java:63)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:662)
 
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.Team.removePlayer(Team.java:648)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.commands.team.LeaveCommand.onCommand(LeaveCommand.java:26)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.commands.presets.TeamSubCommand.onCommand(TeamSubCommand.java:39)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:72)
! [Wed 02:56:35 WARN ]     at BetterTeams.jar//com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:59)
! [Wed 02:56:35 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
! [Wed 02:56:35 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
! [Wed 02:56:35 WARN ]     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
! [Wed 02:56:35 WARN ]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
! [Wed 02:56:35 WARN ]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
! [Wed 02:56:35 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)

### Output of /teama version

4.6.7

### Additional Information

.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
