### ISSUE TITLE
[BUG] YAML to SQL doesn't work not fixed.

### ISSUE THREAD

**Issue by sennby** [booksaw/BetterTeams#478]
### What is the bug?

YAML to SQL doesn't work not fixed.

### Expected Behaviour

YAML > SQL

### How to Reproduce

Change to sql from yaml

### Error message

https://mclo.gs/rFtXS9Y

### Output of /teama version

Its the latest that said the issue was fixed in. (downloaded today) 4.7.1

**Comment by booksaw** [comment]
This may be fixed, if it is not I have improved the error message that will be thrown to include additional information that can be used to trace the error, let me know if this error occurs when you try the conversion in the next update so I can trace the error in more detail.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
