### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ttt0** [booksaw/BetterTeams#495]
### What is the bug?

team e chest bug

### Expected Behaviour

to fix the error

### How to Reproduce

the plugin opens and it goes like this

### Error message

https://hastebin.com/share/ucesapewek.swift

### Output of /teama version

![image](https://github.com/booksaw/BetterTeams/assets/66686400/c4a8ccb2-b94d-498a-8c80-6b21eaab852f)

**Comment by booksaw** [comment]
As mentioned when initially making the bug report, please post the error directly rather than using hastebin / pastebin, else the paste will expire and I will not be able to fix the bug.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
