### ISSUE TITLE
[FEATURE] TEAMMATES HEALTH PLACEHOLDER

### ISSUE THREAD

**Issue by dogedani** [booksaw/BetterTeams#498]
### What is the feature request for?

Add a <type> variable in placeholder whose function is to show the health of teammates

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
Would this show the average health of the players on the team or do you have an idea on how to do it on a per-player basis?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
