### ISSUE TITLE
[FEATURE] ONLY SHOW TEAMMATES NICKNAMES PLACEHOLDER

### ISSUE THREAD

**Issue by dogedani** [booksaw/BetterTeams#499]
### What is the feature request for?

In the placeholders there is already a <type> variable that does this but it also shows the player himself. I would like you to add a way to only show his teammates. Thanks.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
Hi, which placeholder are you referencing?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
