### ISSUE TITLE
prefix bug

### ISSUE THREAD

**Issue by jaydengogogo** [booksaw/BetterTeams#502]
[###]([url](url)) What is the bug?

After 5 minutes I create a team, I can not see the team prefix when I f5.

### Expected Behaviour

I want to now the bug is able to correct in config.yml

### How to Reproduce

?

### Error message

?

### Output of /teama version

[EGG WAR] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[EGG WAR] Minecraft Version: git-Paper-550 (MC: 1.19.4)
[EGG WAR] Language Selected: messages
[EGG WAR] Current plugin version: 4.8.1

### Additional Information

![스크린샷(10)](https://github.com/booksaw/BetterTeams/assets/144572566/c2dd3bc0-6cb5-422a-9aae-d56bc2dbee4c)
![2023-09-10_11 42 07](https://github.com/booksaw/BetterTeams/assets/144572566/95319763-9668-4cda-8395-67a39351b446)

**Comment by jaydengogogo** [comment]
'팀' is team in korean at the scoreboard

**Comment by booksaw** [comment]
This is caused by a plugin conflict, please see this link for more information: https://github.com/booksaw/BetterTeams/wiki/Managing-the-TAB-Menu

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
