### ISSUE TITLE
[BUG] Typo in betterteams `messages.yml` EN

### ISSUE THREAD

**Issue by Ceymikey** [booksaw/BetterTeams#503]
### What is the bug?

While I was translating betterteams I have noticed a typo:

Found: `You team home could not be found`
Correct: `You're team home could not be found`

### Expected Behaviour

To fix this typo its not really that big of an issue.

### How to Reproduce

1. Enter the files
2. Search specific `messages.yml`
3. Line `120`: "home.world"
4. Fix the typo
5. `commit and push`

6. (OPTIONAL): Could search for any other near typo's

### Error message

Language bug

### Output of /teama version

Language bug / Just the most recent one.

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
