### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by XH14MZAH3** [booksaw/BetterTeams#514]
### What is the bug?

Says max level is 2 even though in the config there is more than one level

### Expected Behaviour

To fix it

### How to Reproduce

Idk because idk what the problem is

### Output of /teama version

4.8.2

**Comment by booksaw** [comment]
Could you share the levels section of your config, as this is generally an issue with configuration

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
