### ISSUE TITLE
[BUG] Placeholder not working in /team chat

### ISSUE THREAD

**Issue by kokqi** [booksaw/BetterTeams#515]
### What is the bug?

I got a conditional placeholder which somehow doesn't work in the ally/team chat
%changeoutput_equals_input:{betterteams_tag}_matcher:_ifmatch:&7[&fNone&7]_else:&7[{betterteams_tag}&7]%

**PlaceHolderAPI**
Expansion that I use for the conditional placeholder:
ChangeOutput

### Expected Behaviour

I'm just expecting to see such a placeholder being accepted

### How to Reproduce

1. Conditional Placeholder doesn't work with Team/Ally Chat 

### Output of /teama version

[Teams] Storage Method: 
com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager

[Teams] 
Minecraft Version: 
git-Paper-196 (MC: 1.20.1)
[19:25:25 INFO]: 

[Teams] 
Language Selected: 
messages

[Teams] 
Current plugin version: 
4.8.2

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
