### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by Areanydd** [booksaw/BetterTeams#518]
**Language the issue is about**
Romanian

**Details about request**
Are you providing translations to a new language, or updating a current one? 
New translation language.

**Translations**
Either provide any relevant translations below or attach the messages.yml file
[messages.zip](https://github.com/booksaw/BetterTeams/files/13198372/messages.zip)

**Discord name** 
Provide if you want to get a special rank on the discord server
areanydd

**Comment by booksaw** [comment]
Thanks for your contribution, this new translation will be added in the next update.
