### ISSUE TITLE
Team PVP improvement 

### ISSUE THREAD

**Issue by BlainBurns** [booksaw/BetterTeams#52]
**Is your feature request related to a problem? Please describe.**
I don't know if this is my lack of knowledge or an issue with the plugin but only people with admin powers (who are the leaders of their teams) are able to use /team PVP

**Describe the solution you'd like**
If it isn't just my own stupidity my server members would apreshaite being able to do /team PVP if they have high-rank status in their teams. If it is my own stupidity a feature that would also (though not entirely) fix this issue would be allowing the use of /team PVP with the admin variations of the commands so as an admin I could turn it on or off for them. (as of right now that docent work)

**Comment by booksaw** [comment]
It appears I forgot to setup the permission node correctly, give your default group the permission node `betterteams.pvp` for now. I will fix this properly in the next update.

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update
