### ISSUE TITLE
Add a command to reset all teams money

### ISSUE THREAD

**Issue by RayneBlox** [booksaw/BetterTeams#521]
### What is the feature request for?

Add a command, maybe /team resetmoney or something like that, and it will reset the money of every team in the entire server.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
This will be possible under the command /teama purge <money>
