### ISSUE TITLE
Dissapear vanished poeples from /team invite

### ISSUE THREAD

**Issue by xtomikk** [booksaw/BetterTeams#525]
### What is the feature request for?

Hi, could you please remove the disappeared people from /team invite? So that they don't appear there when they have vanish

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
(to add on as may as well be addressed at the same time, this also happens with /team info)

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.
