### ISSUE TITLE
Kicking offline players

### ISSUE THREAD

**Issue by Czres** [booksaw/BetterTeams#527]
### What is the bug?

I can't kick players from my team if they are offline or aren't in the server. 

### Expected Behaviour

I want it to be fixed . We need to have the right to kick players if they don't play anymore. So that we can play with our friends who currently play.

### How to Reproduce

Add members to your team
Then they will leave the world
Now try kicking them it says specified player don't exist.

### Error message

Specified player not found 

### Output of /teama version

I don't have that access on that server

**Comment by booksaw** [comment]
Hi, I need the /teama version output to be able to make any progress. This is a bug that has been flagged before, but generally is caused by running unsupported server software. Issue #489 is the master issues for this bug to try and determine if there is a pattern between servers.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
