### ISSUE TITLE
[BUG] BetterTeams - entire help menu appears after specific command entered.

### ISSUE THREAD

**Issue by Duffdog15** [booksaw/BetterTeams#528]
### What is the bug?

Requested bug report via dev:

When 'fullycustomhelpmessages: true' in config, and I do a command from the /team menu (e.g. /team create), the whole /team help menu is shown in chat (see image 1) rather than:

![image](https://github.com/booksaw/BetterTeams/assets/153953064/eaf8591b-93cc-4ff7-844c-d40111fb4832)

when 'fullycustomhelpmessages: false', doing /team create will only show the relevant help message (see image 2):

![image](https://github.com/booksaw/BetterTeams/assets/153953064/5123333b-f228-48a0-afc1-c8785baf19c6)

### Expected Behaviour

In dev words, look into it when theres time.

### How to Reproduce

fullycustomhelpmessages : true

/team create

(whole team help menu appears)

### Error message

None

### Output of /teama version

Same applies as /team

**Comment by booksaw** [comment]
@Duffdog15 Out of curiosity, why are you using fullyCustomHelpMessages, I've had a look into the code and I'm not totally sure why they would be used rather than the normal help messages?

**Comment by Duffdog15** [comment]
Hi.I believe at the time I was trying to make it so if I typed in a command with missing arguments like /teams invite, it displayed the corrrct usage of that individual command, rather than listing every help command in the plugin.Sent from my iPhoneOn 31 Jan 2024, at 22:22, James McNair ***@***.***> wrote:﻿
@Duffdog15 Out of curiosity, why are you using fullyCustomHelpMessages, I've had a look into the code and I'm not totally sure why they would be used rather than the normal help messages?

**Comment by booksaw** [comment]
Sorry, I should have been more clear. that is the default behaviour when you set `customHelpMessages` to false. It will only display the help message for the command you have incorrectly entered. 
I am wondering what functionality is missing from the help messages themselves that is causing you to want to be able to customise them even more than you already can?

**Comment by Duffdog15** [comment]
My original query revolves around that. At the time I just wanted the plugin to display the relevant command when it was inputted correctly, rather than displaying every command in the book. Everything else is fine.Sent from my iPhoneOn 1 Feb 2024, at 07:07, James McNair ***@***.***> wrote:﻿
Sorry, I should have been more clear. that is the default behaviour when you set customHelpMessages to false. It will only display the help message for the command you have incorrectly entered.
I am wondering what functionality is missing from the help messages themselves that is causing you to want to be able to customise them even more than you already can?

**Comment by booksaw** [comment]
Oh perfect, I have made some improvements to the normal help message system that will be in the next update. 
When it comes out if you set `fullyCustomHelpMessages` to false and let me know if you find any issues or if there is anything missing, I would appreciate it.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
