### ISSUE TITLE
[FEATURE] Placeholder for team players

### ISSUE THREAD

**Issue by WinterMiller** [booksaw/BetterTeams#529]
### What is the feature request for?

Placeholder for a team players, this would allow for example 

<execute an affect at a person’s team, affecting all members in the current lobby>

[This opens the door to creation of Team items that can be created, which would incentivize using teams] 

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
