### ISSUE TITLE
[FEATURE] Exclamation mark to escape team/ally chat and talk in global

### ISSUE THREAD

**Issue by Mehru1214** [booksaw/BetterTeams#53]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I'm always frustrated when I have to type /team allychat to talk in global, and then having to type it again to go back into ally chat.

**Describe the solution you'd like**
If one could preface their message with an exclamation mark to talk in global chat it would be great. This is very similar to the system used in CubeCraft. This could also be a good way to differentiate between team and allychat too, perhaps by using one ! to go from allychat to team-only chat, and !! to go straight to global chat.

Essentially, if you type normally, the message should go to allychat - "this is a message to allychat"

If you preface with an exclamation mark, the message would go to global - "!this is a message to global chat" (other players wouldnt see the !)

**Comment by booksaw** [comment]
This improvement has been added and will be included in the next update
