### ISSUE TITLE
[FEATURE] Money placeholder formatted?

### ISSUE THREAD

**Issue by Qekker** [booksaw/BetterTeams#535]
### What is the feature request for?

Is it possible for you to make the money placeholder able to be formatted like u can do with vaults? It looks wierd when my players money and the teams money on the scoreboard is different formatted

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This is already possible but will require looking through many of the messages to change it. 
This is to be done in messages.yml, you will need to find the corresponding messages / placeholders you are using and change the money format in them. An example of one of the lines that would need changing can be seen at the link below.
https://github.com/booksaw/BetterTeams/blob/master/src/main/resources/messages.yml#L44

**Comment by Qekker** [comment]
Hey, but if i change the %s in the money. What do i replace it with, all the solutions i could find just made it dissapear.

**Comment by EarthCow** [comment]
What sort of format do you want to change it to? The `%betterteams_money%` placeholder should output whatever format you have here: https://github.com/booksaw/BetterTeams/blob/a949af5371d6d2ce507b73eb45d02d66c1dc0e66/src/main/resources/messages.yml#L22 The %s is replaced with the balance such as "155.36".

**Comment by Qekker** [comment]
I want it to when Its 100000. It just says 100k

**Comment by EarthCow** [comment]
If the balance is 100000 you want it to say 100k? Or is it displaying 100k and you want it to display 100000?

Currently, there is no way to make 100000 appear as 100k.
