### ISSUE TITLE
A new <type> for Placeholder

### ISSUE THREAD

**Issue by DoZysGuy** [booksaw/BetterTeams#537]
### What is the feature request for?

It will be great to return the name of the owner of a team.
Same for admin and members, like onlinelist but here we can for example set the owner of the winner team as npc on spawn before each purge.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
