### ISSUE TITLE
[FEATURE] Current Position Placeholder 

### ISSUE THREAD

**Issue by TheXGuy** [booksaw/BetterTeams#538]
### What is the feature request for?

I'd like 2 placeholders called "%betterteams_position_score%" and "%betterteams_position_balance% to be added. It would display the current position in the score top and balance top leaderboards. For example, it would allow for things like "Your Position: #506 - 2 Points" to be added to leaderboard holograms.

### Additional Information

Something like how: %statistic_player_kills_alltime% is handled would be nice. Where if you're in 5th place then it'll return "5", and if you're in 5,120,109th place, it'll return "5120109" (not sure if it would have commas at 1k or above)

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
