### ISSUE TITLE
[BUG]  Team name not in TAB list 

### ISSUE THREAD

**Issue by Priyansh07777** [booksaw/BetterTeams#540]
### What is the bug?

in my tab list the team name is not showing please help

### Expected Behaviour

kk

### How to Reproduce

kk

### Error message

kk

### Output of /teama version

kk

### Additional Information

please help

**Comment by booksaw** [comment]
Hi, I would suggest you check this wiki page: https://github.com/booksaw/BetterTeams/wiki/Managing-the-TAB-Menu

If not you will need to provide a lot more information about the problem for me to be able to provide support.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
