### ISSUE TITLE
[FEATURE] Translation

### ISSUE THREAD

**Issue by JulekKiwalski** [booksaw/BetterTeams#553]
### What is the feature request for?

When you fully want to translate the plugin, you can't translate some brackets when typed /team. For example, when I want to change <team> to something else, I should be able to do so.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the suggestion.
