### ISSUE TITLE
GET A PAPI PLACEHOLDER

### ISSUE THREAD

**Issue by Q2OD** [booksaw/BetterTeams#561]
### What is the feature request for?

WE NEED IT

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
Hi, can you be more specific with what you are requesting? 
If you were not aware we have already have placeholders: https://github.com/booksaw/BetterTeams/wiki/PlaceholderAPI

If you are requesting a specific placeholder please can you provide information about the placeholder you are after

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
