### ISSUE TITLE
[FEATURE] gui for team list 

### ISSUE THREAD

**Issue by CayanNet** [booksaw/BetterTeams#562]
### What is the feature request for?

like when someone type /team list it shows gui of team lists and click to join the team

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by EarthCow** [comment]
Duplicate of #547

**Comment by booksaw** [comment]
Closing, as this is a duplicate ticket
