### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by KKbutter2281** [booksaw/BetterTeams#569]
### What is the feature request for?

Let us remove or readd prefixes. This way, theres less prefixes.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
Which prefixes are you referencing,
If you are talking about the team name being prefixed in chat messages you can already disable it by setting `prefix` to false in config.yaml

Please could provide examples etc. to make this issue more understandable.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
