### ISSUE TITLE
Problem in the team.yml file

### ISSUE THREAD

**Issue by CODK90** [booksaw/BetterTeams#570]
### What is the bug?

In the team.yml file I have observed that the commas (' ') are disappearing from the cooldown section. Though it should not be the case because in the help page it is specifically written that the commas are required. Please fix this bug. During the server start up it occurs.

### Expected Behaviour

Better Teams is a great plugin and the developer is extremely intelligent a helpful. I hope that in the next update he fixes this bug and all the other bugs that was reported to him. I will wait patiently.

### How to Reproduce

This bug happens when one sets up the team.yml file normally and starts the server and the commas disappear. Although it also works without the commas but I highly doubt the whether the commas are removed when the server starts or before the server stops.

### Error message

No error message. The plugins works as it should be with the commas.

### Output of /teama version

=[00:15:06 INFO]: 
Storage Method: 
com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[00:15:06 INFO]: 
Minecraft Version: 
git-Purpur-2160 (MC: 1.20.4)
[00:15:06 INFO]: 
Language Selected: 
messages
[00:15:06 INFO]: 
Online mode: 
false
[00:15:06 INFO]: 
Player count: 
0
[00:15:06 INFO]: 
Current plugin version: 
4.9.1

### Additional Information

Oh another thing that I observed is 'costFromTeam' when set to false automatically sets to true when the commas are removed. I don't know why because my server does not have an economy yet it happpens.

**Comment by booksaw** [comment]
If the data is not being lost this is not a bug, this is just the weird features of the YAML parser. But thank you for making me aware :)
