### ISSUE TITLE
AutoPurge silently works even if no value is assigned to it. 

### ISSUE THREAD

**Issue by CODK90** [booksaw/BetterTeams#574]
### What is the bug?

In the config file of the plugin there is an option named AutoPurge.  When we set a value like 1:6, it will deduct all scores from all teams at 6 a.m. of every month in Minecraft days. But if no value is assigned to it then also it silently runs. To fix this I had to delete the entire statement. Please fix this issue.

### Expected Behaviour

Better teams is a fantastic plugin nd the developer is ready to help any needy person. I am sure the developer will fix it. Currently the only fix that I have found is to remove the statement entirely.

### How to Reproduce

If in the config it is written autoPurge: and then nothing else then the tick in the Minecraft server can be increased and some score can be set to a temporary team. With time, all the score will be deducted and frequently using /team info helps.

### Error message

No error messages, works silently.

### Output of /teama version

=[12:28:43 INFO]: 
Storage Method: 
com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[12:28:43 INFO]: 
Minecraft Version: 
git-Purpur-2162 (MC: 1.20.4)
[12:28:43 INFO]: 
Language Selected: 
messages
[12:28:43 INFO]: 
Online mode: 
false
[12:28:43 INFO]: 
Player count: 
0
[12:28:43 INFO]: 
Current plugin version: 
4.9.1

### Additional Information

No this was all I can say about the bug. Please fix this bug and Thank You in advance!

**Comment by booksaw** [comment]
This bug has been fixed and the patch will be included in the next update. Thank you for reporting.

I have added an additional config option to ensure this no longer occurs.
