### ISSUE TITLE
[FEATURE] Make some tags blockable for Teams

### ISSUE THREAD

**Issue by CoolAllRounder** [booksaw/BetterTeams#575]
### What is the feature request for?

Like we have some team names which we can Block, we should also be able to block some tags of teams. because otherwise people create tags like "OWNER" , "ADMIN" in teams.

Other than that, please add GUI and Custom interface with custom features like GUILDS Plugin sir. we need that, because current plugin can be added with many many more features. Refer to Guilds plugin. 

### Relevant links

https://www.spigotmc.org/resources/guilds-30-sale.66176/

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
Please keep feature requests to a single topic, I have renamed this one to match the main issue and switched to the bug type.

This would be done by looking at the `blacklist` list for team tags as well as team names to save repitition

**Comment by booksaw** [comment]
Apologies for not highlighting sooner, this is already implemented, add any team names you want banned to the `blacklist` option in config.yml

**Comment by CoolAllRounder** [comment]
Sir what i wanted was not just to blacklist the team names, but to be able
to blacklist the team tags too.
