### ISSUE TITLE
[BUG] Delete teams.yml cache

### ISSUE THREAD

**Issue by NarTwitch** [booksaw/BetterTeams#578]
### What is the bug?

Cannot delete teams.yml cache, I've deleted the whole file, reinstalled the whole plugin, deleted the teams individually, but for some reason they come back everytime.

### Expected Behaviour

Have the teams delete and allow them to be recreated.

### How to Reproduce

1. Have people create teams (ex. RiOT)
2. Attempt to clear the created teams through the teams.yml file
3. Restart server
4. Try to create a team name (ex. RiOT)
5. Error "Team already exists"
6. All the cache comes back even though it was deleted.

### Output of /teama version

theres nothing the teama command can do within this situation, teama disband doesn't work.

**Comment by booksaw** [comment]
Why are you trying to delete teams in the file rather than using the `/teama disband` command. In almost all cases modifying the files directly is not supported.

**Comment by Ceymikey** [comment]
**Hey have you tried the following steps? - Backup files if needed like config**

1. **Stop** your server and remove teams.yml and the betterteams jarfile.
2. **Start** your server without anything betterteams related so no jar.
3. After doing that **stop** the server again, re-add the jar file and start your server up.

The initial key here should be starting the server without the jar to whipe its data,

Your servers disk data for betterteams should now be reset and all teams can be recreated using its command.
Hope this helped!

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
