### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JaredHathaway** [booksaw/BetterTeams#579]
### What is the bug?

I am dealing with an issue that goes like this "i have the /team chat toggle set to true, but idk why in-game that the members messages are still sent to global even if they toggled to team chat, they can do the /team chat (message) tho"

### Expected Behaviour

when I do /team chat it should toggle on and when i type it should go to team chats not global chat

### How to Reproduce

/team chat

### Output of /teama version

![image](https://github.com/booksaw/BetterTeams/assets/166489428/5dec49ec-c49e-47a4-95b7-266a9e7bc6bf)

**Comment by booksaw** [comment]
![image](https://github.com/booksaw/BetterTeams/assets/13976636/c363f716-e45e-48db-8586-8116fa7bb38c)
I have tried to reproduce, but I get the expected behaviour instead of the behaviour you are describing, please can you provide screenshots and more detailed steps to reproduce.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
