### ISSUE TITLE
commands cooldown

### ISSUE THREAD

**Issue by cocomws** [booksaw/BetterTeams#581]
### What is the bug?

here is my team.yml but the cooldown doesnt work
```
# This file is used to determine any /team commands which contain a cooldown or price . NOTE this currently does not work with /teama commands

# COOLDOWNS - Only let a player run a command every set number of seconds. 
# To bypass the cooldown have the permission node betterTeams.cooldown.bypass
# To add a cooldown to this file, an example is shown below
cooldowns:
- 'home: 1800'
- 'warp: 1800'
- 'setwarp: 1800'
- 'sethome: 1800'

# This option determines if the command cost is taken from the team balance first or the individual player
#
# Possible values: [true, false]
costFromTeam: true
```

### Expected Behaviour

make the cooldown work

### How to Reproduce

copy the team.yml file

### Error message

/

### Output of /teama version

Better Teams 4.9.1

### Additional Information

/

**Comment by booksaw** [comment]
You should not have a space between the colon and the number, so instead of
```
cooldowns:
- 'home: 1800'
```
it should be 
```
cooldowns:
- 'home:1800' 
```

Please let me know if the issue persists with this change.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
