### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zasnaz** [booksaw/BetterTeams#6]
Hello
How can I edit the format of prefix In chat
![piccc](https://user-images.githubusercontent.com/66457588/85208357-5a22ec00-b338-11ea-892b-01410a67651e.png)
As you see in the picture 
the team name written in "&b" color and there is a space in front of it 
is there any possibility to edit this ?

**Comment by booksaw** [comment]
Currently, the format for the team prefix is not in messages.yml this will be changed in version 3.0.8

Additionally, I recommend against using /teama reload except to reload the messages.yml file until 3.0.8 as parts of the config file are known to not work with /teama reload (this will be fixed for the next update)

**Comment by zasnaz** [comment]
Thank you

**Comment by booksaw** [comment]
This will be released in version 3.0.8.
