### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by GZSecond** [booksaw/BetterTeams#612]
How can I accurately determine the coordinates of warp homes in the "TeamData" file? I don't understand those number sequences. 😅

**Comment by booksaw** [comment]
Why are you trying to identify coordinates in the actual file? You can use admin commands to teleport to any teams war or home using `/teama warp <team> <warp>` and `/teama home <team>`

**Comment by GZSecond** [comment]
Well thank

Vào 18:46, Th 7, 8 thg 6, 2024 James McNair ***@***.***> đã
viết:

**Comment by GZSecond** [comment]
So in case I can't access the server using the game? I want to be able to
determine without accessing because I don't have much time

Vào 18:47, Th 7, 8 thg 6, 2024 MinecraftPE Acc ***@***.***>
đã viết:

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
