### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by SubToItzMeNinja** [booksaw/BetterTeams#617]
I need help I have uploaded better team plugin on my 1.19.4 server I gave permission to defualt of "betterTeams.standard"
Still they can't access any of cmds of better teams

https://media.discordapp.net/attachments/1251824313099751516/1251824313510920192/Screenshot_20240616_143130.jpg?ex=666ffbbe&is=666eaa3e&hm=90b9f51e3e852f88efd8200f6fcf2b16707f8b0bacaebc80061e15a07fa1d679&

**Comment by booksaw** [comment]
Please can you make a new issue using the bug report format and provide further detail, as currently this is not enough to go on.
Alternatively, you can join the support discord and ask there: https://discord.gg/JF9DNs3
