### ISSUE TITLE
[BUG] Tab menu

### ISSUE THREAD

**Issue by Naufal90** [booksaw/BetterTeams#624]
### What is the bug?

My scoreboard disappeared when installing the betterteams plugin

### Expected Behaviour

Please fix this bug problem

### How to Reproduce

1. I installed the betterteams plugin 2. After I installed it and tried to enter the server suddenly the scoreboard disappeared, when I asked the member on the server he said it suddenly just disappeared.

### Output of /teama version

4.9.4

**Comment by booksaw** [comment]
See this wiki page: https://github.com/booksaw/BetterTeams/wiki/Managing-the-TAB-Menu#conflict
