### ISSUE TITLE
[FEATURE] Shows the status there is a team or not for Placeholder.

### ISSUE THREAD

**Issue by MEGASLIMES** [booksaw/BetterTeams#627]
### What is the feature request for?

Shows the status there is a team or not for Placeholder.
For example, %betterteams_status% will show true if there are teams, and false if there are no teams.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
Hi, I think you are after the %betterteams_inTeam% placeholder. Please let me know if this is not what you are after
