### ISSUE TITLE
Claiming land implementation 

### ISSUE THREAD

**Issue by ovirse** [booksaw/BetterTeams#63]
A lot of people like the option of claiming there precious builds or loot, but hate the faction side of things, by not having the ability to raid claimed land, I think the implementation of claims would take this plug-in to the next level, inviting someone to your team you also trust them to be part of your claim, a really cool idea would be to make it so that players must put items in a chest (diamonds, iron, gold) or even items of choosing in config to maintain the claimed land, the more land they claim the more ores are used and the less time they will have, this gives a player a reason to login and grind everyday to keep there claim stable and safe from other players this also means that when players become inactive your not left with claimed land everywhere, here’s an example of the plug-in that I think would be a great inspiration (ultimateClaims) link:  https://songoda.com/marketplace/product/ultimateclaims-the-ultimate-claiming-plugin.65

**Comment by ovirse** [comment]
https://youtu.be/5rF1hnLNZ0s

**Comment by booksaw** [comment]
I cannot find developer documentation for that plugin, if you are able to please link it. 

Unless documentation can be found I will need to either code my own land claim plugin (very big job) or tie betterteams in with another one. I am going to leave issue at least a week to settle then I will do further research on the avaliable options.

**Comment by ovirse** [comment]
I do not know how to obtain this I suggest you just get a different one or make one that is easy to understand

**Comment by booksaw** [comment]
Someone else in the booksaw development discord managed to get a link to it by asking the plugin owner. 
Im still not sure it is possible with that plugin though. but I will look into it when I get the time

**Comment by ovirse** [comment]
I hope so thank you for looking into it :)

**Comment by booksaw** [comment]
API link: https://github.com/songoda/UltimateClaims/tree/master/src/main/java/com/songoda/ultimateclaims/api/events
This is still in progress

**Comment by booksaw** [comment]
This is being worked on, I need to wait on the developer of the other plugin until I can progress more.
