### ISSUE TITLE
[BUG] Cannot retrieve the list of allies

### ISSUE THREAD

**Issue by svaningelgem** [booksaw/BetterTeams#635]
### What is the bug?

I see how I can ally with a team, but I can't see the requests I sent, nor the teams I've allied myself with.

### Expected Behaviour

some kind of command I guess? "ally list" or so?
But that would disallow a team named "list" 😉

### How to Reproduce

join the server, have 2 teams, ally them... No way that I see to show this list (via the chat)

### Output of /teama version

![image](https://github.com/user-attachments/assets/f7e8c734-ddd1-4262-80b8-c62f3912d5ec)

**Comment by DeathByAutoscroll** [comment]
/team info should list the allies a team has.

**Comment by svaningelgem** [comment]
Ow! My bad. Thanks a lot for this info @DeathByAutoscroll
