### ISSUE TITLE
[FEATURE]It is possible to change the help prompt messages. You can also change the colors, etc.

### ISSUE THREAD

**Issue by yecangminga** [booksaw/BetterTeams#636]
### What is the feature request for?

It is possible to change the help prompt messages. You can also change the colors, etc.
![I~YKOW} )_Q$5DIFT_FA62H](https://github.com/user-attachments/assets/ef149c2c-8366-40e9-95ff-a44dc114cbbf)

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
Help message colours can be changed in this section of the config: 
https://github.com/booksaw/BetterTeams/blob/master/src/main/resources/config.yml#L172-L180
