### ISSUE TITLE
[BUG] TeamDisallowedPvPEvent: removed?

### ISSUE THREAD

**Issue by svaningelgem** [booksaw/BetterTeams#638]
### What is the bug?

I noticed that there was code with TeamDisallowedPvPEvent in `canDamage`. But in one of the latest commits this has been removed (unintentional merge?)

### Expected Behaviour

either remove the class (and the readme doc), or bring it back?

### How to Reproduce

See code around here: https://github.com/booksaw/BetterTeams/blob/master/src/main/java/com/booksaw/betterTeams/Team.java#L1308

### Output of /teama version

not applicable

**Comment by booksaw** [comment]
Fixed by a PR by @Hellinduction

**Comment by svaningelgem** [comment]
@booksaw : I don't know if you know, but am going to put it out here anyhow 😀: If you mention in the PR "Closes #638", and the PR gets merged, Github will automagically close the mentioned issues for you, and even add a link to it in the audit log of the issue.
