### ISSUE TITLE
[FEATURE] /team tag

### ISSUE THREAD

**Issue by DeathByAutoscroll** [booksaw/BetterTeams#64]
**Is your feature request related to a problem? Please describe.**
I wish to display a shorter tag next to player's names instead of a large team name

**Describe the solution you'd like**

The ability to use a command like `/team tag <tag>` to set a shortened name/acronym for my team and/or an option to automatically shorten team names once they are longer than X amount of characters (e.g. Really Long Team Name --> RLTM)

**Describe alternatives you've considered**

**Additional context**
Written up on behalf of another user

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update
