### ISSUE TITLE
[FEATURE]is it possible to access a disbanded team echest?

### ISSUE THREAD

**Issue by J3bo9a** [booksaw/BetterTeams#647]
### What is the feature request for?

I use this plugin on my smp, and i was the leader of my time (i was the only team member), i forgot to take some items from my team echest before disbanding it is there is any command that i can use to get the disbanded team or acce its echest?

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
No, team data is deleted when the team is disbanded so the echest contents is lost
