### ISSUE TITLE
[BUG] Deelay Dosen't work

### ISSUE THREAD

**Issue by fabiohouse** [booksaw/BetterTeams#65]
**Describe the bug**
I can't set deelay on command.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure the file "team.yml" with properly deelay on comand,
2. Wait... "team.yml" is not the correct file? "command.yml" is the one... 

When i try to rename "team.yml" in "command.yml" and reload the server... the plugin generate automatically a new "team.yml" and ignore "command.yml"

`public CooldownManager(String command) {
		File f = new File("plugins/BetterTeams/" + command + ".yml");
....`

**Comment by booksaw** [comment]
The file is named correctly when it is called team.yml

```public CooldownManager(String command) { 
    File f = new File("plugins/BetterTeams/" + command + ".yml"); ....```

command will be a variable storing the name of the command, which is provided. In the case of the /team command command will be team

This is the second report I have had of the delay not working, I will look into fixing that problem for the next update.
