### ISSUE TITLE
[BUG] team kick error

### ISSUE THREAD

**Issue by giantfurkii** [booksaw/BetterTeams#67]
We cannot kick players who are not in the game on betterteams from the team. Will this problem be solved?

**Comment by DeathByAutoscroll** [comment]
> 
> 
> We cannot kick players who are not in the game on betterteams from the team. Will this problem be solved?

Hello, I'm an admin on the official support discord server, is it possible to provide more details about this issue?

Like details descriptions or screenshots of what happens when you try to kick someone who is offline and/or any error messages in the console?

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update.
