### ISSUE TITLE
Can't delhome as team owner unless op? [BUG]

### ISSUE THREAD

**Issue by BelieverInMagic** [booksaw/BetterTeams#70]
**Describe the bug**
_A clear and concise description of what the bug is._
It appears only team owners who are oped can delhome. Sethome works, but delhome didn't until the owner was made op?

**To Reproduce**
_Steps to reproduce the behavior:_
1. Team owner runs /team delhome (while not oped and a team home is already set) and it returns text saying you can't.
2. After confirming it didn't del the home, try running it after team owner is op and then it works.

**Expected behavior**
_A clear and concise description of what you expected to happen._
I would expect the team owner can not only set home but also del the home they set? (I was going to check if there were perms I could adjust for this, but it looks like BetterTeams manages its own perms using team owner instead of ranks/roles from another perm manager so I couldn't find a good list of perms to try and manually set or adjust this.)

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Details**
_Please provide the following details about your server set-up:_
- Spigot version (found by running /version): _paper-1.16.5 (Implementing API version 1.16.5-R0.1-SNAPSHOT)_
    - Newest paper. Everything else with the plugin _seems_ to work well inspite of the new version in use.
- BetterTeams version (found by running /version BetterTeams): _3.1.18_

**Additional context**
If you do have a list of perms or know how I can adjust perms myself that would be ideal.
- In the server I'm setting up for a friend there are set teams, so we do not want the team owners to be able to promote other players or change team names, for example, so being able to give them perms such as to set home but remove their perms to promote or change name would be ideal. I know how to do this in plugins that reference vault for perms, but since BetterTeams appears to manage its own perms and only references vault for player info (I think, right?) I'm not sure how to approach it.

Otherwise, so far this is the best simple team plugin I've found that's compatible with 1.16, and none of the little issues are severe enough that I can't just let it be, but if you know any quick fixes it'd be appreciated. ^^

**Comment by BelieverInMagic** [comment]
Wait, I think I just found the permissions list (I had tried searching it a few times and didn't realize it's a link in the image in the spigot home page for BetterTeams). I'll try adjusting perms in my LuckPerms using the list. Still might want to check if team owners are automatically being given a delhome perm. (No delhome perm is listed in the perm list either. The delwarp perm is listed there but not delhome so I'm not sure if this is on purpose?)

**Comment by booksaw** [comment]
TODO:
Add delhome to the perms list

**Comment by booksaw** [comment]
I am reopening this issue as I still need to change it by default. 
The issue will be closed when the bug is fully fixed.

**Comment by BelieverInMagic** [comment]
Oop, sorry, kk, I've never used this site for issues before so I wasn't sure when to close it haha. Have a good one.

**Comment by booksaw** [comment]
Not a problem :), the issues are so I can look through the list of problems and know what to fix. When they are closed they are automatically removed from the list. So issues are closed when either they are found to be invalid (A problem with the specific servers config for example) or when they implemented in the next update (the case for this update).

**Comment by booksaw** [comment]
This bug has been fully fixed and will be included in the next update.
