### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gontijo8199** [booksaw/BetterTeams#71]
**Describe the bug**
by trying to use a plugin that overwrites the better teams join/leave msg bc i cant disable, might cause conflict, by that i mean the leave msg won't work.
**To Reproduce**
Steps to reproduce the behaviour:
1. Download the latest version of better teams
2. download join/leave custom msg plugin (one that is happening the conflict: spigotmc.org/resources/custom-join-leave-message.59300/)
3. use this in the config file or u can use the default,
4. My config file: 
5. {Title-Onjoin-Message-Main: WELCOME
Title-Onjoin-Message-Bottem: IN OUR SERVER
Join: '[+]&e %player% has joined the server!'
Leave: '[-]&e %player% has left the server!'
New-Player: '[+]&e %player% has joined for the first time!'
First-Join-Message: true
Language: EN
Title-Onjoin: false }

**Expected behaviour**
Leave msg appear like "[-]&e %player% has left the server!"
**Screenshots**
I do not have one, im not in my pc.
**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version):
- BetterTeams version (found by running /version BetterTeams): 
1.16.5 spigot version
Betterteams and Join/leave msg plugin (both latest)
PlaceHolderAPI
**Additional context**
Discord Gontijo!#1369

**Comment by booksaw** [comment]
![image](https://user-images.githubusercontent.com/13976636/109293974-77437f00-7824-11eb-86b6-8846da4b646a.png)
I have tested this config on my test server and the leave and join messages are displayed correctly.

**Comment by booksaw** [comment]
If more information comes to light showing that it is a betterteams bug, feel free to reopen the issue
