### ISSUE TITLE
team create[BUG]

### ISSUE THREAD

**Issue by Kwidcele** [booksaw/BetterTeams#72]
**Describe the bug**

Steps to reproduce the behaviour:
1. Run command /team create [teamname]
2. Enter command

Expected behaviour
When /team create command is ran and even if in team.yml is changed so people don't have to pay it still says "You are too poor to run that command"

Details
- PaperSpigot version 1.16.5:
- BetterTeams version (found by running /version BetterTeams):

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update
