### ISSUE TITLE
[BUG] team limit doesn't limit

### ISSUE THREAD

**Issue by ElijahRus250** [booksaw/BetterTeams#73]
**Describe the bug**
When you set the teamLimit it doesn't set and allows unlimited players. 

**To Reproduce**
Steps to reproduce the behaviour:
1. set config too ```
levels:
  l1:
    teamLimit: 2
    maxChests: 2
  l2:
    teamLimit: 2
    maxChests: 2
    price: 100s```
2. /team create blah
3.  /team invite <friend> x2
4. see bug

**Expected behaviour**
should limit players from joining sayings its full

**Screenshots**
n/a

**Details**
Please provide the following details about your server set-up:
- Paper 1.8
- Latest

**Additional context**
Spoke via DMS with booksaw

**Comment by booksaw** [comment]
Team invites are not players joining the team but just inviting them to join. I have tested and the config limits joining but as you cannot revoke invites it does not make sense to limit the number of invites a team can send as if they extend an invite to one person who does not accept the invite and then they invite another player who, limiting the second invite could stop a potential player even though it would still fit within the team size. 
If a team is completely full, an invite cannot be sent as there is no space for the player to join. 

From my testing, this does not appear to be a bug, if further information comes to light that shows that it is, feel free to reopen the issue.

**Comment by ElijahRus250** [comment]
Feature suggestion to solve this issue:

when sending out an invite you are limited by the max team size for the amount of invites you can send out. After an invite is sent out you will have a config amout of seconds to accept it or it will auto cancel. 

Example:

Player 1 creates a team and the max team size is 2. He invites player 2 and tries to invite player 3 but the max amount of invites have been sent out. Player 2 decides to ignore the invite so after x seconds it will cancel and player 1 can invite player 3

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update.
