### ISSUE TITLE
[FEATURE] Add integration with GriefPrevension

### ISSUE THREAD

**Issue by FlsdMeat** [booksaw/BetterTeams#74]
Thinking of building a server soon. It would be great if Team Owners gained permissions to do specific things that members or regular users could not. 

      Here: [Grief Prevention Wiki](https://github.com/TechFortress/GriefPrevention/wiki) is a claim space plugin. With it you can give permissions that gain more or less maximum claim space for their base or builds. I would think this would be a great idea for say letting regular users have a specific claim amount on a server, say 4 chunks, while teams would get 8 chunks, plus for every rank they gain they would also gain a certain amount of more space so they could increase their base size, or setup new bases around the server.
       Through grief prevention, there is this command, 'adjustbonusclaimblocks &p 100', but this is targeting single players. The other command is 'AdjustBonusClaimBlocks [player/permission target] [amount]'. Here you could add say a team leader with the permission of Team Leader, and for every team rank add a number to the end of the permission. That way, you could head into Grief Prevention and set the amount of max claim space for each of the ranks.
        It could also be a feature in which the server can decide if they would like members of teams to be allowed to claim land or not. 
        In theory this could be nice if this was a offline feature, but when online how would factions actually fight each other, Grief Prevention does allow the server to decide if PvP is allowed on claims or not, so blowing up a base might be impossible, but killing the players their wouldn't be, and you can also turn stealing on.

**Comment by booksaw** [comment]
This is starting to sound a lot like factions. How would this be different from factions?
I plan to implement a different land claim plugin (see the feature request for it here): https://github.com/booksaw/BetterTeams/issues/63
I will leave this issue open so you can respond to my question.

**Comment by FlsdMeat** [comment]
Welp, it's not like I have ever used a factions plugin, so I can't answer that question. After reading that thread I understand where Ovirse is coming from, everyone on my server enjoys your plugin so in a perfect world it would be nice to stick to it. But maybe factions would be the way to go for this idea. If you do think it would be a nice idea to add a module between BetterTeams and GriefPrevension, I would be all for it, but time is time. No worries if it's a stretch.

**Comment by booksaw** [comment]
I sadly do not currently have time to implement a second land claim style feature. 

If I have time further down the line I may return to this idea but for now I am closing this issue.
