### ISSUE TITLE
[QUESTION] How do I disable the warp feature?

### ISSUE THREAD

**Issue by NotErikUden** [booksaw/BetterTeams#76]
As the title says, how do I disable the warp feature and only leave behind the best parts of the BetterTeams plugin?

**Comment by booksaw** [comment]
By disabling the relevant permissions. Find the correct ones and an explanation of how to do it here: https://github.com/booksaw/BetterTeams/wiki/Permissions

(Close the issue when you are finished)

**Comment by NotErikUden** [comment]
Thank you very much!
