### ISSUE TITLE
[FEATURE] Disable pvp protection in certain worlds.

### ISSUE THREAD

**Issue by GuazP** [booksaw/BetterTeams#77]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to call team owner to disable pvp inside team to play arena or other minigame on server.

**Describe the solution you'd like**
Make configuration to define certain worlds where disabled pvp between teammates aren't working, without constant switching pvp/nonpvp by owner of team.

**Describe alternatives you've considered**
Maybe worldguards flags to set regions without team non-pvp could be an alternative.

**Additional context**
Not suitable

**Comment by booksaw** [comment]
I have added support for a new world guard flag called' teampvp' which when set to allow in a region will allow team killing regardless of if the config has it set to disable. 
This will be included in the next update
