### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DeathByAutoscroll** [booksaw/BetterTeams#79]
**Describe the bug**
Console spam on fresh installation of BetterTeams plugin

**To Reproduce**
Steps to reproduce the behaviour:
1. Start up a server where BetterTeams has no been installed, or delete messages.yml
2. Cry in console spam

**Expected behaviour**

A lovely unspammed console

**Screenshots**
![2021-03-13-13-26-46](https://user-images.githubusercontent.com/39137649/111031694-b49d3480-8400-11eb-988e-ccaeb796528a.png)

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): version git-Spigot-a19903d-e1ebdd9
- BetterTeams version (found by running /version BetterTeams): 3.1.20

**Additional context**
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update.
