### ISSUE TITLE
API[FEATURE]

### ISSUE THREAD

**Issue by DragonTech409** [booksaw/BetterTeams#80]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think it would be nice if there could come an API for the player's title like %betterTeams_title%
Would be really helpfull for me, thanks in advance.

**Describe alternatives you've considered**
I could also add an rank plugin but I only need 1 more thing which already is in the betterTeams plugin, but there's just no API for it, yet.

**Additional context**
I'm willing to use it in a scoreboard.

**Comment by DeathByAutoscroll** [comment]
Hello, I am an admin on the official help server for BetterTeams, is it possible to provide a few more details and clarify what an api call for %betterTeams_title% would/should do?

**Comment by booksaw** [comment]
Do you mean with placeholder API? because that is what the formatting is like 
https://github.com/booksaw/BetterTeams/wiki/PlaceholderAPI

**Comment by booksaw** [comment]
I am assuming the lack of response means that the problem has been solved. 
I am closing the issue, if you have any more issues feel free to open a new one
