### ISSUE TITLE
[/TEAM TAG BUG]

### ISSUE THREAD

**Issue by Kytonage** [booksaw/BetterTeams#81]
**Describe the bug**
/team tag {tag} does not work correctly with /team color {color}.

**To Reproduce**
Steps to reproduce the behaviour:
1. *Be the owner of a team*
2. Do /team tag {TAG}
3. If you go into tab or look at other players it will show the tag as the basic starter team color. Although, if you send a message in chat it will show correctly.
4. Trying to give the team a color through /team color {color} (again) does not work either.

**Expected behaviour**
The teams tag is suppose to be the same color as before setting the tag.

**Screenshots**
![2021-03-16_16 34 11](https://user-images.githubusercontent.com/80786117/111377244-cc7dee00-8676-11eb-8527-c33bb2435520.png)
![2021-03-16_16 36 00](https://user-images.githubusercontent.com/80786117/111377270-d30c6580-8676-11eb-9c88-65453a8d903a.png)

**Details**
Please provide the following details about your server set-up:
- Spigot version (found by running /version): "This server is running Paper version git-Paper-553 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)"
Previous version: git-Paper-551 (MC: 1.16.5)
- BetterTeams version (found by running /version BetterTeams): 3.1.20

**Additional context**

**Comment by booksaw** [comment]
This bug has been fixed and will be included in the next update.
