### ISSUE TITLE
[FEATURE] Error Handling For Score Add

### ISSUE THREAD

**Issue by jahua50** [booksaw/BetterTeams#85]
Is it possible to not give an error when using "score add" & the player is not on a team?
Im using elitemobs system, and when mobs dies, the players' scores are added.
But if the players are not on a team, it will throw out an error.
Please consider this feature, thanks!

**Comment by booksaw** [comment]
By thow out an error, do you mean an error in the console or the following message:
![image](https://user-images.githubusercontent.com/13976636/112141562-537a1b80-8bcd-11eb-90c7-c33f40867849.png)

**Comment by jahua50** [comment]
Sorry that i didnt clearify, i meant the error in the console.
![image](https://user-images.githubusercontent.com/35772634/112142752-f3f22f00-8c11-11eb-9d49-b46b52f30bf7.png)

**Comment by booksaw** [comment]
Could you please screenshot the full error message, as the details I need to fix the problem will be lower in the error message

**Comment by jahua50** [comment]
no problem. thanks in advance~
![image](https://user-images.githubusercontent.com/35772634/112144050-a676c180-8c13-11eb-83db-a16c1ed99007.png)
![image](https://user-images.githubusercontent.com/35772634/112144075-b098c000-8c13-11eb-84e6-d8edc06fe336.png)

**Comment by booksaw** [comment]
Thanks, you were so close, there will be about 5 more lines of the error under the bottom screenshot which are the specific 5 lines that I need to see (you dont have to send the rest again just the few lines underneath NullPointerException as they will tell me the line number of the bug)

**Comment by jahua50** [comment]
![image](https://user-images.githubusercontent.com/35772634/112147065-3ec27580-8c17-11eb-892e-58eef6cc90f7.png)
but i dont see other error messages underneath the nullpointer exception

**Comment by booksaw** [comment]
Ah, there is normally something there. Well thanks, ill look into it

**Comment by jahua50** [comment]
Thanks a LOT!!!

**Comment by booksaw** [comment]
Ah, I think I know what your error is: 
![image](https://user-images.githubusercontent.com/13976636/112147639-dbafef00-8bd4-11eb-9484-5799d5bff420.png)
at the top of the error message it includes the command run which includes '$players' I think the command you have configured is incorrect, at a guess it should be $player$ which will be replaced with the player name.

Ive added some extra error checking to the command, hopefully that will fix it (this will be included in the next update). If it does not, let me know and ill download the elitemobs plugin and test with it.
