### ISSUE TITLE
[BUG] Console Error

### ISSUE THREAD

**Issue by jahua50** [booksaw/BetterTeams#88]
![image](https://user-images.githubusercontent.com/35772634/112674289-b35c1500-8ea0-11eb-9755-6e40c5703080.png)

Dont know what happened, but this error showed up in the console.
Thanks in advance~

**Comment by booksaw** [comment]
I thought I had fixed that problem in the previous update. Ill have a bug fix out tomorrow for it.

**Comment by jahua50** [comment]
ok Thanks a lot!

**Comment by jahua50** [comment]
I think that i didnt use the latest version. I was using 3.1.21. Sorry for that.

**Comment by booksaw** [comment]
I've just checked, in version 3.1.22 bows are working correctly. 
Feel free to make a new issue if other problems arise.
