### ISSUE TITLE
[FEATURE] Allies

### ISSUE THREAD

**Issue by booksaw** [booksaw/BetterTeams#9]
**Is your feature request related to a problem? Please describe.**
none

**Describe the solution you'd like**
/team ally <team> - Requests to become an ally with another team (once both teams have typed, an alliance is started)
/team normal <team> - Removes an ally 

Alliance: Cannot hit members of allied teams. 
Alliances should show up on /team info

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by BboyZeroOne** [comment]
I would suggest to change it to '/team neutral' instead of '/team normal'.

**Comment by BboyZeroOne** [comment]
2. Add a placeholder for team allies.

**Comment by booksaw** [comment]
Add an ally chat

**Comment by booksaw** [comment]
All suggested features relating to ally chat have been added in this [commit to master](https://github.com/booksaw/BetterTeams/commit/a3d33a836a0222f819954badb5950087f577f8f9)
