### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by NotAShelf** [booksaw/BetterTeams#90]
**Is your feature request related to a problem? Please describe.**
no, it's merely a feature request

What I am looking for is more flexibility on how we use the modules and the plugin itself.
- Being able to disable some of the core features, like team homes or balance.
- Being able to specify in which worlds does the plugin work (this is especially important for me)
- A form of score system for better competition (maybe hooks for plugins like goldenchallenges or quest plugins for better point collecting?)
- A chat hook for VentureChat so that we are able to generate a specific channels for it, which we may spy without the help of BetterTeams; allowing the developers/server owners to collect all things chat in one place. (not much of a priority, but would  be really nice to have)

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**

(im yet to figure out why the feature request template looks like a bug report)

**Comment by booksaw** [comment]
> What I am looking for is more flexibility on how we use the modules and the plugin itself.
> 
> * Being able to disable some of the core features, like team homes or balance.

You can do this with a permissions: https://github.com/booksaw/BetterTeams/wiki/Permissions
If the feature shows in /team info, you can disable that message to ''. For example: 
`info.name: ''`
This will stop it from showing up when you run /team info

> * Being able to specify in which worlds does the plugin work (this is especially important for me)

Why do you want this? Have you looked into plugins like 'PerWorldPlugin'

> * A form of score system for better competition (maybe hooks for plugins like goldenchallenges or quest plugins for better point collecting?)

This can often be done by setting the other plugin to run the command `/teama score add <player>` to add score to a players team
If the plugin you are interested in does not have support to run commands, make a feature request specifically for that plugin, including exactly what you want the integration to do along with a link to the plugin spigot page.

> * A chat hook for VentureChat so that we are able to generate a specific channels for it, which we may spy without the help of BetterTeams; allowing the developers/server owners to collect all things chat in one place. (not much of a priority, but would  be really nice to have)

How is this different from /teama chatspy (im not familiar with VentureChat)

> 
> **Describe the solution you'd like**
> N/A
> 
> **Describe alternatives you've considered**
> N/A
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 
> (im yet to figure out why the feature request template looks like a bug report)
The feature request template does not look like the bug report one. They are similar but have different questions.

**Comment by booksaw** [comment]
No reply has been received within 17 days. I am closing the issue.
Feel free to open another issue to address the comments made in this one.
