### ISSUE TITLE
[FEATURE] Permission for each team name to allow for permission based sorting 

### ISSUE THREAD

**Issue by ElijahRus250** [booksaw/BetterTeams#91]
**Is your feature request related to a problem? Please describe.**
When sorting players in tab it would be really nice to be able to put the respective players on a team next to each other. 

**Describe the solution you'd like**
Ability to give players a permission when they join a team to allow for permission based sorting.

When someone joins a team ur gives them a permission such as betterteams.teamname.<name> and then when they leave or disband it removes the perm.

**Describe alternatives you've considered**
unknown

**Additional context**
Discord chat https://discord.com/channels/295271438112522241/728527914630643785/825860020766900244

**Comment by booksaw** [comment]
A command section has been implemented and will be included in the next update. 
The usage of commands makes the feature more versatile.

The new sections will not automatically be added to prexisting configs to avoid unwanted changes, you can add them manually from the default config: https://github.com/booksaw/BetterTeams/blob/master/config.yml
