### ISSUE TITLE
[FEATURE] glowing

### ISSUE THREAD

**Issue by STEVE1010101** [booksaw/BetterTeams#96]
Maybe you can add team glowing options
When player toggle 
It will let same team player glowing

**Comment by booksaw** [comment]
What command would be used to activate the glowing effect? 
Would activating the glowing effect only enable it for them or the whole team?

**Comment by booksaw** [comment]
This issue is being closed due to inactivity. 
If you wish to continue this discussion please create a new issue linking to this one answering any questions.
