### ISSUE TITLE
[FEATURE] Maximum Move Distance for "noMove" option

### ISSUE THREAD

**Issue by megargayu** [booksaw/BetterTeams#97]
**Is your feature request related to a problem? Please describe.**
Whenever a villager or peaceful mob, or one of my team members moves a player even a tiny bit, the warping automatically fails with the `noMove` option enabled.

**Describe the solution you'd like**
The `noMove` config option is removed, and instead replaced with `maxMoveDist`. When the value of `maxMoveDist` is `-1`, then players can move as much as they want (acts exactly like `noMove: false`). When the value of `maxMoveDist` is `0`, then players cannot move at all (acts exactly like `noMove: true`). However, when the value is any other positive number, that is the maximum amount of blocks that players can move before they are not allowed to warp. For example, with `maxMoveDist: 1`, the player can only move 1 block - if the player moves 2 blocks, the warp fails.

**Describe alternatives you've considered**
The `noMove` config option could also be kept and instead a new config option added called `maxMoveDist`, which is only used when `noMove` is enabled. This could default to `0` so that servers that update their plugin don't have to change anything. The behaviour will work exactly like the behaviour described above except that the `-1` value will not do anything/is not a valid option - instead, you would set `noMove: false`.

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update.
